<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Termeh Shafie">
<title>Foundational Statistics - 9&nbsp; What is Probability?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../rv-probdists.html" rel="next">
<link href="../prob-theory/prob-concepts.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../prob-theory/prob-concepts.html">Probability Theory</a></li><li class="breadcrumb-item"><a href="../prob-theory/what-is-prob.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundational Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/what-is-stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Unavoidable Math</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-surveys.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Surveys: Key Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/variable-class.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variable Classification</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Descriptive Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/describe-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing a Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/central-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of Central Tendency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/dispersion-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Measures of Dispersion</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Probability Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/what-is-prob.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Random Variables and Probability Distributions</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Sampling and Sampling Distributions</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Inferential Statistics</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Chi Square Tests</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Summary</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">References</span></span>
  </li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#fundamental-assumptions-of-probability" id="toc-fundamental-assumptions-of-probability" class="nav-link active" data-scroll-target="#fundamental-assumptions-of-probability"><span class="header-section-number">9.1</span> Fundamental Assumptions of Probability</a></li>
  <li><a href="#kolmogorovs-axioms" id="toc-kolmogorovs-axioms" class="nav-link" data-scroll-target="#kolmogorovs-axioms"><span class="header-section-number">9.2</span> Kolmogorov’s Axioms</a></li>
  <li>
<a href="#defining-probability" id="toc-defining-probability" class="nav-link" data-scroll-target="#defining-probability"><span class="header-section-number">9.3</span> Defining Probability</a>
  <ul class="collapse">
<li><a href="#the-classical-definition" id="toc-the-classical-definition" class="nav-link" data-scroll-target="#the-classical-definition"><span class="header-section-number">9.3.1</span> The Classical Definition</a></li>
  <li><a href="#the-frequentist-definition" id="toc-the-frequentist-definition" class="nav-link" data-scroll-target="#the-frequentist-definition"><span class="header-section-number">9.3.2</span> The Frequentist Definition</a></li>
  <li><a href="#the-subjective-definition" id="toc-the-subjective-definition" class="nav-link" data-scroll-target="#the-subjective-definition"><span class="header-section-number">9.3.3</span> The Subjective Definition</a></li>
  </ul>
</li>
  <li><a href="#uniform-probabilitis" id="toc-uniform-probabilitis" class="nav-link" data-scroll-target="#uniform-probabilitis"><span class="header-section-number">9.4</span> Uniform Probabilitis</a></li>
  <li>
<a href="#counting-outcomes-combinatorial-methods" id="toc-counting-outcomes-combinatorial-methods" class="nav-link" data-scroll-target="#counting-outcomes-combinatorial-methods"><span class="header-section-number">9.5</span> Counting Outcomes: Combinatorial Methods</a>
  <ul class="collapse">
<li><a href="#drawing-with-replacemen-order-matters" id="toc-drawing-with-replacemen-order-matters" class="nav-link" data-scroll-target="#drawing-with-replacemen-order-matters"><span class="header-section-number">9.5.1</span> Drawing with Replacemen, Order Matters</a></li>
  <li><a href="#drawing-with-replacemen-ignoring-order" id="toc-drawing-with-replacemen-ignoring-order" class="nav-link" data-scroll-target="#drawing-with-replacemen-ignoring-order"><span class="header-section-number">9.5.2</span> Drawing with Replacemen, Ignoring Order</a></li>
  <li><a href="#drawing-without-replacement-order-matters" id="toc-drawing-without-replacement-order-matters" class="nav-link" data-scroll-target="#drawing-without-replacement-order-matters"><span class="header-section-number">9.5.3</span> Drawing without Replacement, Order Matters</a></li>
  <li><a href="#drawing-without-replacement-ignoring-order" id="toc-drawing-without-replacement-ignoring-order" class="nav-link" data-scroll-target="#drawing-without-replacement-ignoring-order"><span class="header-section-number">9.5.4</span> Drawing without Replacement, Ignoring Order</a></li>
  </ul>
</li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../prob-theory/prob-concepts.html">Probability Theory</a></li><li class="breadcrumb-item"><a href="../prob-theory/what-is-prob.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Now that we have explored fundamental probability concepts, such as unions, intersections, complements, and mutually exclusive events, we can use these ideas to formally define probability itself.</p>
<p>Using the relationships between events that we have discussed, we can also establish the formal rules of probability and see how these concepts help in calculating probabilities for different types of events.</p>
<section id="fundamental-assumptions-of-probability" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="fundamental-assumptions-of-probability">
<span class="header-section-number">9.1</span> Fundamental Assumptions of Probability</h2>
<p>Probability theory provides a framework for modeling randomness and quantifying uncertainty. At its core, it relies on three fundamental assumptions that define how probabilities are assigned to different outcomes in a random experiment.</p>
<ol type="1">
<li><p>First, every probability calculation begins with a random experiment that has a well-defined sample space, denoted as <span class="math inline">\(\Omega = \{O_1, O_2, \dots, O_n\}\)</span>. This sample space represents all possible outcomes of the experiment, ensuring that every event of interest is accounted for.</p></li>
<li><p>Second, once the sample space is established, each outcome <span class="math inline">\(O_i\)</span> is assigned a probability <span class="math inline">\(P(O_i)\)</span> for <span class="math inline">\(i = 1,2,\ldots, n\)</span>, representing the likelihood of that specific event occurring. These probabilities must follow</p></li>
</ol>
<ul>
<li>
<strong>non-negativity</strong>, meaning that probabilities must always fall within the range <span class="math inline">\(0 \leq P(O_i) \leq 1\)</span> for all outcomes. This ensures that an event can never have a negative probability, and the probability of a certain event is at most 1.<br>
</li>
<li>and the <strong>total probability principle</strong>, stating that the sum of all assigned probabilities must equal 1:</li>
</ul>
<p><span class="math display">\[P(O_1) + P(O_2) + \dots + P(O_n) = \sum_{i=1}^{n} P(O_i) = 1\]</span></p>
<p>These fundamental principles form the backbone of probability theory, ensuring a structured and consistent way to reason about uncertain events. By defining probabilities within these constraints, we can build models that capture real-world randomness and variability in a mathematically rigorous way.</p>
<p>The probability of an event <span class="math inline">\(A\)</span>, denoted as <span class="math inline">\(P(A)\)</span>, is determined by summing the probabilities of all individual outcomes that make up <span class="math inline">\(A\)</span>: <span class="math display">\[ P(A) = \sum_{O_i \in A} P(O_i) \]</span></p>
<p>This rule ensures that if an event consists of multiple possible outcomes, its probability is found by adding up the probabilities of each contributing outcome.</p>
<p>Since probability values must be assigned consistently, we require a formal system that ensures logical coherence in probability calculations. This leads us to <strong>Kolmogorov axioms</strong>, which form the foundation of modern probability theory.</p>
</section><section id="kolmogorovs-axioms" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="kolmogorovs-axioms">
<span class="header-section-number">9.2</span> Kolmogorov’s Axioms</h2>
<p>To maintain consistency in probability assignments, Andrey Kolmogorov formulated three fundamental axioms:</p>
<ol type="1">
<li><p><strong>Non-Negativity:</strong> The probability of any event <span class="math inline">\(A\)</span> is always greater than or equal to zero:<br><span class="math display">\[P(A) \geq 0\]</span><br>
This ensures that probabilities are never negative.</p></li>
<li><p><strong>Total Probability:</strong> The probability of the entire sample space <span class="math inline">\(\Omega\)</span> (i.e., the event that some outcome must occur) is exactly <strong>1</strong>:<br><span class="math display">\[P(\Omega) = 1\]</span><br>
This guarantees that probability is correctly distributed among all possible outcomes.</p></li>
<li><p><strong>Additivity for Mutually Exclusive Events:</strong> If two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> cannot occur at the same time (i.e., they are mutually exclusive), then the probability of either occurring is the sum of their individual probabilities:<br><span class="math display">\[P(A \cup B) = P(A) + P(B)\]</span><br>
This principle extends to any finite or countable number of mutually exclusive events. If <span class="math inline">\(A_1, A_2, \dots, A_k\)</span> are <strong>pairwise disjoint events</strong>, then the probability of their union is the sum of their individual probabilities: <span class="math display">\[P(A_1 \cup A_2 \cup \dots \cup A_k) = P(A_1) + P(A_2) + \dots + P(A_k)\]</span></p></li>
</ol>
<p>These axioms are not just abstract rules; they provide the backbone for all probability calculations, from simple games of chance to risk assessments in finance, medicine, and machine learning. By defining probability through outcome summation and enforcing consistency through these axioms, we build a powerful and reliable framework for understanding and modeling uncertainty, thus allowing for meaningful calculations and predictions about uncertain events.</p>
</section><section id="defining-probability" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="defining-probability">
<span class="header-section-number">9.3</span> Defining Probability</h2>
<p>The probability of an event <span class="math inline">\(A\)</span>, denoted as <span class="math inline">\(P(A)\)</span>, is a measure of how likely it is that the event will occur. Different interpretations of probability exist, leading to various probability definitions.</p>
<section id="the-classical-definition" class="level3" data-number="9.3.1"><h3 data-number="9.3.1" class="anchored" data-anchor-id="the-classical-definition">
<span class="header-section-number">9.3.1</span> The Classical Definition</h3>
<p>The <strong>classical definition</strong> of probability, derived from basic counting principles, states that if a random experiment has <span class="math inline">\(N\)</span> possible outcomes, and exactly <span class="math inline">\(N_A\)</span> of these correspond to event <span class="math inline">\(A\)</span> occurring, then the probability of <span class="math inline">\(A\)</span> is given by: <span class="math display">\[P(A) = \frac{N_A}{N}\]</span> This is known as a <strong>theoretical probability assignment</strong>, as it assumes that all outcomes are equally likely.</p>
</section><section id="the-frequentist-definition" class="level3" data-number="9.3.2"><h3 data-number="9.3.2" class="anchored" data-anchor-id="the-frequentist-definition">
<span class="header-section-number">9.3.2</span> The Frequentist Definition</h3>
<p>An alternative way to define probability is through relative frequency. In the <strong>frequentist interpretation</strong>, the probability of an event <span class="math inline">\(A\)</span> is understood as the proportion of times <span class="math inline">\(A\)</span> occurs in a very long sequence of repeated random experiments. This can be expressed mathematically as: <span class="math display">\[P(A) \approx \frac{n_A}{n}\]</span> where:</p>
<ul>
<li>
<span class="math inline">\(n_A\)</span> is the number of times event <span class="math inline">\(A\)</span> occurs.</li>
<li>
<span class="math inline">\(n\)</span> is the total number of trials.</li>
</ul>
<p>As the number of trials <span class="math inline">\(n\)</span> increases, the relative frequency of event <span class="math inline">\(A\)</span> stabilizes and approaches its probability <span class="math inline">\(P(A)\)</span>, aligning with the classical probability definition. In other words, if we repeat an experiment an extremely large number of times, the empirical probability we observe will converge toward a fixed value. This phenomenon is known as the <strong>stability of relative frequencies</strong> and serves as the empirical foundation of probability theory. It explains why probabilities can be estimated by repeated experimentation, as observed frequencies tend to settle around a fixed value over a large number of trials. AN example of this is shown below in Example 9.1.</p>
<p>This probability defintion is known as the <strong>empirical probability assignment</strong>, meaning that probabilities are assigned based on observed data rather than theoretical assumptions.</p>
</section><section id="the-subjective-definition" class="level3" data-number="9.3.3"><h3 data-number="9.3.3" class="anchored" data-anchor-id="the-subjective-definition">
<span class="header-section-number">9.3.3</span> The Subjective Definition</h3>
<p>Another way to interpret probability is through <strong>subjective probability</strong>, where probability is understood as a*measure of personal belief in the occurrence of an event. Formally, the probability of an event <span class="math inline">\(A\)</span> in this interpretation is given by:</p>
<p><span class="math display">\[P(A) = \text{a measure of how strongly a person believes that } A \text{ will occur}\]</span> For example, one might estimate the probability of rain tomorrow as <strong>30%</strong>, or believe that the chance of Germany winning the next Eurovision Song Contest is <strong>70%</strong>. These probabilities are not derived from mathematical models or repeated experiments but instead reflect an individual’s degree of confidence in a given outcome.</p>
<p>This approach known as the <strong>subjective probability assignment</strong> is commonly used in decision-making under uncertainty, such as betting, economics, and risk assessment, where probabilities are assigned based on available information, intuition, or expert judgment rather than empirical frequency or formal statistical models.</p>
<section id="example-9.1-stability-of-relative-frequencies" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.1-stability-of-relative-frequencies">Example 9.1: Stability of Relative Frequencies</h4>
<p>How many sixes can we expect if we roll a die 10 times? 1000 times? 10,000 times?</p>
<p>Let event <span class="math inline">\(A\)</span> represent rolling a six when tossing a fair die. The theoretical probability of rolling a six is:</p>
<p><span class="math display">\[P(A) = \frac{1}{6} \approx 0.167\]</span></p>
<p>This suggests that in 10 rolls, we should expect approximately 1 to 2 sixes.</p>
<p>To illustrate this, nine people each rolled a die 10 times, producing the following results for the number of sixes obtained: <span class="math inline">\(1, 3, 1, 2, 2, 5, 4, 0, 2\)</span></p>
<p>In total, there were 90 rolls, with a total of: <span class="math inline">\(1+3+1+2+2+5+4+0+2 = 20\)</span> occurrences of a six. The relative frequency of rolling a six in this experiment was: <span class="math display">\[\frac{n_A}{n} = \frac{20}{90} = 0.22\]</span></p>
<p>What happens if we roll the die many more times? Using a computer simulation, the die was rolled 1000, 10 000 and 100 000 times, resulting in 140, 1726, and 16 745 sixes. The results are summarized in <a href="#tbl-die" class="quarto-xref">Table&nbsp;<span>9.1</span></a>.</p>
<div id="tbl-die" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-die-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Summary of rolling a fair six-sided die multiple times, showing how the relative frequency of rolling a six approaches the theoretical probability 0.167 (16.7%) as the number of trials increases.
</figcaption><div aria-describedby="tbl-die-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead><tr class="header">
<th>Number of 🎲 Rolls</th>
<th>Number of Sixes</th>
<th>Relative Frequency</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>10</td>
<td>2</td>
<td>0.20 (20%)</td>
</tr>
<tr class="even">
<td>90</td>
<td>20</td>
<td>0.22 (22%)</td>
</tr>
<tr class="odd">
<td>1,000</td>
<td>140</td>
<td>0.14 (14%)</td>
</tr>
<tr class="even">
<td>10,000</td>
<td>1,726</td>
<td>0.173 (17.3%)</td>
</tr>
<tr class="odd">
<td>100,000</td>
<td>16,745</td>
<td>0.167 (16.75%)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>As the number of trials increases, the observed relative frequency tends to stabilize around the theoretical probability. This illustrates the <strong>law of large numbers</strong>, which states that the empirical probability of an event converges to its theoretical probability as the number of trials increases. We’ll return to this later on.</p>
</section></section></section><section id="uniform-probabilitis" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="uniform-probabilitis">
<span class="header-section-number">9.4</span> Uniform Probabilitis</h2>
<p>In many practical situations, it is reasonable to assume that all outcomes of a random experiment are equally likely. This is known as a <strong>uniform probability model</strong>.</p>
<p>For an experiment where each outcome occurs with equal probability, the probability of an event <span class="math inline">\(A\)</span> can be calculated as:</p>
<p><span class="math display">\[P(A) = \frac{N_A}{N}\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(N\)</span> is the total number of possible outcomes.</li>
<li>
<span class="math inline">\(N_A\)</span> is the number of favorable outcomes (i.e., outcomes where event <span class="math inline">\(A\)</span> occurs).</li>
</ul>
<p>This applies to all situations where each outcome has the same probability of occurring.</p>
<section id="example-9.2-rolling-two-dice" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.2-rolling-two-dice">Example 9.2: Rolling Two Dice 🎲🎲</h4>
<p>Consider rolling two fair six-sided dice. Since each die has six faces, there are a total of:</p>
<p><span class="math display">\[6 \times 6 = 36\]</span><br>
possible outcomes, all of which are assumed to be equally likely. This is illustrated below where each star represents a possible combination of each roll of the two dice:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="what-is-prob_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What is the probability of rolling two sixes?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Define event <span class="math inline">\(A\)</span> as the event of rolling a six on both dice. Since there is only one way to get this outcome <span class="math inline">\((6,6)\)</span> among the 36 possible outcomes, the probability of <span class="math inline">\(A\)</span> is: <span class="math display">\[P(A) = \frac{1}{36} \]</span></p>
<p>Thus, the likelihood of rolling double sixes in a single roll is <strong>1 in 36</strong>, or approximately <strong>2.78%</strong>.</p>
<p>Below in <a href="#tbl-dice" class="quarto-xref">Table&nbsp;<span>9.2</span></a>, all possible outcome combinations and their corresponding probaiblitis are given. The probability of rolling double sixes in a single roll is given the last row of this table.</p>
<div id="tbl-dice" class="center quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.2: The probability distribution of sums when rolling two six-sided dice.
</figcaption><div aria-describedby="tbl-dice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="center table">
<thead><tr class="header">
<th>Sum</th>
<th>Number of Outcomes</th>
<th>Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>1</td>
<td>1/36 (2.78%)</td>
</tr>
<tr class="even">
<td>3</td>
<td>2</td>
<td>2/36 (5.56%)</td>
</tr>
<tr class="odd">
<td>4</td>
<td>3</td>
<td>3/36 (8.33%)</td>
</tr>
<tr class="even">
<td>5</td>
<td>4</td>
<td>4/36 (11.11%)</td>
</tr>
<tr class="odd">
<td>6</td>
<td>5</td>
<td>5/36 (13.89%)</td>
</tr>
<tr class="even">
<td>7</td>
<td>6</td>
<td>6/36 (16.67%)</td>
</tr>
<tr class="odd">
<td>8</td>
<td>5</td>
<td>5/36 (13.89%)</td>
</tr>
<tr class="even">
<td>9</td>
<td>4</td>
<td>4/36 (11.11%)</td>
</tr>
<tr class="odd">
<td>10</td>
<td>3</td>
<td>3/36 (8.33%)</td>
</tr>
<tr class="even">
<td>11</td>
<td>2</td>
<td>2/36 (5.56%)</td>
</tr>
<tr class="odd">
<td>12</td>
<td>1</td>
<td>1/36 (2.78%)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</div>
</section></section><section id="counting-outcomes-combinatorial-methods" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="counting-outcomes-combinatorial-methods">
<span class="header-section-number">9.5</span> Counting Outcomes: Combinatorial Methods</h2>
<p>In many probability problems, it is not always as straightforward to determine how many possible outcomes exist or how many outcomes belong to a particular event. Fortunately, there are efficient counting methods that work in a wide range of situations. These methods are based on <strong>combinatorics</strong>, which provides systematic ways to count possible outcomes (see <a href="../introduction/intro-math.html" class="quarto-xref"><span>Chapter 2</span></a>).</p>
<p>When dealing with such compound random experiments, where multiple steps or selections are involved, we often use the <strong>urn model</strong> (introduced in <a href="../introduction/intro-surveys.html" class="quarto-xref"><span>Chapter 3</span></a>) to represent the problem mathematically. This allows us to determine the number of ways an event can occur systematically.</p>
<p>One key distinction in counting problems is whether selection is <strong>with or without replacement</strong>.</p>
<ul>
<li><p>If a ball is drawn from an urn and returned before the next draw, then every selection remains independent, and the number of available choices does not change. This is known as <strong>drawing with replacement</strong>. For example, if an urn contains six balls, each ball has a <span class="math inline">\(1/6\)</span> probability of being chosen, and this probability remains the same for every draw.</p></li>
<li><p>In contrast, <strong>drawing without replacement</strong> means that once a ball is selected, it is not returned to the urn. This affects the probability of subsequent draws. A common example is a lottery draw, where seven winning numbers are selected from a total of 35 balls. Since each number can only appear once, this is an example of drawing without replacement.</p></li>
</ul>
<p>Another important factor is whether the <strong>order of selection</strong> matters when counting possibilities.</p>
<ul>
<li><p>In some cases, order does matter. For example, imagine that a company requires employees to create five-letter security codes using the letters A, B, C, D, and E. Here the order of the letters celarly matters since password <em>ABCDE</em> is different from password <em>ACBDE</em>. This means the number of possible passwords availbale to choose from is determined by <strong>permutations</strong>, where order plays a role.</p></li>
<li><p>In other cases, order does not matter. Returning to the <strong>lottery example</strong>, suppose the machine selects the balls in the order 1,2,3,4,5,6,7. This sequence represents the same lottery result as if the balls had been drawn in the order 7,6,5,4,3,2,1. Since the order of selection does not change the outcome, this scenario follows <strong>combinations</strong>, where only the chosen numbers matter, not their sequence.</p></li>
</ul>
<p>By understanding whether we are dealing with <strong>replacement or no replacement</strong> and <strong>ordered or unordered selection</strong>, we can use combinatorial techniques to systematically count possible outcomes in probability problems.</p>
<section id="drawing-with-replacemen-order-matters" class="level3" data-number="9.5.1"><h3 data-number="9.5.1" class="anchored" data-anchor-id="drawing-with-replacemen-order-matters">
<span class="header-section-number">9.5.1</span> Drawing with Replacemen, Order Matters</h3>
<section id="example-9.3-pin-code-generation" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.3-pin-code-generation">Example 9.3: PIN Code Generation</h4>
<p>Consider a four-digit PIN code, where each digit can be any number from 0 to 9. Since each digit is chosen independently and can be repeated, every unique sequence forms a distinct PIN code.</p>
<p>This is an example of <strong>permutations with repetition</strong>, where the total number of possible PIN codes is given by: <span class="math display">\[N^n\]</span> where:</p>
<ul>
<li>
<span class="math inline">\(N\)</span> is the number of available choices for each digit (10 digits: 0–9).</li>
<li>
<span class="math inline">\(n\)</span> is the number of digits in the PIN code (4-digit code). Applying the formula: <span class="math display">\[10^4 = 10,000 \]</span>
</li>
</ul>
<p>This means there are 10,000 unique PIN codes that can be generated under these conditions.</p>
</section><section id="example-9.4-vehicle-registration-numbers-in-sweden" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.4-vehicle-registration-numbers-in-sweden">Example 9.4: Vehicle Registration Numbers in Sweden</h4>
<p>How many possible vehicle registration numbers exist in Sweden? In Swedish license plates, a registration number consists of three letters followed by three digits. Since letters and digits can be repeated, this follows the rule of <strong>permutations with repetition</strong>.</p>
<p>To calculate the total number of possible license plates, we consider:</p>
<ul>
<li>The first three characters are letters, chosen from 26 available options.<br>
</li>
<li>The last three characters are digits, chosen from 10 available options (0–9).</li>
</ul>
<p>Using the <strong>multiplication principle</strong>, the total number of possible registration numbers is:</p>
<p><span class="math display">\[ 26 \times 26 \times 26 \times 10 \times 10 \times 10 = 26^3 \times 10^3 = 17,576,000 \]</span></p>
<p>This means that Sweden can issue up to 17.58 million unique vehicle registration numbers under this system. The formaula is generally written as <span class="math inline">\(N_1^{n_1} \times N_2^{n_2}\)</span> where:</p>
<ul>
<li>
<span class="math inline">\(N_1 = 26\)</span> (number of available letters), <span class="math inline">\(n_1 = 3\)</span> (three letters chosen).<br>
</li>
<li>
<span class="math inline">\(N_2 = 10\)</span> (number of available digits), <span class="math inline">\(n_2 = 3\)</span> (three digits chosen).</li>
</ul></section></section><section id="drawing-with-replacemen-ignoring-order" class="level3" data-number="9.5.2"><h3 data-number="9.5.2" class="anchored" data-anchor-id="drawing-with-replacemen-ignoring-order">
<span class="header-section-number">9.5.2</span> Drawing with Replacemen, Ignoring Order</h3>
<section id="example-9.5-selecting-ice-cream-flavors" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.5-selecting-ice-cream-flavors">Example 9.5: Selecting Ice Cream Flavors 🍦</h4>
<p>Imagine an ice cream shop that offers six different flavors. A customer selects three scoops of ice cream, where:</p>
<ul>
<li>The same flavor can be chosen multiple times (replacement).<br>
</li>
<li>The order of the scoops does not matter— choosing <em>(vanilla, chocolate, vanilla)</em> is the same as <em>(chocolate, vanilla, vanilla)</em>.</li>
</ul>
<p>Since order is ignored, but repetition is allowed, we calculate the number of possible selections using <strong>combinations with replacement</strong>, given by the formula: <span class="math display">\[\binom{N + n - 1}{n} = \frac{(N + n - 1)!}{n!(N - 1)!} \]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(N = 6\)</span> (number of available flavors).<br>
</li>
<li>
<span class="math inline">\(n = 3\)</span> (number of scoops selected).</li>
</ul>
<p>Applying the formula:</p>
<p><span class="math display">\[ \binom{6+3-1}{3} = \binom{8}{3} = \frac{8!}{3!(5!)} = \frac{8 \times 7 \times 6}{3 \times 2 \times 1} = 56 \]</span></p>
<p>Thus, there are 56 different ways to choose three scoops of ice cream when order does not matter, but flavors can be repeated.</p>
</section></section><section id="drawing-without-replacement-order-matters" class="level3" data-number="9.5.3"><h3 data-number="9.5.3" class="anchored" data-anchor-id="drawing-without-replacement-order-matters">
<span class="header-section-number">9.5.3</span> Drawing without Replacement, Order Matters</h3>
<section id="example-9.6-finalist-selection-in-esc" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.6-finalist-selection-in-esc">Example 9.6: Finalist Selection in ESC 🎤🎶</h4>
<p>In the semi-final rounds of the Eurovision Song Contest, five countries have reached the last stage. The final ranking must be determined, where each country is assigned a unique position from 1st place to 5th place.</p>
<p>Since the <strong>order of ranking is important</strong>, we need to determine how many different ways the top five positions can be arranged. This follows the <strong>permutation rule</strong>, as once a country’s submission is assigned a position, it cannot be placed elsewhere. The total number of possible rankings is calculated as: <span class="math display">\[5 \times 4 \times 3 \times 2 \times 1 = 5! = 120 \]</span><br>
Thus, there are 120 possible ways to assign the final rankings to the five finalists.</p>
<p>This follows the principle of <strong>permutations without replacement</strong>, meaning that each finalist is placed in a unique ranking, and no two countries can hold the same position.</p>
</section></section><section id="drawing-without-replacement-ignoring-order" class="level3" data-number="9.5.4"><h3 data-number="9.5.4" class="anchored" data-anchor-id="drawing-without-replacement-ignoring-order">
<span class="header-section-number">9.5.4</span> Drawing without Replacement, Ignoring Order</h3>
<section id="example-9.7-poker-hands" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-9.7-poker-hands">Example 9.7: Poker Hands 🎴</h4>
<p>In a standard game of five-card poker, a player is dealt five random cards from a standard deck of 52 playing cards. Since:</p>
<ul>
<li><p>The <strong>order of the cards does not matter</strong> (a hand with A♠ K♠ Q♠ J♠ 10♠ is the same regardless of the order drawn).</p></li>
<li><p>Cards are drawn without replacement (once a card is drawn, it cannot be selected again), we calculate the total number of different poker hands using <strong>combinations without replacement</strong>: <span class="math display">\[\binom{52}{5} = \frac{52!}{(52-5)!5!} = \frac{52 \times 51 \times 50 \times 49 \times 48}{5!} = 2 598 960 \]</span><br>
Thus, there are 2 598 960 unique five-card poker hands in a standard deck.</p></li>
</ul>
<p>What is the probability of getting a flush on the first draw?</p>
<p>A flush in poker means that all five cards in the hand belong to the same suit (♠, ♥, ♦, or ♣). We define event <span class="math inline">\(A\)</span> as the event of being dealt a flush directly, meaning that all five cards in the hand belong to the same suit (♠, ♥, ♦, or ♣).</p>
<p>To compute the probability <span class="math inline">\(A\)</span>, consider that:</p>
<ul>
<li><p>If we focus on only hearts, there are 13 hearts in the deck, and we need to choose 5 of them: <span class="math display">\[\binom{13}{5} = \frac{13!}{(13-5)!5!} = 1287 \]</span></p></li>
<li><p>The same calculation applies for the other three suits (spades, diamonds, and clubs), so the total number of flush hands is: <span class="math display">\[4 \times 1287 = 5148 \]</span></p></li>
</ul>
<p>Since all poker hands are equally likely, the probability of being dealt a flush is: <span class="math display">\[P(A) = \frac{5148}{2598960} \approx 0.00198\]</span><br>
This means that the probability of being dealt a flush on the first draw is approximately 0.198%.</p>
</section></section></section><section id="exercises" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li>A <strong>full house</strong> in poker consists of three cards of one rank and two cards of another (e.g., Q♠ Q♥ Q♦ 7♣ 7♦). What is the probability of getting a full house on the first draw?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since the order <strong>does not matter</strong>, and cards are drawn <strong>without replacement</strong>, we use <strong>combinations</strong> to determine the number of possible full house hands.</p>
<p>Selecting one of 13 ranks for the three-of-a-kind: <span class="math inline">\(\binom{13}{1} = 13\)</span>. Choosing three suits out of four for that rank: <span class="math inline">\(\binom{4}{3} = 4\)</span>.</p>
<p>Total ways to select the three-of-a-kind: <span class="math display">\[13 \times 4 = 52 \]</span></p>
<p>Selecting one of 12 remaining ranks for the pair: $ = 12 $. Choosing two suits out of four for that rank: <span class="math inline">\(\binom{4}{2} = 6\)</span>. Total ways to select the pair: <span class="math display">\[12 \times 6 = 72 \]</span></p>
<p>Multiplying both parts together we get: <span class="math display">\[52 \times 72 = 3 744 \]</span><br>
Thus, there are 3 744 unique full house hands in a standard deck.</p>
<p>Since we already know that there are 2 598 960 total poker hands, the probability of being dealt a full house is (defined as event <span class="math inline">\(A\)</span>):</p>
<p><span class="math display">\[P(A) = \frac{3744}{2598960} \approx 0.00144\]</span></p>
<p>This means the probability of being dealt a full house on the first draw is 0.144%.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Consider rolling two fair six-sided dice. What is the probability of rolling doubles (both dice show the same number)?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>From earlier we know that the dice rolling follows a uniform probability model with <span class="math inline">\(6 \times 6 = 36\)</span> total possible outcomes.<br>
The event ‘Doubles’ occur when both dice show the same number:<br><em>(1,1), (2,2), (3,3), (4,4), (5,5), (6,6)</em>, implying we have 6 outcomes of interest and the probaiblity of this event is given by <span class="math display">\[P(\text{doubles}) = \frac{6}{36} = \frac{1}{6} \approx 0.167 \text{ (16.7\%)} \]</span></p>
</div>
</div>
</div>
<ol start="3" type="1">
<li>A teacher randomly arranges 6 students in a line for a class photo. Each student is assigned a unique position.</li>
</ol>
<ol type="a">
<li>How many different ways can the 6 students be arranged in a line?</li>
<li>What is the probability that a specific student (A) is in the first position?</li>
<li>What is the probability that student A is first and student B is second in the lineup?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>There are <span class="math inline">\(P(6,6) = 6! = 6 \times 5 \times 4 \times 3 \times 2 \times 1 = 720\)</span> different ways to arrange the students in a line (see <a href="../introduction/intro-math.html" class="quarto-xref"><span>Chapter 2</span></a> exercises for more details)</p></li>
<li><p>Since all arrangements are equally likely, student A can be in any of the 6 positions. If we fix A in the first position, the remaining 5 students can be arranged freely: <span class="math display">\[5! = 5 \times 4 \times 3 \times 2 \times 1 = 120\]</span><br>
The probability of A being first is then given by <span class="math display">\[P(A)  = \frac{120}{720} = \frac{1}{6} \approx 0.167 \text{ (16.7\%)}\]</span></p></li>
<li><p>If A is fixed in the first position, there are 5 students remaining. If B is fixed in the second position, there are 4 students left to be arranged: <span class="math display">\[4! = 4 \times 3 \times 2 \times 1 = 24\]</span><br>
The probability of A being first and B being second is then given by: <span class="math display">\[P(B) = \frac{24}{720} = \frac{1}{30} \approx 0.0333 \text{ (3.33\%)}\]</span></p></li>
</ol>
</div>
</div>
</div>
<hr>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../prob-theory/prob-concepts.html" class="pagination-link" aria-label="Probability Concepts">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Concepts</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../rv-probdists.html" class="pagination-link" aria-label="Random Variables and Probability Distributions">
        <span class="nav-page-text">Random Variables and Probability Distributions</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Foundational Statistics by Termeh Shafie.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>