project:
  type: book
  output-dir: docs

book:
  title: "Foundational Statistics"
  author: "Termeh Shafie"
  date: "April 4,2025"
  page-footer:
    left: |
      Foundational Statistics by Termeh Shafie.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
    background: light
  cover-image: cover.png
  favicon: cover.png
  site-url: https://termehs.github.io/found-stats/
  repo-url: https://github.com/termehs/found-stats
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
      - introduction/what-is-stats.qmd
      - introduction/intro-math.qmd
      - introduction/intro-surveys.qmd
      - introduction/variable-class.qmd
    - part: "Descriptive Statistics"
      chapters: 
      - descriptive-stats/describe-data.qmd
      - descriptive-stats/central-measures.qmd
      - descriptive-stats/dispersion-measures.qmd
    - part: "Probability Theory"
      chapters:
      - prob-theory/prob-concepts.qmd
      - prob-theory/what-is-prob.qmd
      - prob-theory/count-rules.qmd
      - prob-theory/prob-rules.qmd
    - part: "Random Variables and Probability Distributions"
      chapters:
      - rvs-probdists/random-variables.qmd
      - rvs-probdists/discrete-dists.qmd
      - rvs-probdists/cont-dists.qmd
      - rvs-probdists/jointly-dist.qmd
    - part: "Sampling and Sampling Distributions"
      chapters:
      - sampling-dists/sampling.qmd
      - sampling-dists/sampling-dist-mean.qmd
      - sampling-dists/sampling-dist-prop.qmd
      - sampling-dists/clt.qmd
    - part: "Inferential Statistics"
      chapters:
      - inferential/intro-inference.qmd
      - inferential/estimation.qmd
    - part: chi2.qmd
    - part: regression.qmd
    - part: references.qmd
  appendices:
  - appendix/normal-table.qmd
  - appendix/t-table.qmd
bibliography: references.bib

number-sections: true 

format:
  html:
    execute:
    echo: false
    warning: false
    message: false
    mermaid:
      theme: default
    theme: cosmo
    number-depth: 3
    code-link: true
    author-meta: "Termeh Shafie"
crossref:
  appendix-delim: ":"
editor: visual

