<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Termeh Shafie">
<title>22&nbsp; Hypothesis Testing – Foundational Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chi2/chi2.html" rel="next">
<link href="../inferential/estimation.html" rel="prev">
<link href="../cover.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6bb5ad484749947dbf006bb4d74c4af5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/intro-inference.html">Inferential Statistics</a></li><li class="breadcrumb-item"><a href="../inferential/hyp-test.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundational Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/termehs/found-stats" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/what-is-stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Unavoidable Math</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-surveys.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Surveys: Key Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/variable-class.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variable Classification</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/describe-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing a Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/central-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of Central Tendency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/dispersion-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Measures of Dispersion</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/what-is-prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/count-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Counting Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Random Variables and Probability Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/discrete-dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/cont-dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/jointly-dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Jointly Distributed Random Variables</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Sampling and Sampling Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling-dist-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling Distributions for a Sample Mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling-dist-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Sampling Distributions for a Sample Proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/intro-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">From Probability to Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/hyp-test.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Chi Square Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Chi Square Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Goodness-of-Fit Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2-ind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing for Independence</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The Regression Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-inf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regression Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Categorical Variables in Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Residual Analysis and Model Diagnostics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">References</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/normal-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Standard Normal Distribution Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/t-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span> Distribution Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/chi2-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(\chi^2\)</span> Distribution Table</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#what-is-hypothesis-testing" id="toc-what-is-hypothesis-testing" class="nav-link active" data-scroll-target="#what-is-hypothesis-testing"><span class="header-section-number">22.1</span> What Is Hypothesis Testing?</a></li>
  <li>
<a href="#classical-hypothesis-testing" id="toc-classical-hypothesis-testing" class="nav-link" data-scroll-target="#classical-hypothesis-testing"><span class="header-section-number">22.2</span> Classical Hypothesis Testing</a>
  <ul class="collapse">
<li><a href="#step-1.-hypotheses" id="toc-step-1.-hypotheses" class="nav-link" data-scroll-target="#step-1.-hypotheses">Step 1. Hypotheses</a></li>
  <li><a href="#step-2.-significance-level" id="toc-step-2.-significance-level" class="nav-link" data-scroll-target="#step-2.-significance-level">Step 2. Significance Level</a></li>
  <li><a href="#step-3.-test-statistic" id="toc-step-3.-test-statistic" class="nav-link" data-scroll-target="#step-3.-test-statistic">Step 3. Test Statistic</a></li>
  <li><a href="#step-4-decision-rule" id="toc-step-4-decision-rule" class="nav-link" data-scroll-target="#step-4-decision-rule">Step 4: Decision Rule</a></li>
  <li><a href="#step-5-observation" id="toc-step-5-observation" class="nav-link" data-scroll-target="#step-5-observation">Step 5: Observation</a></li>
  <li><a href="#step-6-conclusion" id="toc-step-6-conclusion" class="nav-link" data-scroll-target="#step-6-conclusion">Step 6: Conclusion</a></li>
  </ul>
</li>
  <li>
<a href="#hypothesis-testing-for-a-population-mean" id="toc-hypothesis-testing-for-a-population-mean" class="nav-link" data-scroll-target="#hypothesis-testing-for-a-population-mean"><span class="header-section-number">22.3</span> Hypothesis Testing for a Population Mean</a>
  <ul class="collapse">
<li><a href="#two-sided-hypothesis-tests" id="toc-two-sided-hypothesis-tests" class="nav-link" data-scroll-target="#two-sided-hypothesis-tests"><span class="header-section-number">22.3.1</span> Two-Sided Hypothesis Tests</a></li>
  <li><a href="#one-sided-hypothesis-tests" id="toc-one-sided-hypothesis-tests" class="nav-link" data-scroll-target="#one-sided-hypothesis-tests"><span class="header-section-number">22.3.2</span> One-Sided Hypothesis Tests</a></li>
  <li><a href="#hypothesis-testing-with-unknown-variance" id="toc-hypothesis-testing-with-unknown-variance" class="nav-link" data-scroll-target="#hypothesis-testing-with-unknown-variance"><span class="header-section-number">22.3.3</span> Hypothesis Testing with Unknown Variance</a></li>
  </ul>
</li>
  <li><a href="#hypothesis-testing-for-a-population-proportion" id="toc-hypothesis-testing-for-a-population-proportion" class="nav-link" data-scroll-target="#hypothesis-testing-for-a-population-proportion"><span class="header-section-number">22.4</span> Hypothesis Testing for a Population Proportion</a></li>
  <li><a href="#hypothesis-testing-with-p-values" id="toc-hypothesis-testing-with-p-values" class="nav-link" data-scroll-target="#hypothesis-testing-with-p-values"><span class="header-section-number">22.5</span> Hypothesis Testing with <span class="math inline">\(p\)</span>-Values</a></li>
  <li><a href="#hypothesis-testing-and-confidence-intervals" id="toc-hypothesis-testing-and-confidence-intervals" class="nav-link" data-scroll-target="#hypothesis-testing-and-confidence-intervals"><span class="header-section-number">22.6</span> Hypothesis Testing and Confidence Intervals</a></li>
  <li>
<a href="#hypothesis-testing-for-the-difference-between-two-population-means" id="toc-hypothesis-testing-for-the-difference-between-two-population-means" class="nav-link" data-scroll-target="#hypothesis-testing-for-the-difference-between-two-population-means"><span class="header-section-number">22.7</span> Hypothesis Testing for the Difference Between Two Population Means</a>
  <ul class="collapse">
<li><a href="#case-1-large-samples" id="toc-case-1-large-samples" class="nav-link" data-scroll-target="#case-1-large-samples"><span class="header-section-number">22.7.1</span> Case 1: Large Samples</a></li>
  <li><a href="#case-2-small-samples" id="toc-case-2-small-samples" class="nav-link" data-scroll-target="#case-2-small-samples"><span class="header-section-number">22.7.2</span> Case 2: Small Samples</a></li>
  </ul>
</li>
  <li><a href="#hypothesis-testing-for-the-difference-between-two-proportions" id="toc-hypothesis-testing-for-the-difference-between-two-proportions" class="nav-link" data-scroll-target="#hypothesis-testing-for-the-difference-between-two-proportions"><span class="header-section-number">22.8</span> Hypothesis Testing for the Difference Between Two Proportions</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/termehs/found-stats/edit/main/inferential/hyp-test.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/termehs/found-stats/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../inferential/intro-inference.html">Inferential Statistics</a></li><li class="breadcrumb-item"><a href="../inferential/hyp-test.html"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-hyptest" class="quarto-section-identifier"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In the previous chapter, we used <strong>confidence intervals</strong> to estimate an unknown population parameter such as the mean (<span class="math inline">\(\mu\)</span>) or proportion (<span class="math inline">\(p\)</span>), based on a random sample. Confidence intervals provide a range of plausible values for that parameter.</p>
<p>While confidence intervals focus on estimation, <strong>hypothesis testing</strong> addresses decision-making: it allows us to test specific claims about a population parameter using sample data. In fact, these two methods are closely related; we can often reach the same conclusions using either approach. We return to this in more detail later in this chapter.</p>
<section id="what-is-hypothesis-testing" class="level2" data-number="22.1"><h2 data-number="22.1" class="anchored" data-anchor-id="what-is-hypothesis-testing">
<span class="header-section-number">22.1</span> What Is Hypothesis Testing?</h2>
<p>Hypothesis testing is a formal method used to evaluate <strong>two competing statements</strong> (called hypotheses) about a population parameter:</p>
<ul>
<li>
<strong>Null hypothesis</strong> (<span class="math inline">\(H_0\)</span>): The default or status quo assumption.</li>
<li>
<strong>Alternative hypothesis</strong> (<span class="math inline">\(H_1\)</span> or <span class="math inline">\(H_a\)</span>): A competing claim that we seek evidence for.</li>
</ul>
<p>We use data from a sample to decide whether there is sufficient evidence to reject the null hypothesis in favor of the alternative. The null hypothesis (<span class="math inline">\(H_0\)</span>) is assumed to be true unless the evidence from the sample strongly contradicts it. It plays the role of a “presumption of innocence.” The alternative hypothesis (<span class="math inline">\(H_1\)</span>) is what we hope to support, but only if we have enough evidence to doubt <span class="math inline">\(H_0\)</span>.</p>
<p>We never prove the alternative hypothesis directly; we can only reject <span class="math inline">\(H_0\)</span> if the evidence is strong enough, just like a jury does not prove guilt, but rather rejects the assumption of innocence when the evidence demands it. Rejecting <span class="math inline">\(H_0\)</span> only indicates that the data are inconsistent with <span class="math inline">\(H_0\)</span> under the assumed conditions.</p>
<section id="example-22.1-bottled-water-production" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.1-bottled-water-production">Example 22.1: Bottled Water Production</h4>
<p>A company bottles 500 ml of spring water per bottle. To ensure customer trust, they need to verify that the filling process remains accurate. Let</p>
<p><span class="math display">\[
\mu = \text{true average amount of water per bottle}
\]</span></p>
<p>We want to test whether the bottling machine is still calibrated correctly:</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 500\)</span> (machine is accurate)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\mu \neq 500\)</span> (machine is underfilling or overfilling)</p>
<p>That is, the alternative hypothesis says: <em>“The machine does not have the correct precision.”</em></p>
</section><section id="example-22.2-political-party-support" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.2-political-party-support">Example 22.2: Political Party Support</h4>
<p>In a political opinion poll, 14% of the selected individuals say they support Party A. We know that in the most recent election, Party A received 12% of the votes. Has the proportion of A-supporters in the population increased since the election?</p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P = 0.12\)</span> (The proportion is unchanged)</p>
<p><span class="math inline">\(H_1\)</span>: <span class="math inline">\(P &gt; 0.12\)</span> (The proportion has increased)</p>
<p><em>Should we reject <span class="math inline">\(H_0\)</span> or not?</em></p>
<ul>
<li>If we consider the high sample value to be explainable by chance (assuming <span class="math inline">\(H_0\)</span> is true), we stick with <span class="math inline">\(H_0\)</span>.</li>
<li>If we consider the sample proportion to be too high to be reasonably explained by chance, we reject <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>We can never be 100% certain that we are making the correct decision. Statistical hypothesis testing involves using specific decision rules to determine when we should reject <span class="math inline">\(H_0\)</span> (and when we should retain <span class="math inline">\(H_0\)</span>). These decision rules are designed so that we have a certain level of control over the risk of making an incorrect decision.</p>
<p>To understand the reasoning behind hypothesis testing, it can be helpful to draw an analogy from the legal system. Imagine a courtroom trial where the task is to determine whether the defendant is guilty or not. A key question in this context is: on whom does the burden of proof lie?</p>
<p>Just as in most legal systems, where a person is presumed innocent until proven guilty, hypothesis testing begins with a similar assumption. The <strong>null hypothesis</strong>, denoted <span class="math inline">\(H_0\)</span>, plays the role of “innocence”: it is the claim we initially assume to be true. The <strong>alternative hypothesis</strong>, denoted <span class="math inline">\(H_1\)</span>, corresponds to the prosecution’s claim: it challenges the status quo and must be supported by strong evidence.</p>
<p>There is an asymmetry in how we treat the null hypothesis (<span class="math inline">\(H_0\)</span>) and the alternative hypothesis (<span class="math inline">\(H_1\)</span>) in statistical hypothesis testing. We typically choose <span class="math inline">\(H_0\)</span> to be the hypothesis that we hold on to as long as possible. It is the default assumption, often representing “no change,” “no effect,” or “no difference.” On the other hand, <span class="math inline">\(H_1\)</span> is usually the more bold and interesting hypothesis from an applied perspective.</p>
<p>We require particularly strong evidence from the observed data to reject <span class="math inline">\(H_0\)</span>. The burden of proof lies with the party advocating for <span class="math inline">\(H_1\)</span>. Before diving into how to best use information from the sample, we ask ourselves: how confident must we be that the accused is guilty before reaching a guilty verdict? Similarly, how confident must we be that the null hypothesis is incorrect before deciding to believe in the alternative hypothesis?</p>
<p>If we reach that level of confidence, we say that we reject the null hypothesis (or accept the alternative hypothesis). The degree of confidence required depends on the context, but typically, we want to be quite certain that the assumption in the null hypothesis is incorrect. This is because the decision to reject the null hypothesis, and instead believe in the alternative, often comes with serious consequences.</p>
</section></section><section id="classical-hypothesis-testing" class="level2" data-number="22.2"><h2 data-number="22.2" class="anchored" data-anchor-id="classical-hypothesis-testing">
<span class="header-section-number">22.2</span> Classical Hypothesis Testing</h2>
<p>The classical approach to hypothesis testing involves the following six main steps:</p>
<section id="step-1.-hypotheses" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="step-1.-hypotheses">Step 1. Hypotheses</h3>
<p>Begin by formulating the null hypothesis (<span class="math inline">\(H_0\)</span>) and the alternative hypothesis (<span class="math inline">\(H_1\)</span>).</p>
<p>Examples of hypotheses about population means:</p>
<ul>
<li><p><span class="math inline">\(H_0: \mu = \mu_0\)</span>; <span class="math inline">\(H_1: \mu \ne \mu_0\)</span><br><em>(Simple null hypothesis; two-sided alternative)</em></p></li>
<li><p><span class="math inline">\(H_0: \mu \le \mu_0\)</span>; <span class="math inline">\(H_1: \mu &gt; \mu_0\)</span><br><em>(Composite null hypothesis; one-sided alternative)</em></p></li>
</ul>
<p>Examples of hypotheses about population proportions:</p>
<ul>
<li><p><span class="math inline">\(H_0: p = p_0\)</span>; <span class="math inline">\(H_1: p \ne p_0\)</span><br><em>(Simple null hypothesis; two-sided alternative)</em></p></li>
<li><p><span class="math inline">\(H_0: p = p_0\)</span>; <span class="math inline">\(H_1: p &gt; p_0\)</span><br><em>(Simple null hypothesis; one-sided alternative)</em></p></li>
</ul></section><section id="step-2.-significance-level" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="step-2.-significance-level">Step 2. Significance Level</h3>
<p>Choose a significance level <span class="math inline">\(\alpha\)</span>, which represents the probability (or risk) of rejecting the null hypothesis <span class="math inline">\(H_0\)</span> when it is actually true.</p>
<p>A common choice is <span class="math inline">\(\alpha = 0.05\)</span>, which implies that the hypothesis test is conducted at the 5% level. This means that there is a 5% chance of making a <strong>Type I error</strong>, that is rejecting a true null hypothesis. In other words, if the null hypothesis is true, then on average, 1 in every 20 tests will incorrectly reject it. If we want to be more cautious about rejecting a correct null hypothesis, we use a smaller <span class="math inline">\(\alpha\)</span>, such as <span class="math inline">\(\alpha = 0.01\)</span>.</p>
</section><section id="step-3.-test-statistic" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="step-3.-test-statistic">Step 3. Test Statistic</h3>
<p>Specify which test statistic will be used. A <strong>test statistic</strong> is a quantity calculated from the sample data and its value forms the basis of our decision (see step 5).</p>
<p>The choice of test statistic depends on:</p>
<ul>
<li>Whether the sample is large or not.</li>
<li>Whether the population is normally distributed or not.</li>
<li>Whether the population variance is known or not.</li>
</ul>
<p>We’ll return to these different cases in more detail below.</p>
</section><section id="step-4-decision-rule" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="step-4-decision-rule">Step 4: Decision Rule</h3>
<p>Specify the <strong>rejection region</strong> (the critical region), such that <span class="math inline">\(H_0\)</span> is rejected if the test statistic falls within this region. In summary, the form of the <strong>critical region</strong> is determined by:</p>
<ol type="1">
<li>
<p>The form of the alternative hypothesis:</p>
<ul>
<li>
<span class="math inline">\(H_1: \mu \neq \mu_0\)</span> → two-tailed test → rejection region in both tails.</li>
<li>
<span class="math inline">\(H_1: \mu &gt; \mu_0\)</span> → one-tailed test → rejection region in the <strong>right</strong> tail.</li>
<li>
<span class="math inline">\(H_1: \mu &lt; \mu_0\)</span> → one-tailed test → rejection region in the <strong>left</strong> tail.</li>
</ul>
</li>
<li><p>The significance level <span class="math inline">\(\alpha\)</span>.</p></li>
</ol>
<p>Alternative hypotheses of the forms <span class="math inline">\(&gt;\)</span> and <span class="math inline">\(&lt;\)</span> are called <strong>one-sided</strong>, while those using <span class="math inline">\(\neq\)</span> are called <strong>two-sided</strong>. <a href="#fig-hyptest" class="quarto-xref">Figure&nbsp;<span>22.1</span></a> illustrates the decision framework of hypothesis testing three panels:</p>
<ol type="1">
<li><p>Left: Depicts a two-tailed test, where both tails of the distribution represent critical regions. The dashed lines mark the critical values at <span class="math inline">\(z = \pm z_{\alpha/2}\)</span>. Each tail has an area of <span class="math inline">\(\alpha/2\)</span>, and the null hypothesis is rejected if the test statistic lies in either shaded tail. The central blue segment indicates the non-rejection region.</p></li>
<li><p>Right: Represents a one-sided test with the alternative hypothesis <span class="math inline">\(H_1: \mu &gt; \mu_0\)</span>. The right tail is shaded red, indicating the critical region with area <span class="math inline">\(\alpha\)</span>. The test statistic must fall in this region to reject <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>Middle: Shows the critical region in the left tail of the distribution, representing a one-sided test with the alternative hypothesis <span class="math inline">\(H_1: \mu &lt; \mu_0\)</span>. The red-shaded area corresponds to the significance level <span class="math inline">\(\alpha\)</span>, and any test statistic falling in this region leads to rejection of the null hypothesis <span class="math inline">\(H_0\)</span>.</p></li>
</ol>
<div id="fig-hyptest" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-hyptest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hyptest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.1: The decision framework of hypothesis testing for two-tailed and one-tailed tests.
</figcaption></figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Errors and Decision Framework
</div>
</div>
<div class="callout-body-container callout-body">
<p>When making a decision, one either makes a correct choice or one of two types of errors. Just as there is a risk that an innocent person may be wrongly convicted, there is also a risk that a guilty person may go free.</p>
<p>Using probability theory, we can to some extent determine the risk of making incorrect decisions.</p>
<ul>
<li><p>A <strong>Type I error</strong> occurs when we incorrectly reject the null hypothesis (<span class="math inline">\(H_0\)</span>) even though it is true. The risk of making a Type I error is called the <strong>significance level</strong> of the test and is denoted by the Greek letter <span class="math inline">\(\alpha\)</span>.</p></li>
<li><p>A <strong>Type II error</strong> occurs when we incorrectly fail to reject the null hypothesis, even though it is false. The risk of this error is denoted by the Greek letter <span class="math inline">\(\beta\)</span>.</p></li>
</ul>
<p>A diagram describing the possible outcomes of hypothesis testing is shown below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead><tr class="header">
<th><strong>Reality</strong></th>
<th>
<span class="math inline">\(H_0\)</span> is true</th>
<th>
<span class="math inline">\(H_0\)</span> is false</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Decision</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Do not reject <span class="math inline">\(H_0\)</span>
</td>
<td>Correct decision</td>
<td>Type II error (incorrect decision)</td>
</tr>
<tr class="odd">
<td>Reject <span class="math inline">\(H_0\)</span>
</td>
<td>Type I error (incorrect decision)</td>
<td>Correct decision</td>
</tr>
</tbody>
</table>
<p>In classical hypothesis testing, we primarily control the probability of making a Type I error. This is done by setting the significance level <span class="math inline">\(\alpha\)</span> to a predefined low value (commonly <span class="math inline">\(\alpha = 0.01\)</span>, <span class="math inline">\(0.05\)</span>, or <span class="math inline">\(0.10\)</span>).</p>
<p><span class="math display">\[
\alpha = \text{Significance level of the test} = P(\text{Reject } H_0 \mid H_0 \text{ is true})
\]</span></p>
<p>After setting the acceptable level for Type I errors, we then aim to reduce the probability of Type II errors (<span class="math inline">\(\beta\)</span>) by choosing a sufficiently large sample size.</p>
</div>
</div>
<p>Once the hypotheses have been formulated, the appropriate test statistic selected and decision rules specified, we proceed with the final steps of the classical hypothesis testing procedure:</p>
</section><section id="step-5-observation" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="step-5-observation">Step 5: Observation</h3>
<p>We calculate the value of the <strong>test statistic</strong> using the data obtained from the sample. This computation allows us to compare the observed value with the theoretical distribution <em>under the null hypothesis</em>. This value is what we refere to as our <strong>observed value</strong>.</p>
</section><section id="step-6-conclusion" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="step-6-conclusion">Step 6: Conclusion</h3>
<p>Based on the value of the test statistic (our observed value), we make our decision based on the decision rule:</p>
<ul>
<li><p>If the value falls <strong>outside the critical boundaries</strong> (i.e.&nbsp;outside the non-rejection region), we <strong>reject the null hypothesis</strong> <span class="math inline">\(H_0\)</span>. This means that we have obtained a result that is statistically significant at the chosen significance level <span class="math inline">\(\alpha\)</span>.</p></li>
<li><p>If the value falls <strong>within the non-rejection region</strong>, we <strong>do not reject</strong> <span class="math inline">\(H_0\)</span>. In this case, the result is said to be <strong>not statistically significant</strong>.</p></li>
</ul>
<p>In essence, these final steps guide us in deciding whether the sample data provides enough evidence to conclude that the null hypothesis is unlikely to be true, given the selected confidence level.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A non-significant result does <strong>not</strong> mean that we can conclude the null hypothesis (<span class="math inline">\(H_0\)</span>) is true. It simply indicates that the alternative hypothesis (<span class="math inline">\(H_1\)</span>) does not present strong enough evidence against <span class="math inline">\(H_0\)</span> in this particular case.</p>
<p>There may be many other potential null hypotheses that would also not be rejected. Therefore, <strong>failing to reject <span class="math inline">\(H_0\)</span> is not the same as accepting <span class="math inline">\(H_0\)</span> as true</strong>.</p>
<p>In other words, we use the terms ‘<em>reject</em>’ and ‘<em>fail to reject</em>’ to summarize the possible outcomes of a hypothesis test</p>
</div>
</div>
</section></section><section id="hypothesis-testing-for-a-population-mean" class="level2" data-number="22.3"><h2 data-number="22.3" class="anchored" data-anchor-id="hypothesis-testing-for-a-population-mean">
<span class="header-section-number">22.3</span> Hypothesis Testing for a Population Mean</h2>
<p>Just as with confidence intervals, different cases must be considered when conducting hypothesis tests:</p>
<ul>
<li>Is the sample size large or small?</li>
<li>Is the population normally distributed?</li>
<li>Is the population variance known?</li>
</ul>
<section id="two-sided-hypothesis-tests" class="level3" data-number="22.3.1"><h3 data-number="22.3.1" class="anchored" data-anchor-id="two-sided-hypothesis-tests">
<span class="header-section-number">22.3.1</span> Two-Sided Hypothesis Tests</h3>
<p>We begin with an example: suppose we draw a sample of size <span class="math inline">\(n\)</span> from a <strong>normally distributed population</strong> where the mean <span class="math inline">\(\mu\)</span> is unknown but the <strong>variance <span class="math inline">\(\sigma^2\)</span> is known</strong>. We conduct a <strong>two-sided hypothesis test</strong> at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, walking through the six steps of hypothesis testing.</p>
<section id="hypotheses" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="hypotheses">1. Hypotheses</h4>
<p>We want to test whether the population mean equals some hypothesized value <span class="math inline">\(\mu_0\)</span>. The hypotheses are:</p>
<p><span class="math display">\[
H_0: \mu = \mu_0
\]</span> <span class="math display">\[
H_1: \mu \ne \mu_0
\]</span></p>
<p>This is a <strong>two-sided test</strong>, as we are considering deviations in both directions from <span class="math inline">\(\mu_0\)</span>.</p>
</section><section id="significance-level" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="significance-level">2. Significance Level</h4>
<p>We choose a significance level of:</p>
<p><span class="math display">\[
\alpha = 0.05
\]</span></p>
<p>This indicates we are willing to accept a 5% chance of rejecting the null hypothesis if it is actually true.</p>
</section><section id="test-statistic" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="test-statistic">3. Test Statistic</h4>
<p>Since the population is normally distributed and the population standard deviation <span class="math inline">\(\sigma\)</span> is known, we use the <strong>standard normal <span class="math inline">\(Z\)</span> statistic</strong>:</p>
<p><span class="math display">\[
Z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}}
\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the statistic follows the standard normal distribution:</p>
<p><span class="math display">\[
Z \sim N(0, 1)
\]</span></p>
</section><section id="decision-rule" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="decision-rule">4. Decision Rule</h4>
<p>For a two-sided test with <span class="math inline">\(\alpha = 0.05\)</span>, the critical values are:</p>
<p><span class="math display">\[
z_{\alpha/2} = \pm 1.96
\]</span></p>
<p>The decision rule is:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z_{\text{obs}}| &gt; 1.96\)</span>
</li>
<li>Otherwise, do not reject <span class="math inline">\(H_0\)</span>
</li>
</ul>
<p>The critical regions for this test is visualized in <a href="#fig-mean2side" class="quarto-xref">Figure&nbsp;<span>22.2</span></a>, where we see the threshold for rejecting <span class="math inline">\(H_0\)</span> in both directions when testing for a deviation from a hypothesized population mean.</p>
<div id="fig-mean2side" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mean2side-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean2side-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.2: Visual representation of a two-sided hypothesis test at significance level <span class="math inline">\(\alpha  = 0.05\)</span>. The standard normal curve is split into two critical regions (shaded red), each representing <span class="math inline">\(\alpha⁄2 = 0.025\)</span> in the tails, where the null hypothesis is rejected. The non-rejection region (shaded blue) lies between the critical values −1.96 and 1.96. If the test statistic falls within this central interval, we do not reject the null hypothesis.
</figcaption></figure>
</div>
</section><section id="observation" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="observation">5. Observation</h4>
<p>Compute the observed value of the test statistic:</p>
<p><span class="math display">\[
z_{\text{obs}} = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}}
\]</span></p>
</section><section id="conclusion" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="conclusion">6. Conclusion</h4>
<p>Compare <span class="math inline">\(z_{\text{obs}}\)</span> to the critical values:</p>
<ul>
<li>If <span class="math inline">\(|z_{\text{obs}}| &gt; 1.96\)</span>, <strong>reject <span class="math inline">\(H_0\)</span></strong>
</li>
<li>Otherwise, <strong>fail to reject <span class="math inline">\(H_0\)</span></strong>
</li>
</ul>
<p>This tells us whether the sample provides strong enough evidence to conclude that the population mean differs from <span class="math inline">\(\mu_0\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note: Choosing Critical Values for a Hypothesis Test
</div>
</div>
<div class="callout-body-container callout-body">
<p>A reasonable starting point in hypothesis testing is that we should reject the null hypothesis (<span class="math inline">\(H_0\)</span>) if we observe a sample mean <span class="math inline">\(\bar{x}\)</span> that is “far” from the expected value <span class="math inline">\(\mu_0\)</span> under <span class="math inline">\(H_0\)</span>.</p>
<p>In practical terms, <span class="math inline">\(\bar{x}\)</span> being far from <span class="math inline">\(\mu_0\)</span> means that the test statistic <span class="math inline">\(Z\)</span> takes on a value far from 0; either in the positive or negative direction. Therefore, we decide to reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(Z\)</span> falls outside a specified range: specifically, outside the interval <span class="math inline">\([-c, c]\)</span>, where <span class="math inline">\(c\)</span> is a positive constant that we determine based on the desired significance level <span class="math inline">\(\alpha\)</span>.</p>
<p>To define this cutoff <span class="math inline">\(c\)</span>, we choose it so that the total probability of <span class="math inline">\(Z\)</span> falling outside the interval (i.e., the two tails) equals the chosen significance level <span class="math inline">\(\alpha\)</span>. For example, with <span class="math inline">\(\alpha = 0.05\)</span>, we solve:</p>
<p><span class="math display">\[
P(|Z| &gt; c \mid H_0 \text{ true}) = 0.05
\]</span></p>
<p>Since the distribution of <span class="math inline">\(Z\)</span> under the null hypothesis is standard normal <span class="math inline">\(N(0, 1)\)</span>, we find:</p>
<p><span class="math display">\[
P(|Z| &gt; 1.96 \mid H_0 \text{ true}) = 0.05
\]</span></p>
<p>Thus, we set <span class="math inline">\(c = 1.96\)</span> for a two-sided test at the 5% significance level. Our final decision rule becomes:</p>
<blockquote class="blockquote">
<p>Reject <span class="math inline">\(H_0\)</span> if the computed test statistic <span class="math inline">\(Z\)</span> falls outside the interval <span class="math inline">\([-1.96,\ 1.96]\)</span>. Otherwise, we fail to reject <span class="math inline">\(H_0\)</span>.</p>
</blockquote>
</div>
</div>
</section></section><section id="one-sided-hypothesis-tests" class="level3" data-number="22.3.2"><h3 data-number="22.3.2" class="anchored" data-anchor-id="one-sided-hypothesis-tests">
<span class="header-section-number">22.3.2</span> One-Sided Hypothesis Tests</h3>
<p>In some situations, we are not interested in detecting any difference from the null value, but specifically a greater or smaller value. In such cases, we use a one-sided alternative hypothesis. The structure of the test depends on the direction specified in the alternative.</p>
<section id="testing-if-the-mean-is-greater-than-a-specified-value" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="testing-if-the-mean-is-greater-than-a-specified-value">Testing if the mean is greater than a specified value</h4>
<p>We want to test the hypotheses:</p>
<p><span class="math display">\[
H_0: \mu = \mu_0 \quad \text{vs.} \quad H_1: \mu &gt; \mu_0
\]</span></p>
<p>In this case, we are interested in large values of the sample mean <span class="math inline">\(\bar{x}\)</span> as evidence against <span class="math inline">\(H_0\)</span>. The rejection region lies in the right tail of the standard normal distribution.</p>
<p>For a significance level <span class="math inline">\(\alpha = 0.05\)</span>, the critical value is:</p>
<p><span class="math display">\[
z_\alpha = 1.645
\]</span></p>
<p>We reject the null hypothesis if:</p>
<p><span class="math display">\[
z_{\text{obs}} &gt; 1.645
\]</span></p>
<p>This corresponds to the idea that an unusually high observed value of <span class="math inline">\(\bar{x}\)</span> supports the alternative that the true mean is greater than <span class="math inline">\(\mu_0\)</span>.</p>
</section><section id="testing-if-the-mean-is-less-than-a-specified-value" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="testing-if-the-mean-is-less-than-a-specified-value">Testing if the mean is less than a specified value</h4>
<p>Now suppose we want to test:</p>
<p><span class="math display">\[
H_0: \mu = \mu_0 \quad \text{vs.} \quad H_1: \mu &lt; \mu_0
\]</span></p>
<p>Here, we are interested in small values of the sample mean as evidence against <span class="math inline">\(H_0\)</span>. The rejection region lies in the left tail of the standard normal distribution.</p>
<p>For <span class="math inline">\(\alpha = 0.05\)</span>, the critical value becomes:</p>
<p><span class="math display">\[
z_\alpha = -1.645
\]</span></p>
<p>We reject the null hypothesis if:</p>
<p><span class="math display">\[
z_{\text{obs}} &lt; -1.645
\]</span></p>
<p>This reflects the logic that low values of <span class="math inline">\(\bar{x}\)</span> support the alternative that the true mean is less than <span class="math inline">\(\mu_0\)</span>.</p>
<p>The critical regions for these one-sided tests are visualized in <a href="#fig-mean1side" class="quarto-xref">Figure&nbsp;<span>22.3</span></a>, where we see the threshold for rejecting <span class="math inline">\(H_0\)</span> in either directions when testing for a deviation from a hypothesized population mean.</p>
<div id="fig-mean1side" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mean1side-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean1side-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.3: Visual comparison of one-sided hypothesis tests using the standard normal distribution. The left plot shows a right-tailed test, with the rejection region in the upper tail (for testing <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu &gt; \mu_0\)</span>). The right plot illustrates a left-tailed test, where the rejection region lies in the lower tail (for testing <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu &lt; \mu_0\)</span>).
</figcaption></figure>
</div>
</section></section><section id="hypothesis-testing-with-unknown-variance" class="level3" data-number="22.3.3"><h3 data-number="22.3.3" class="anchored" data-anchor-id="hypothesis-testing-with-unknown-variance">
<span class="header-section-number">22.3.3</span> Hypothesis Testing with Unknown Variance</h3>
<p>Up until now, we have assumed that the population is normally distributed and that the population variance <span class="math inline">\(\sigma^2\)</span> is known. But what if the population variance is <strong>unknown</strong> or if the sample size is <strong>small</strong>?</p>
<p>In such cases, we no longer use the standard normal distribution (<span class="math inline">\(Z\)</span>). Instead, we use the <strong>Student’s <span class="math inline">\(t\)</span>-distribution</strong>, which accounts for the additional uncertainty introduced by estimating the population standard deviation from the sample.</p>
<p>The test statistic is then defined as:</p>
<p><span class="math display">\[
t = \frac{\bar{X} - \mu_0}{s / \sqrt{n}}
\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(\bar{X}\)</span> is the sample mean,</li>
<li>
<span class="math inline">\(\mu_0\)</span> is the value of the population mean under the null hypothesis,</li>
<li>
<span class="math inline">\(s\)</span> is the sample standard deviation,</li>
<li>
<span class="math inline">\(n\)</span> is the sample size.</li>
</ul>
<p>Under the null hypothesis <span class="math inline">\(H_0\)</span>, this test statistic follows a <strong><span class="math inline">\(t\)</span>-distribution</strong> with <span class="math inline">\(n - 1\)</span> <strong>degrees of freedom</strong>.</p>
<p>This approach is particularly crucial when the sample size is small (<span class="math inline">\(n &lt; 30\)</span>), and the population variance cannot be assumed to be known. The <span class="math inline">\(t\)</span>-distribution is wider than the normal distribution, which reflects greater uncertainty in small samples. As <span class="math inline">\(n\)</span> increases, the <span class="math inline">\(t\)</span>-distribution approaches the standard normal distribution (see <a href="estimation.html" class="quarto-xref"><span>Chapter 21</span></a>).</p>
<section id="summary-hypothesis-tests-for-a-population-mean" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="summary-hypothesis-tests-for-a-population-mean">Summary: Hypothesis Tests for a Population Mean</h4>
<p>When testing hypotheses about a population mean, the choice of test statistic depends on the sample size, whether the population standard deviation is known, and the shape of the population distribution. These different cases for a test of the population mean are shown in <a href="#tbl-testmean" class="quarto-xref">Table&nbsp;<span>22.1</span></a>.</p>
<div id="tbl-testmean" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-testmean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;22.1: Summary of test statistics and distributions used for hypothesis testing of a population mean (<span class="math inline">\(\mu\)</span>), depending on sample size, knowledge of the population variance, and the assumption of normality. When the population standard deviation is unknown and the sample size is small, the <span class="math inline">\(t\)</span>-distribution is used with <span class="math inline">\(n - 1\)</span> degrees of freedom. Note that these are the distributions assumed given <span class="math inline">\(H_0\)</span> true.
</figcaption><div aria-describedby="tbl-testmean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 14%">
<col style="width: 29%">
</colgroup>
<thead><tr class="header">
<th>Conditions</th>
<th>Test Statistic</th>
<th>Distribution</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<span class="math inline">\(n \geq 30\)</span>, <span class="math inline">\(\sigma^2\)</span> known</td>
<td><span class="math inline">\(Z = \dfrac{\bar{X} - \mu_0}{\sigma / \sqrt{n}}\)</span></td>
<td>Standard Normal (<span class="math inline">\(Z\)</span>)</td>
</tr>
<tr class="even">
<td>
<span class="math inline">\(n \geq 30\)</span>, <span class="math inline">\(\sigma^2\)</span> unknown</td>
<td><span class="math inline">\(Z = \dfrac{\bar{X} - \mu_0}{s / \sqrt{n}}\)</span></td>
<td>Standard Normal (<span class="math inline">\(Z\)</span>)</td>
</tr>
<tr class="odd">
<td>
<span class="math inline">\(n &lt; 30\)</span>, <span class="math inline">\(\sigma^2\)</span> known, normal population</td>
<td><span class="math inline">\(Z = \dfrac{\bar{X} - \mu_0}{\sigma / \sqrt{n}}\)</span></td>
<td>Standard Normal (<span class="math inline">\(Z\)</span>)</td>
</tr>
<tr class="even">
<td>
<span class="math inline">\(n &lt; 30\)</span>, <span class="math inline">\(\sigma^2\)</span> unknown, normal population</td>
<td><span class="math inline">\(t = \dfrac{\bar{X} - \mu_0}{s / \sqrt{n}}\)</span></td>
<td>
<span class="math inline">\(t\)</span> with <span class="math inline">\(n-1\)</span> df</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section><section id="example-22.1-hypothesis-testing-for-a-mean" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.1-hypothesis-testing-for-a-mean">Example 22.1: Hypothesis Testing for a Mean</h4>
<p>We are given a sample of <span class="math inline">\(n = 16\)</span> observations from a normally distributed population with a known standard deviation <span class="math inline">\(\sigma = 16\)</span>. The sample mean is <span class="math inline">\(\bar{x} = 743\)</span>. We want to test at the 5% significance level whether the population mean differs from 750, i.e., whether <span class="math inline">\(\mu \ne 750\)</span>.</p>
<ul>
<li><p><strong>Step 1: Hypotheses</strong> <span class="math display">\[
H_0: \mu = 750
\]</span> <span class="math display">\[
H_1: \mu \ne 750
\]</span> This is a two-sided test.</p></li>
<li><p><strong>Step 2: Significance Level</strong><br>
We use a significance level of: <span class="math display">\[
\alpha = 0.05
\]</span></p></li>
<li><p><strong>Step 3: Test Statistic</strong><br>
Since <span class="math inline">\(\sigma\)</span> is known and the population is normally distributed, we use the standard normal test statistic (see <a href="#tbl-testmean" class="quarto-xref">Table&nbsp;<span>22.1</span></a>): <span class="math display">\[
Z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} \sim N(0,1)
\]</span></p></li>
<li><p><strong>Step 4: Decision Rule</strong><br>
Because this is a two-tailed test, the critical values are: <span class="math display">\[
z_{\alpha/2} = \pm 1.96
\]</span> We reject <span class="math inline">\(H_0\)</span> if: <span class="math display">\[
|z| &gt; 1.96
\]</span></p></li>
<li><p><strong>Step 5: Observation</strong><br>
We use the sample data to compute our observed value: <span class="math display">\[
Z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} = \frac{743 - 750}{16 / \sqrt{16}} = \frac{-7}{4} = -1.75
\]</span></p></li>
<li><p><strong>Step 6: Conclusion</strong><br>
Since the observed test statistic is <span class="math inline">\(z = -1.75\)</span> and: <span class="math display">\[
|-1.75| &lt; 1.96
\]</span> we <em>fail to reject the null hypothesis</em>. There is not enough evidence at the 5% level to conclude that the population mean differs from 750.</p></li>
</ul>
<p>This test is visualized in <a href="#fig-mean-ex" class="quarto-xref">Figure&nbsp;<span>22.4</span></a>.</p>
<div id="fig-mean-ex" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mean-ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.4: The two-tailed test in Example 22.1 using the <span class="math inline">\(Z\)</span>-distribution.
</figcaption></figure>
</div>
</section><section id="example-22.2-hypothesis-test-for-a-mean" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.2-hypothesis-test-for-a-mean">Example 22.2: Hypothesis Test for a Mean</h4>
<p>We are given a random sample of size <span class="math inline">\(n = 15\)</span> drawn from a normally distributed population with unknown standard deviation. The sample has a mean <span class="math inline">\(\bar{x} = 24.1\)</span> and a sample standard deviation <span class="math inline">\(s = 2\)</span>. We want to test, at the 1% significance level, whether the population mean <span class="math inline">\(\mu\)</span> is less than 25.</p>
<ul>
<li><p><strong>Step 1: Hypotheses</strong><br>
We are conducting a one-sided (left-tailed) test: <span class="math display">\[
H_0: \mu = 25
\]</span> <span class="math display">\[
H_1: \mu &lt; 25
\]</span></p></li>
<li><p><strong>Step 2: Significance Level</strong><br>
We choose a significance level of <span class="math inline">\(\alpha = 0.01\)</span>.</p></li>
<li><p><strong>Step 3: Test Statistic</strong><br>
Since <span class="math inline">\(\sigma\)</span> is unknown and <span class="math inline">\(n\)</span> is small, we use the <span class="math inline">\(t\)</span>-distribution (see <a href="#tbl-testmean" class="quarto-xref">Table&nbsp;<span>22.1</span></a>): <span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}}  \sim t(n-1)
\]</span></p></li>
<li><p><strong>Step 4: Decision Rule</strong><br>
With <span class="math inline">\(n - 1 = 14\)</span> degrees of freedom and <span class="math inline">\(\alpha = 0.01\)</span> (one-tailed), we find the critical value: <span class="math display">\[
t_{14, 0.01} = -2.624
\]</span> We reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{\text{obs}} &lt; -2.624\)</span>.</p></li>
<li><p><strong>Step 5: Observation</strong><br>
We use the sample data to compute our observed value: <span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}} = \frac{24.1 - 25}{2 / \sqrt{15}} \approx -1.743
\]</span></p></li>
<li><p><strong>Step 5: Conclusion</strong> Since <span class="math inline">\(t_{\text{obs}} = -1.743\)</span> is greater than <span class="math inline">\(-2.624\)</span> (in the non-rejection region), we do not reject the null hypothesis. We fail to reject <span class="math inline">\(H_0\)</span>. The sample does <strong>not</strong> provide sufficient evidence at the 1% significance level to conclude that the population mean is less than 25. See <a href="#fig-mean-ex2" class="quarto-xref">Figure&nbsp;<span>22.5</span></a> for an illustration of this one-tailed test.</p></li>
</ul>
<blockquote class="blockquote">
<p><strong>Note:</strong> Because the test statistic does not fall in the rejection region, the observed sample mean can be explained by random sampling variation if the true mean were 25.</p>
</blockquote>
<div id="fig-mean-ex2" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mean-ex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-ex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.5: The one-tailed test in Example 22.2 using the <span class="math inline">\(t\)</span>-distribution.
</figcaption></figure>
</div>
</section></section></section><section id="hypothesis-testing-for-a-population-proportion" class="level2" data-number="22.4"><h2 data-number="22.4" class="anchored" data-anchor-id="hypothesis-testing-for-a-population-proportion">
<span class="header-section-number">22.4</span> Hypothesis Testing for a Population Proportion</h2>
<p>In this section, we test hypotheses about a <strong>population proportion</strong> <span class="math inline">\(p\)</span> based on data from a single sample. The hypotheses can be formulated as:</p>
<ul>
<li>
<span class="math inline">\(H_0: p = p_0\)</span> (null hypothesis)</li>
<li>
<span class="math inline">\(H_1\)</span>: one of the following alternative hypotheses:
<ul>
<li>
<span class="math inline">\(p \neq p_0\)</span> (two-tailed)</li>
<li>
<span class="math inline">\(p &gt; p_0\)</span> (right-tailed)</li>
<li>
<span class="math inline">\(p &lt; p_0\)</span> (left-tailed)</li>
</ul>
</li>
</ul>
<p>Here, <span class="math inline">\(p\)</span> is the unknown population proportion, and <span class="math inline">\(p_0\)</span> is a specified numerical value.</p>
<p>We ask: Is the observed sample proportion <span class="math inline">\(\hat{p}\)</span> far enough from <span class="math inline">\(p_0\)</span> to justify rejecting the null hypothesis <span class="math inline">\(H_0\)</span>? Or is the observed deviation consistent with sampling variation?</p>
<p>If the sample size is sufficiently large, we use the test statistic: <span class="math display">\[
Z = \frac{\hat{p} - p_0}{\sqrt{\frac{p_0(1 - p_0)}{n}}}
\]</span> Under the null hypothesis <span class="math inline">\(H_0\)</span>, this statistic is approximately standard normal: <span class="math display">\[
Z \sim N(0, 1)
\]</span> For a common significance level <span class="math inline">\(\alpha = 0.05\)</span>, the decision rules are as follows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 39%">
<col style="width: 30%">
</colgroup>
<thead><tr class="header">
<th>Alternative Hypothesis</th>
<th>Reject <span class="math inline">\(H_0\)</span> if…</th>
<th>Critical Value (<span class="math inline">\(z_c\)</span>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p \neq p_0\)</span></td>
<td><span class="math inline">\(|z_{obs}| &gt; z_c\)</span></td>
<td><span class="math inline">\(z_c = 1.96\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(p &gt; p_0\)</span></td>
<td><span class="math inline">\(z_{obs} &gt; z_c\)</span></td>
<td><span class="math inline">\(z_c = 1.645\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p &lt; p_0\)</span></td>
<td><span class="math inline">\(z_{obs} &lt; -z_c\)</span></td>
<td><span class="math inline">\(z_c = -1.645\)</span></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>The critical values change with the chosen significance level. For other <span class="math inline">\(\alpha\)</span>, adjust <span class="math inline">\(z_c\)</span> accordingly.</p>
</blockquote>
<section id="example-22.3-hypothesis-test-for-a-population-proportion" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.3-hypothesis-test-for-a-population-proportion">Example 22.3: Hypothesis Test for a Population Proportion</h4>
<p>In a random sample of <span class="math inline">\(n = 1200\)</span> individuals, 625 report a particular opinion. Do the sample data support the claim that <em>more than half</em> of the population shares this opinion? We will test this at a significance level of <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<ul>
<li><p><strong>Step 1: Hypotheses</strong><br>
This is a one-sided test:</p></li>
<li><p>Null hypothesis: <span class="math inline">\(H_0: p = 0.5\)</span></p></li>
<li><p>Alternative hypothesis: <span class="math inline">\(H_1: p &gt; 0.5\)</span></p></li>
<li><p><strong>Step 2: Significance Level</strong> We use <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li>
<p><strong>Step 3: Test Statistic</strong><br>
Because the sample size is large, we use the <strong>normal approximation</strong>. The test statistic is: <span class="math display">\[
Z = \frac{\hat{p} - p_0}{\sqrt{ \frac{p_0(1 - p_0)}{n} }}
\]</span> where:</p>
<ul>
<li><span class="math inline">\(\hat{p} = \frac{625}{1200} = 0.521\)</span></li>
<li><span class="math inline">\(p_0 = 0.5\)</span></li>
<li><span class="math inline">\(n = 1200\)</span></li>
</ul>
</li>
<li><p><strong>Step 4: Decision Rule</strong><br>
For a one-sided test at the 5% level, we reject <span class="math inline">\(H_0\)</span> if: <span class="math display">\[
z_{\text{obs}} &gt; 1.645
\]</span></p></li>
<li><p><strong>Step 5: Observation</strong><br>
Substitute the values into the formula for test statistic: <span class="math display">\[
z_{\text{obs}} = \frac{0.521 - 0.5}{\sqrt{ \frac{0.5(1 - 0.5)}{1200} }} = \frac{0.021}{0.0144} \approx 1.45
\]</span></p></li>
<li><p><strong>Step 6: Conclusion</strong><br>
Since <span class="math inline">\(z_{\text{obs}} = 1.45\)</span> is less than the critical value 1.645, we fail to reject the null hypothesis. This means that the sample does not provide sufficient evidence to support the claim that more than half of the population holds this opinion at the 5% level. The test is visualize in <a href="#fig-prop-ex" class="quarto-xref">Figure&nbsp;<span>22.6</span></a>.</p></li>
</ul>
<div id="fig-prop-ex" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-prop-ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prop-ex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.6: The one-tailed test for population proportion in Example 22.3.
</figcaption></figure>
</div>
</section></section><section id="hypothesis-testing-with-p-values" class="level2" data-number="22.5"><h2 data-number="22.5" class="anchored" data-anchor-id="hypothesis-testing-with-p-values">
<span class="header-section-number">22.5</span> Hypothesis Testing with <span class="math inline">\(p\)</span>-Values</h2>
<p>In hypothesis testing, once the test statistic has been calculated, the next step is to decide whether to reject the null hypothesis. This decision traditionally depends on whether the test statistic falls within the critical region defined by a chosen significance level (<span class="math inline">\(\alpha\)</span>). However, this binary decision does not reveal how unusual or extreme the observed result actually is under the assumption that the null hypothesis is true.</p>
<p>To provide a more nuanced view, we use what is known as the <strong><span class="math inline">\(p\)</span>-value</strong>. The <span class="math inline">\(p\)</span>-value answers the question:</p>
<blockquote class="blockquote">
<p><em>If the null hypothesis were true, what is the probability of obtaining a result at least as extreme as the one observed?</em></p>
</blockquote>
<p>In this sense, the <span class="math inline">\(p\)</span>-value is a measure of how compatible the observed data are with the null hypothesis. A small <span class="math inline">\(p\)</span>-value indicates that such an extreme outcome would be unlikely if the null hypothesis were true, thereby providing evidence against it.</p>
<p>The smaller the <span class="math inline">\(p\)</span>-value, the stronger the evidence against the null hypothesis in favor of the alternative. This value can also be thought of as a kind of post hoc significance threshold:</p>
<blockquote class="blockquote">
<p>The <span class="math inline">\(p\)</span>-value is the lowest significance level at which the null hypothesis would be rejected based on the observed data.</p>
</blockquote>
<p>Instead of comparing the test statistic to a critical value, statistical software typically reports the <span class="math inline">\(p\)</span>-value directly. This allows researchers and readers to interpret the strength of the evidence themselves, depending on the context and the significance level they consider appropriate.</p>
<p>In practical terms, if a researcher has set a significance level of 0.05 before conducting the test, and the calculated <span class="math inline">\(p\)</span>-value is below this threshold, the null hypothesis would be rejected. If the <span class="math inline">\(p\)</span>-value is greater, the null hypothesis is not rejected. The <span class="math inline">\(p\)</span>-value thus becomes a central element in statistical inference, guiding conclusions with more granularity than a simple yes-or-no decision.</p>
<p>Let’s consider an example: suppose we are conducting a hypothesis test at the 5% level using the alternative hypothesis: <span class="math display">\[
H_1: \mu &gt; \mu_0
\]</span> and the sample results yield a <span class="math inline">\(p\)</span>-value of 3%. We perform this test at a significance level of <span class="math inline">\(\alpha = 0.05\)</span>, i.e., a 5% threshold for rejecting the null hypothesis.</p>
<p>The <span class="math inline">\(p\)</span>-value here tells us that the probability (under the assumption that the null hypothesis is true) of obtaining a result at least as extreme as the one observed is 3%. Since this is less than 5%, we reject the null hypothesis.</p>
<p>This decision is based on comparing the <span class="math inline">\(p\)</span>-value to the critical value threshold. The critical region begins at the so-called critical point, the value on the distribution where the area under the curve to the right equals <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>Because the <span class="math inline">\(p\)</span>-value corresponds to an area of only 3% under the curve to the right of our observed test statistic, and 3% is less than 5%, the observed value lies beyond the critical point and thus falls in the rejection region. This interpretation means the result is statistically significant at the 5% level. This is visualized in <a href="#fig-pval" class="quarto-xref">Figure&nbsp;<span>22.7</span></a>.</p>
<div id="fig-pval" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.7: The shaded red region represents the critical region corresponding to a significance level of <span class="math inline">\(\alpha\)</span> and critical value of z[c]. The blue point indicates the observed test statistic z[obs]. The purple shaded area indicates the <span class="math inline">\(p\)</span>-value region. Since <span class="math inline">\(p\)</span>-value <span class="math inline">\(&lt;  \alpha\)</span>, the null hypothesis is rejected.
</figcaption></figure>
</div>
<p>For this example, the <span class="math inline">\(p\)</span>-value is given as <span class="math display">\[P (Z&gt;z_{obs}|H_0 \text{ true} ) = 1−\Phi(z_{obs}) =0 .03\]</span> where <span class="math inline">\(\Phi\)</span> is the cumulative distribution function (CDF) of the standard normal distribution. Thus, the <em>p</em>-value is the probability (under the null hypothesis <span class="math inline">\(H_0\)</span>) of obtaining a value of <span class="math inline">\(Z\)</span> at least as extreme as the observed value <span class="math inline">\(z_{obs}\)</span>.</p>
<p>Suppose we want to test whether a population mean is equal to a specific value. Our hypotheses are:</p>
<ul>
<li>Null hypothesis: <span class="math inline">\(H_0: \mu = \mu_0\)</span>
</li>
<li>Alternative hypothesis: <span class="math inline">\(H_1: \mu \neq \mu_0\)</span>
</li>
</ul>
<p>In this case, we are interested in detecting whether the mean is either significantly larger or smaller than the hypothesized value, that is a two-tailed test. To determine how surprising our result is under the assumption that <span class="math inline">\(H_0\)</span> is true, we can calculate the <span class="math inline">\(p\)</span>-value. This is the probability of obtaining a <span class="math inline">\(Z\)</span> value that is at least as extreme as the observed value, <em>in either direction</em>.</p>
<p>The formula for the <span class="math inline">\(p\)</span>-value then becomes: <span class="math display">\[
p\text{-value} = 2 \left[1 - \Phi\left(|z_{\text{obs}}|\right)\right]
\]</span></p>
<p>where <span class="math inline">\(\Phi\)</span> is the cumulative distribution function (CDF) of the standard normal distribution, and <span class="math inline">\(|z_{\text{obs}}|\)</span> is the absolute value of our observed test statistic. This is shown in <a href="#fig-pval2" class="quarto-xref">Figure&nbsp;<span>22.8</span></a>.</p>
<div id="fig-pval2" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pval2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pval2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.8: Visualization of a two-tailed <span class="math inline">\(p\)</span>-value. The shaded purple regions in both tails represent the <span class="math inline">\(p\)</span>-value, corresponding to the probability (under the null hypothesis) of observing a test statistic as extreme or more extreme than the observed value z[obs]. The dashed vertical lines indicate the observed test statistic in both directions. Since this is a two-sided test, both tails are included in the calculation of the <span class="math inline">\(p\)</span>-value.
</figcaption></figure>
</div>
<section id="example-22.4-hypothesis-testing-using-the-p-value" class="level4"><h4 class="anchored" data-anchor-id="example-22.4-hypothesis-testing-using-the-p-value">Example 22.4: Hypothesis Testing Using the <span class="math inline">\(p\)</span>-value</h4>
<p>We have a random sample of <span class="math inline">\(n = 70\)</span> observations from a population with unknown distribution and unknown variance. From the sample, we obtain:</p>
<ul>
<li>Sample mean: <span class="math inline">\(\bar{x} = 14100\)</span>
</li>
<li>Sample standard deviation: <span class="math inline">\(s = 1900\)</span>
</li>
</ul>
<p>We want to test whether the population mean <span class="math inline">\(\mu\)</span> is greater than 13500, using the <span class="math inline">\(p\)</span>-value method.</p>
<ul>
<li><p><strong>Hypotheses</strong> <span class="math display">\[
H_0: \mu = 13500 \\
H_1: \mu &gt; 13500
\]</span></p></li>
<li><p><strong>Test Statistic</strong><br>
Since the population variance <span class="math inline">\(\sigma^2\)</span> is unknown but the sample is large, we use the standardized test statistic: <span class="math display">\[
Z = \frac{\bar{X} - \mu_0}{s / \sqrt{n}}
\]</span></p></li>
<li><p><strong>Observation</strong> <span class="math display">\[
z_{\text{obs}} = \frac{14100 - 13500}{1900 / \sqrt{70}} = 2.64
\]</span> Specifying a significance level or a formal decision rule isn’t necessary here, since the <span class="math inline">\(p\)</span>-value alone provides sufficient information to determine whether the null hypothesis should be rejected. We therefore compute the <span class="math inline">\(p\)</span>-value as the next step.</p></li>
<li><p><strong><span class="math inline">\(p\)</span>-value</strong><br>
Under the null hypothesis, <span class="math inline">\(Z \sim N(0, 1)\)</span>. The <span class="math inline">\(p\)</span>-value is the probability of obtaining a value as extreme or more extreme than the observed value when <span class="math inline">\(H_0\)</span> is true (see <a href="../appendix/normal-table.html" class="quarto-xref"><span>Appendix A</span></a>): <span class="math display">\[
\text{p-value} = P(Z &gt; 2.64) = 1 - \Phi(2.64) = 1 - 0.9959 = 0.0041
\]</span> See <a href="#fig-pex" class="quarto-xref">Figure&nbsp;<span>22.9</span></a> for an illustration of this <span class="math inline">\(p\)</span>-value.</p></li>
<li><p><strong>Conclusion</strong> As long as the significance level <span class="math inline">\(\alpha &gt; 0.0041\)</span>, we reject the null hypothesis. Thus, we reject <span class="math inline">\(H_0\)</span> at the 1% level of significance. In fact, we would reject it at any significance level above 0.41%, but not below. There is strong evidence in favor of <span class="math inline">\(H_1\)</span>; that the population mean is greater than 13500.</p></li>
</ul>
<div id="fig-pex" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.9: An illustration of the test in Example 22.4, where the <span class="math inline">\(p\)</span>-value is equal to 0.0041.
</figcaption></figure>
</div>
</section><section id="example-22.5-two-sided-hypothesis-test-with-p-value" class="level4"><h4 class="anchored" data-anchor-id="example-22.5-two-sided-hypothesis-test-with-p-value">Example 22.5: Two-Sided Hypothesis Test with <span class="math inline">\(p\)</span>-value</h4>
<p>We use the same setup as in Example 22.4, but this time we test against the two-sided alternative: <span class="math display">\[
H_1: \mu \neq 13,\!500
\]</span> This means that both very high and very low values of the test statistic <span class="math inline">\(Z\)</span> are considered evidence against the null hypothesis <span class="math inline">\(H_0\)</span>. We observe: <span class="math display">\[
z_{\text{obs}} = 2.64
\]</span> The <span class="math inline">\(p\)</span>-value is now calculated as:</p>
<p><span class="math display">\[
\begin{split}
p\text{-value} &amp; = P(Z &gt; z_{\text{obs}} \mid H_0) + P(Z &lt; -z_{\text{obs}} \mid H_0)
\\ &amp; = 2 \cdot [1 - \Phi(2.64)] = 2 \cdot (1 - 0.9959) = 0.0082
\end{split}
\]</span> We multiply by 2 because in a two-sided test, extreme outcomes in both directions (greater than or less than the hypothesized value) are considered equally inconsistent with the null hypothesis. Therefore, we calculate the probability of observing a test statistic at least as extreme as <span class="math inline">\(|z_{\text{obs}}|\)</span> in either tail of the distribution, as shown in <a href="#fig-pex2" class="quarto-xref">Figure&nbsp;<span>22.10</span></a>.</p>
<p>Since the <span class="math inline">\(p\)</span>-value is 0.0082, we would reject the null hypothesis at a 1% significance level. In fact, we would reject it at any significance level down to 0.82%, but not below that. This provides strong evidence in favor of the alternative hypothesis <span class="math inline">\(H_1\)</span> over the null hypothesis <span class="math inline">\(H_0\)</span>.</p>
<div id="fig-pex2" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="hyp-test_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pex2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22.10: Visualization of a two-tailed <span class="math inline">\(p\)</span>-value in Example 22.5.
</figcaption></figure>
</div>
</section></section><section id="hypothesis-testing-and-confidence-intervals" class="level2" data-number="22.6"><h2 data-number="22.6" class="anchored" data-anchor-id="hypothesis-testing-and-confidence-intervals">
<span class="header-section-number">22.6</span> Hypothesis Testing and Confidence Intervals</h2>
<p>When we are testing a hypothesis such as <span class="math display">\[
H_0 : \mu = \mu_0
\]</span> against the <strong>two-sided alternative hypothesis</strong> <span class="math display">\[
H_1 : \mu \ne \mu_0,
\]</span> we can use a confidence interval for the population mean <span class="math inline">\(\mu\)</span> instead of computing a test statistic directly. The key relationship is:</p>
<blockquote class="blockquote">
<p>The null hypothesis <span class="math inline">\(H_0\)</span> is <strong>rejected at significance level <span class="math inline">\(\alpha\)</span></strong> if and only if the <span class="math inline">\(100(1 - \alpha)\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span> <strong>does not include</strong> the value <span class="math inline">\(\mu_0\)</span>.</p>
</blockquote>
<p>Instead of calculating the value of a test statistic, we can construct a 95% confidence interval for <span class="math inline">\(\mu\)</span> and check whether the value <span class="math inline">\(\mu_0\)</span> lies within this interval or not (Significance level = 5%).</p>
<p>Suppose we are given a 95% confidence interval for the population mean as <span class="math inline">\(64.8 &lt; \mu &lt; 67.3\)</span>. We want to test the null hypothesis: <span class="math display">\[
H_0: \mu = 65 \quad
\]</span> against <span class="math display">\[
H_1: \mu \ne 65
\]</span> Since the hypothesized value 65 lies <strong>inside</strong> the confidence interval, we <strong>fail to reject</strong> the null hypothesis. In other words, the data do not provide sufficient evidence to suggest that the population mean differs from 65 at the 5% significance level.</p>
<p>To state this more generally:</p>
<ul>
<li>A 95% confidence interval contains all values of <span class="math inline">\(\mu\)</span> that would not be rejected in a two-sided test at the 5% significance level.</li>
<li>A 99% confidence interval contains all values of <span class="math inline">\(\mu\)</span> that would not be rejected at the 1% level.</li>
<li>A 99.9% confidence interval corresponds to a 0.1% significance level.</li>
<li>and so on…</li>
</ul>
<p>This shows how confidence intervals and hypothesis testing are closely related; they are essentially two sides of the same inferential coin.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note: when working with proportions
</div>
</div>
<div class="callout-body-container callout-body">
<p>While the above equivalence between hypothesis tests and confidence intervals holds well for means, it is <strong>not exact</strong> for proportions or differences in proportions. This is because confidence intervals for proportions use the sample proportion <span class="math inline">\(\hat{p}\)</span> in the standard error: <span class="math display">\[
\hat{p} \pm z_{\alpha/2} \cdot \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}
\]</span></p>
<p>and hypothesis tests for a proportion use the <strong>null proportion</strong> <span class="math inline">\(p_0\)</span> in the test statistic: <span class="math display">\[
Z = \frac{\hat{p} - p_0}{\sqrt{ \frac{p_0(1 - p_0)}{n} }}
\]</span></p>
<p>Thus, confidence intervals and hypothesis testing may give slightly different results in these cases, especially with small samples.</p>
</div>
</div>
</section><section id="hypothesis-testing-for-the-difference-between-two-population-means" class="level2" data-number="22.7"><h2 data-number="22.7" class="anchored" data-anchor-id="hypothesis-testing-for-the-difference-between-two-population-means">
<span class="header-section-number">22.7</span> Hypothesis Testing for the Difference Between Two Population Means</h2>
<p>In this section, we explore how to test hypotheses about the difference between the means of two populations. This is particularly useful when we want to determine if there is a statistically significant difference between the average values of two groups.</p>
<p>We use the same notation as in confidence interval estimation (<a href="estimation.html" class="quarto-xref"><span>Chapter 21</span></a>) for the difference between two means:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Population</th>
<th>Mean (<span class="math inline">\(\mu\)</span>)</th>
<th>Standard Deviation (<span class="math inline">\(\sigma\)</span>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Population 1</td>
<td><span class="math inline">\(\mu_x\)</span></td>
<td><span class="math inline">\(\sigma_x\)</span></td>
</tr>
<tr class="even">
<td>Population 2</td>
<td><span class="math inline">\(\mu_y\)</span></td>
<td><span class="math inline">\(\sigma_y\)</span></td>
</tr>
</tbody>
</table>
<p>We are interested in making inferences about the difference <span class="math inline">\(\mu_x - \mu_y\)</span>. Suppose we have one independent sample from each of the two populations. We summarize the data as:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 11%">
<col style="width: 37%">
<col style="width: 24%">
</colgroup>
<thead><tr class="header">
<th>Sample</th>
<th>Size (<span class="math inline">\(n\)</span>)</th>
<th>Sample Mean (<span class="math inline">\(\bar{x}\)</span> or <span class="math inline">\(\bar{y}\)</span>)</th>
<th>Sample Std. Dev. (<span class="math inline">\(s\)</span>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>From Population 1</td>
<td><span class="math inline">\(n_x\)</span></td>
<td><span class="math inline">\(\bar{x}\)</span></td>
<td><span class="math inline">\(s_x\)</span></td>
</tr>
<tr class="even">
<td>From Population 2</td>
<td><span class="math inline">\(n_y\)</span></td>
<td><span class="math inline">\(\bar{y}\)</span></td>
<td><span class="math inline">\(s_y\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Note:</strong> The samples must be independently drawn from the respective populations.</p>
<p>We want to test:</p>
<ul>
<li>Null hypothesis: <span class="math inline">\(H_0: \mu_x - \mu_y = D_0\)</span>
</li>
<li>Alternative hypothesis (two-sided): <span class="math inline">\(H_1: \mu_x - \mu_y \ne D_0\)</span>
</li>
</ul>
<p>Often, <span class="math inline">\(D_0 = 0\)</span>, meaning we test for equality of the population means:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_x = \mu_y\)</span></li>
<li><span class="math inline">\(H_1: \mu_x \ne \mu_y\)</span></li>
</ul>
<p>One-sided tests may also be appropriate, which corresponds to <span class="math inline">\(D_0&lt;0\)</span> or <span class="math inline">\(D_0&gt;0\)</span>:</p>
<ul>
<li>
<span class="math inline">\(H_1: \mu_x &lt; \mu_y\)</span> (or <span class="math inline">\(D_0&lt;0\)</span>)</li>
<li>
<span class="math inline">\(H_1: \mu_x &gt; \mu_y\)</span> (or <span class="math inline">\(D_0&gt;0\)</span>)</li>
</ul>
<p>We compare the observed difference in sample means <span class="math inline">\(\bar{x} - \bar{y}\)</span> to the hypothesized value <span class="math inline">\(D_0\)</span>. The core question becomes:</p>
<blockquote class="blockquote">
<p>Is the observed value of <span class="math inline">\(\bar{x} - \bar{y}\)</span> far enough from <span class="math inline">\(D_0\)</span> to reject <span class="math inline">\(H_0\)</span>?</p>
</blockquote>
<p>This decision again depends on the factors:</p>
<ul>
<li>Sample sizes (small vs large)</li>
<li>Whether population distributions are approximately normal</li>
<li>Whether population variances are known or unknown</li>
</ul>
<p>These factors determine the appropriate test statistic (e.g., <span class="math inline">\(Z\)</span> or <span class="math inline">\(t\)</span>) and which distribution to use. We will now look at specific cases based on these conditions.</p>
<section id="case-1-large-samples" class="level3" data-number="22.7.1"><h3 data-number="22.7.1" class="anchored" data-anchor-id="case-1-large-samples">
<span class="header-section-number">22.7.1</span> Case 1: Large Samples</h3>
<p>We assume <span class="math inline">\(n_x \geq 30\)</span> and <span class="math inline">\(n_y \geq 30\)</span>. With large samples, we do not need to assume anything about the population distributions.</p>
<p>The test statistic when population variances are known is given by: <span class="math display">\[
Z = \frac{(\bar{x} - \bar{y}) - D_0}{\sqrt{\frac{\sigma_x^2}{n_x} + \frac{\sigma_y^2}{n_y}}}
\]</span> and when population variances are unknown, we have <span class="math display">\[
Z = \frac{(\bar{x} - \bar{y}) - D_0}{\sqrt{\frac{s_x^2}{n_x} + \frac{s_y^2}{n_y}}}
\]</span> where:</p>
<ul>
<li>
<span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> are the sample means,</li>
<li>
<span class="math inline">\(D_0\)</span> is the hypothesized difference (typically <span class="math inline">\(0\)</span>),</li>
<li>
<span class="math inline">\(s_x^2\)</span> and <span class="math inline">\(s_y^2\)</span> are the sample variances,</li>
<li>
<span class="math inline">\(n_x\)</span> and <span class="math inline">\(n_y\)</span> are the sample sizes.</li>
</ul>
<p>The test statistics <span class="math inline">\(Z\)</span> above are approximately normally distributed, <span class="math inline">\(N(0,1)\)</span>, when <span class="math inline">\(H_0\)</span> is true. Rejection boundaries (critical values) are determined by the significance level and the alternative hypothesis, just as done earlier.</p>
</section><section id="case-2-small-samples" class="level3" data-number="22.7.2"><h3 data-number="22.7.2" class="anchored" data-anchor-id="case-2-small-samples">
<span class="header-section-number">22.7.2</span> Case 2: Small Samples</h3>
<p>Here, at least one of <span class="math inline">\(n_x\)</span> and <span class="math inline">\(n_y\)</span> is smaller than 30. In this case, both samples must come from normally distributed populations. That is, at least one of <span class="math inline">\(n_x\)</span> and <span class="math inline">\(n_y\)</span> is smaller than 30. In this case, both samples must come from normally distributed populations.</p>
<section id="a-population-variances-known" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="a-population-variances-known">a) Population Variances Known</h4>
<p>If <span class="math inline">\(\sigma_x^2\)</span> and <span class="math inline">\(\sigma_y^2\)</span> are known, the test statistic is given by: <span class="math display">\[
Z = \frac{(\bar{x} - \bar{y}) - D_0}{\sqrt{\frac{\sigma_x^2}{n_x} + \frac{\sigma_y^2}{n_y}}}
\]</span></p>
</section><section id="b-population-variances-unknown-but-assumed-equal" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="b-population-variances-unknown-but-assumed-equal">b) Population Variances Unknown but Assumed Equal</h4>
<p>We must assume that the population variances are equal, although their actual values are unknown. Then the test statistic is given by: <span class="math display">\[
t = \frac{(\bar{x} - \bar{y}) - D_0}{\sqrt{s_p^2 \left( \frac{1}{n_x} + \frac{1}{n_y} \right)}}
\]</span> where the pooled sample variance <span class="math inline">\(s_p^2\)</span> is: <span class="math display">\[
s_p^2 = \frac{(n_x - 1)s_x^2 + (n_y - 1)s_y^2}{n_x + n_y - 2}
\]</span> This <span class="math inline">\(t\)</span> statistic follows a <span class="math inline">\(t\)</span>-distribution with: <span class="math display">\[
\nu = n_x + n_y - 2
\]</span> degrees of freedom when <span class="math inline">\(H_0\)</span> is true.</p>
</section><section id="c-population-variances-unknown-and-not-assumed-equal-welchs-t-test" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="c-population-variances-unknown-and-not-assumed-equal-welchs-t-test">c) Population Variances Unknown and Not Assumed Equal (Welch’s t-test)</h4>
<p>If we cannot assume equal variances, we use <strong>Welch’s t-test</strong> with statistic: <span class="math display">\[
t = \frac{(\bar{x} - \bar{y}) - D_0}{\sqrt{\frac{s_x^2}{n_x} + \frac{s_y^2}{n_y}}}
\]</span> This test statistic approximately follows a <span class="math inline">\(t\)</span>-distribution with degrees of freedom calculated by <strong>Welch-Satterthwaite approximation</strong>: <span class="math display">\[
\nu = \frac{\left( \frac{s_x^2}{n_x} + \frac{s_y^2}{n_y} \right)^2}{
\frac{\left( s_x^2/n_x \right)^2}{n_x - 1} +
\frac{\left( s_y^2/n_y \right)^2}{n_y - 1}}
\]</span> This test is more robust when the assumption of equal population variances is questionable.</p>
</section><section id="example-22.6-hypothesis-test-for-difference-between-two-means" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.6-hypothesis-test-for-difference-between-two-means">Example 22.6: Hypothesis Test for Difference Between Two Means</h4>
<p>We consider two independent random samples. We want to test whether the two populations have the same mean. The population variances are unknown, but we estimate them using the sample standard deviations. The sample information is:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 23%">
<col style="width: 19%">
<col style="width: 31%">
</colgroup>
<thead><tr class="header">
<th>Sample</th>
<th>Sample size (<span class="math inline">\(n\)</span>)</th>
<th>Mean (<span class="math inline">\(\bar{x}\)</span> / <span class="math inline">\(\bar{y}\)</span>)</th>
<th>Standard deviation (<span class="math inline">\(s\)</span>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>From population 1</td>
<td><span class="math inline">\(n_x = 36\)</span></td>
<td><span class="math inline">\(\bar{x} = 20.1\)</span></td>
<td><span class="math inline">\(s_x = 2.35\)</span></td>
</tr>
<tr class="even">
<td>From population 2</td>
<td><span class="math inline">\(n_y = 36\)</span></td>
<td><span class="math inline">\(\bar{y} = 19.2\)</span></td>
<td><span class="math inline">\(s_y = 2.25\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Step 1: Hypotheses</strong><br>
We test: <span class="math display">\[
\begin{split}
&amp; H_0: \mu_x - \mu_y = 0 \quad \text{(i.e., no difference in population means)} \\ &amp;
H_1: \mu_x - \mu_y \neq 0 \quad \text{(i.e., the means are different)}
\end{split}
\]</span></p></li>
<li><p><strong>Step 2: Significance Level</strong><br>
We choose a significance level of <span class="math inline">\(\alpha = 0.05\)</span>.</p></li>
<li><p><strong>Step 3: Test Statistic</strong><br>
Since both samples are large (<span class="math inline">\(n \geq 30\)</span>), we can use the standard normal distribution. The test statistic is calculated using: <span class="math display">\[
Z = \frac{(\bar{x} - \bar{y}) - D_0}{\sqrt{ \frac{s_x^2}{n_x} + \frac{s_y^2}{n_y} }} \sim N(0,1)
\]</span> Here, <span class="math inline">\(D_0 = 0\)</span> under the null hypothesis.</p></li>
<li><p><strong>Step 4: Decision Rule</strong><br>
We reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z_{\text{obs}}| &gt; 1.96\)</span> (the critical value for a 95% confidence level two-tailed test).</p></li>
<li><p><strong>Step 5: Observation</strong><br>
Plugging in values in the test statistic: <span class="math display">\[
Z = \frac{(20.1 - 19.2) - 0}{\sqrt{ \frac{2.35^2}{36} + \frac{2.25^2}{36} }} = \frac{0.9}{\sqrt{ \frac{5.5225 + 5.0625}{36} }} = \frac{0.9}{\sqrt{ \frac{10.585}{36} }} = \frac{0.9}{\sqrt{0.294}} \approx 1.66
\]</span></p></li>
<li><p><strong>Step 6: Conclusion</strong><br>
Since <span class="math inline">\(|z_{\text{obs}}| = 1.66 &lt; 1.96\)</span>, we fail to reject the null hypothesis. At the 5% significance level, the sample means are not significantly different.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Using confidence interval instead
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can also compute a 95% confidence interval for the difference in means: <span class="math display">\[
(\bar{x} - \bar{y}) \pm z_{\alpha/2} \cdot \sqrt{ \frac{s_x^2}{n_x} + \frac{s_y^2}{n_y} }
\]</span> Plugging in the numbers: <span class="math display">\[
0.9 \pm 1.96 \cdot \sqrt{ \frac{2.35^2}{36} + \frac{2.25^2}{36} } = 0.9 \pm 1.96 \cdot \sqrt{0.294} \approx 0.9 \pm 1.0628
\]</span> Thus, the confidence interval is: <span class="math display">\[
[-0.1628;\, 1.9628]
\]</span> Since 0 is included in the interval, this supports our previous conclusion that there is no significant difference between the means.</p>
</div>
</div>
</section><section id="example-22.7-hypothesis-test-for-difference-between-two-means" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.7-hypothesis-test-for-difference-between-two-means">Example 22.7: Hypothesis Test for Difference Between Two Means</h4>
<p>We have independent random samples from two normally distributed populations with <strong>equal (but unknown) variances</strong>. We wish to test whether the mean of population 1 is greater than that of population 2, at a 1% significance level.</p>
<p>The sample summary is given in below table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 23%">
<col style="width: 19%">
<col style="width: 31%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>Sample size (<span class="math inline">\(n\)</span>)</th>
<th>Mean (<span class="math inline">\(\bar{x}\)</span> / <span class="math inline">\(\bar{y}\)</span>)</th>
<th>Standard deviation (<span class="math inline">\(s\)</span>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Population 1</td>
<td><span class="math inline">\(n_x = 11\)</span></td>
<td><span class="math inline">\(\bar{x} = 1.23\)</span></td>
<td><span class="math inline">\(s_x = 0.23\)</span></td>
</tr>
<tr class="even">
<td>Population 2</td>
<td><span class="math inline">\(n_y = 13\)</span></td>
<td><span class="math inline">\(\bar{y} = 1.18\)</span></td>
<td><span class="math inline">\(s_y = 0.27\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Step 1: Hypotheses</strong><br>
We set up the hypotheses as: <span class="math display">\[
\begin{split}
&amp; H_0: \mu_x - \mu_y = 0 \quad (\text{no difference})  \\ &amp;
H_1: \mu_x - \mu_y &gt; 0 \quad (\text{population 1 has a larger mean})
\end{split}
\]</span></p></li>
<li><p><strong>Step 2: Significance Level</strong><br>
We are testing at the 1% level: <span class="math display">\[
\alpha = 0.01
\]</span></p></li>
<li><p><strong>Step 3: Test Statistic</strong><br>
Since the population variances are assumed equal and the samples are small, we use a <strong>pooled <span class="math inline">\(t\)</span>-test</strong>: <span class="math display">\[
t = \frac{(\bar{x} - \bar{y}) - 0}{\sqrt{s_p^2 \left( \frac{1}{n_x} + \frac{1}{n_y} \right)}} \sim t(\nu = n_x + n_y - 2 )
\]</span> where the <strong>pooled variance</strong> is calculated as: <span class="math display">\[
s_p^2 = \frac{(n_x - 1)s_x^2 + (n_y - 1)s_y^2}{n_x + n_y - 2}
= \frac{(11 - 1)(0.23^2) + (13 - 1)(0.27^2)}{22} = 0.0638
\]</span></p></li>
<li><p><strong>Step 4: Decision Rule</strong><br>
We use a right-tailed <span class="math inline">\(t\)</span>-test with degrees of freedom: <span class="math display">\[
\nu =  n_x + n_y - 2 = 11 + 13 - 2 = 22
\]</span> Critical value for a one-tailed test at <span class="math inline">\(\alpha = 0.01\)</span>: <span class="math display">\[
t_{22, 0.01} = 2.508
\]</span></p></li>
<li><p><strong>Step 5: Observation</strong><br>
We compute the test statistic: <span class="math display">\[
t_{\text{obs}} = \frac{1.23 - 1.18}{\sqrt{0.0638 \left( \frac{1}{11} + \frac{1}{13} \right)}} = 0.483
\]</span></p></li>
<li><p><strong>Step 6: Conclusion</strong> Since <span class="math inline">\(t_{\text{obs}} = 0.483 &lt; 2.508\)</span>, we fail to reject the null hypothesis. There is not enough evidence at the 1% level to conclude that the mean of population 1 is greater than that of population 2.</p></li>
</ul></section></section></section><section id="hypothesis-testing-for-the-difference-between-two-proportions" class="level2" data-number="22.8"><h2 data-number="22.8" class="anchored" data-anchor-id="hypothesis-testing-for-the-difference-between-two-proportions">
<span class="header-section-number">22.8</span> Hypothesis Testing for the Difference Between Two Proportions</h2>
<p>When comparing two proportions, we consider two populations:</p>
<ul>
<li>
<strong>Population 1</strong> with proportion <span class="math inline">\(P_x\)</span>
</li>
<li>
<strong>Population 2</strong> with proportion <span class="math inline">\(P_y\)</span>
</li>
</ul>
<p>We want to test whether <span class="math inline">\(P_x = P_y\)</span>, which is equivalent to testing whether the difference in population proportions is zero: <span class="math display">\[
H_0: p_x - p_y = 0
\]</span> This is the null hypothesis. The alternative hypothesis can be:</p>
<ul>
<li>Two-sided:</li>
</ul>
<p><span class="math display">\[
H_1: p_x - p_y \ne 0
\]</span></p>
<ul>
<li>One-sided:</li>
</ul>
<p><span class="math display">\[
H_1: p_x - p_y &lt; 0 \quad \text{or} \quad H_1: p_x - p_y &gt; 0
\]</span></p>
<p>From each population, we take an independent samples:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Sample</th>
<th>Sample Size</th>
<th>Sample Proportion</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>From population 1</td>
<td><span class="math inline">\(n_x\)</span></td>
<td><span class="math inline">\(\hat{p}_x\)</span></td>
</tr>
<tr class="even">
<td>From population 2</td>
<td><span class="math inline">\(n_y\)</span></td>
<td><span class="math inline">\(\hat{p}_y\)</span></td>
</tr>
</tbody>
</table>
<p>We then test whether the observed difference between <span class="math inline">\(\hat{p}_x\)</span> and <span class="math inline">\(\hat{p}_y\)</span> is large enough to reject the null hypothesis.</p>
<p>When sample sizes are large, we use the following test statistic: <span class="math display">\[
Z = \frac{\hat{p}_x - \hat{p}_y}{\sqrt{ \hat{p}_0 (1 - \hat{p}_0) \left( \frac{1}{n_x} + \frac{1}{n_y} \right)}}
\]</span> where <span class="math inline">\(\hat{p}_0\)</span> is the pooled proportion under the null hypothesis, calculated as: <span class="math display">\[
\hat{p}_0 = \frac{n_x \hat{p}_x + n_y \hat{p}_y}{n_x + n_y}
\]</span> <span class="math inline">\(\hat{p}_0\)</span> represents the proportion in the <em>combined sample</em>, assuming the null hypothesis (<span class="math inline">\(p_x = p_y\)</span>) is true.</p>
<p>When testing whether two population proportions differ, we can use a test statistic <span class="math inline">\(Z\)</span> that is approximately standard normally distributed, <span class="math inline">\(Z \sim N(0, 1)\)</span>, assuming the null hypothesis <span class="math inline">\(H_0\)</span> is true. The rejection regions (critical values) depend on the significance level <span class="math inline">\(\alpha\)</span> and the alternative hypothesis.</p>
<section id="example-22.8-hypothesis-testing-for-a-difference-between-two-proportions" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.8-hypothesis-testing-for-a-difference-between-two-proportions">Example 22.8: Hypothesis Testing for a Difference Between Two Proportions</h4>
<p>Let <span class="math inline">\(p_x\)</span> denote the proportion who support a particular political party in population 1, and let <span class="math inline">\(p_y\)</span> be the corresponding proportion in population 2. We want to examine, at a 5% significance level, whether there is a difference in party support between the two populations. A simple random sample of <span class="math inline">\(n_x = 150\)</span> individuals is taken from population 1, and <span class="math inline">\(n_y = 250\)</span> individuals from population 2. The sample proportions of supporters turn out to be:</p>
<ul>
<li><span class="math inline">\(\hat{p}_x = 0.36\)</span></li>
<li><span class="math inline">\(\hat{p}_y = 0.27\)</span></li>
</ul>
<p>The sample sizes are sufficiently large to meet the requirements for using a normal approximation.</p>
<ul>
<li>
<strong>Step 1: Hypotheses</strong><br><span class="math display">\[
H_0: P_x - P_y = 0 \quad \text{(i.e., } P_x = P_y \text{)}
\]</span>
</li>
</ul>
<p><span class="math display">\[
H_1: P_x - P_y \neq 0 \quad \text{(i.e., } P_x \neq P_y \text{)}
\]</span></p>
<ul>
<li><p><strong>Step 2: Significance Level</strong><br><span class="math display">\[
\alpha = 0.05
\]</span></p></li>
<li><p><strong>Step 3: Test Statistic</strong><br>
We use the following test statistic for comparing proportions: <span class="math display">\[
Z = \frac{\hat{p}_x - \hat{p}_y}{\sqrt{\hat{p}_0(1 - \hat{p}_0) \left( \frac{1}{n_x} + \frac{1}{n_y} \right)}} \sim N(0,1)
\]</span> where <span class="math inline">\(\hat{p}_0\)</span> is the pooled proportion: <span class="math display">\[
\hat{p}_0 = \frac{n_x \hat{p}_x + n_y \hat{p}_y}{n_x + n_y}
= \frac{150 \cdot 0.36 + 250 \cdot 0.27}{150 + 250}
= 0.30375
\]</span></p></li>
<li><p><strong>Step 4: Decision Rule</strong><br>
Reject <span class="math inline">\(H_0\)</span> if: <span class="math display">\[
|Z_{\text{obs}}| &gt; 1.96
\]</span></p></li>
<li><p><strong>Step 5: Observation</strong><br>
The observed test statistic is: <span class="math display">\[
Z_{\text{obs}} = \frac{0.36 - 0.27}{\sqrt{0.30375(1 - 0.30375) \left( \frac{1}{150} + \frac{1}{250} \right)}} = 1.895
\]</span></p></li>
<li><p><strong>Step 6: Conclusion</strong><br>
Since <span class="math inline">\(|1.895| &lt; 1.96\)</span>, we fail to reject the null hypothesis at the 5% significance level. This means we do not have sufficient evidence to claim a significant difference in party support between the two populations.</p></li>
</ul></section><section id="example-22.9-one-sided-hypothesis-test-for-difference-in-proportions" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-22.9-one-sided-hypothesis-test-for-difference-in-proportions">Example 22.9: One-Sided Hypothesis Test for Difference in Proportions</h4>
<p>This example builds on Example 22.8, but now we test a <em>one-sided alternative hypothesis</em>. Specifically, we want to investigate whether there is a higher proportion of supporters in population 1 than in population 2, using a significance level of 5%.</p>
<ul>
<li><p><strong>Step 1: Hypotheses</strong><br><span class="math display">\[
\begin{align*}
H_0 &amp;: p_x - p_y = 0 \quad \text{(i.e., } p_x = p_y \text{)} \\
H_1 &amp;: p_x - p_y &gt; 0 \quad \text{(i.e., } p_x &gt; p_y \text{)}
\end{align*}
\]</span></p></li>
<li><p><strong>Step 3: Significance Level</strong><br><span class="math display">\[
\alpha = 0.05
\]</span></p></li>
<li><p><strong>Step 3: Test Statistic</strong><br>
We use the same test statistic for comparing proportions as in Example 22.8: <span class="math display">\[
Z = \frac{\hat{p}_x - \hat{p}_y}{\sqrt{\hat{p}_0(1 - \hat{p}_0) \left( \frac{1}{n_x} + \frac{1}{n_y} \right)}}
\]</span> where <span class="math inline">\(\hat{p}_0\)</span> is the pooled proportion: <span class="math display">\[
\hat{p}_0 = \frac{n_x \hat{p}_x + n_y \hat{p}_y}{n_x + n_y}
= \frac{150 \cdot 0.36 + 250 \cdot 0.27}{150 + 250}
= 0.30375
\]</span></p></li>
<li><p><strong>Step 4: Decision Rule</strong><br>
Reject <span class="math inline">\(H_0\)</span> if: <span class="math display">\[
z_{\text{obs}} &gt; z_{\alpha} = 1.645
\]</span></p></li>
<li><p><strong>Step 5: Observation</strong><br>
Same as in the previous example (standardized difference in sample proportions). <span class="math display">\[
z_{\text{obs}} = 1.895
\]</span></p></li>
<li><p><strong>Step 6: Conclusion</strong><br>
Since <span class="math inline">\(z_{\text{obs}} = 1.895 &gt; 1.645\)</span>, we reject the null hypothesis in favor of the alternative.</p></li>
</ul>
<blockquote class="blockquote">
<p>There is significant evidence, at the 5% level, that the proportion of supporters in population 1 is greater than in population 2.</p>
</blockquote>
<p>This result provides statistical support for the claim that <span class="math inline">\(p_x &gt; p_y\)</span>.</p>
</section></section><section id="exercises" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li>A courier company claims that their average delivery time for packages is no more than 2 days. A consumer watchdog suspects the actual delivery time might be longer. To test this claim, they randomly select 100 recent deliveries and record their delivery times. The sample has:
<ul>
<li>Sample size: <span class="math inline">\(n = 100\)</span>
</li>
<li>Sample mean: <span class="math inline">\(\bar{x} = 2.2\)</span> days</li>
<li>Population standard deviation (assumed known): <span class="math inline">\(\sigma = 0.8\)</span> days</li>
</ul>
Perform a test to check whether the true mean delivery time exceeds 2 days on 5% significance level. Make sure to include all 6 steps for classical hypothesis testing.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Hypotheses</strong><br><span class="math display">\[
\begin{align*}
H_0 &amp;: \mu = 2 \quad \text{(company claim)} \\
H_1 &amp;: \mu &gt; 2 \quad \text{(watchdog suspicion)}
\end{align*}
\]</span></p>
<p><strong>Step 2: Significance level</strong><br>
We choose a significance level <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>Step 2: Test statistic</strong><br>
Since the sample size is large and <span class="math inline">\(\sigma\)</span> is known, we use a Z-test: <span class="math display">\[
z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} \sim N(0.1)
\]</span></p>
<p><strong>Step 3: Critical value</strong><br>
From standard normal tables: <span class="math display">\[
z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} = \frac{2.2 - 2}{0.8 / \sqrt{100}} = \frac{0.2}{0.08} = 2.5
\]</span> <span class="math display">\[
z_{0.05} = 1.645
\]</span></p>
<p><strong>Step 4: Decision Rule</strong><br>
We reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(z_{obs} &gt;  1.645\)</span>.</p>
<p><strong>Step 5: Observation</strong><br><span class="math display">\[
z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} = \frac{2.2 - 2}{0.8 / \sqrt{100}} = \frac{0.2}{0.08} = 2.5
\]</span> <strong>Step 6: Conclusion</strong><br>
Since <span class="math inline">\(z = 2.5 &gt; 1.645\)</span>, we reject the null hypothesis. There is evidence at the 5% level to suggest that the average delivery time is greater than 2 days, contradicting the company’s claim.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li>A health researcher wants to test whether a new natural sleep supplement increases the average hours of sleep per night. In the general population, the average sleep duration is known to be 7 hours. The researcher gives the supplement to 12 participants and records their sleep hours over one week. The sample statistics are as follows:
<ul>
<li>Sample size: <span class="math inline">\(n = 12\)</span>
</li>
<li>Sample mean: <span class="math inline">\(\bar{x} = 7.6\)</span> hours</li>
<li>Sample standard deviation: <span class="math inline">\(s = 0.8\)</span> hours</li>
</ul>
Test if the supplement leads to longer sleep on average. Set <span class="math inline">\(\alpha = 0.05\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Hypotheses</strong><br><span class="math display">\[
\begin{align*}
H_0 &amp;: \mu = 7 \quad \text{(no effect)} \\
H_1 &amp;: \mu &gt; 7 \quad \text{(supplement increases sleep)}
\end{align*}
\]</span></p>
<p><strong>Step 2: Significance level</strong> <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>Step 3: Test statistics</strong><br>
Use a <span class="math inline">\(t\)</span>-test (since <span class="math inline">\(n\)</span> is small and <span class="math inline">\(\sigma\)</span> is unknown):<br><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}} \sim t(n-1)
\]</span></p>
<p><strong>Step 4: Decision Rule</strong><br>
Degrees of freedom: <span class="math display">\[
\nu = n - 1 = 11
\]</span> From the <span class="math inline">\(t\)</span>-table, <span class="math inline">\(t_{0.05, 11} \approx 1.796\)</span> so we reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}&gt;1.796\)</span></p>
<p><strong>Step 5: Observation</strong><br><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{s / \sqrt{n}} = \frac{7.6 - 7}{0.8 / \sqrt{12}} = \frac{0.6}{0.231} \approx 2.597
\]</span></p>
<p><strong>Step 6: Conclusion:</strong><br>
Since <span class="math inline">\(t = 2.597 &gt; 1.796\)</span>, we reject the null hypothesis. There is evidence at the 5% level that the supplement increases average sleep time.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li>A school introduces a new teaching method and wants to evaluate if it has increased students’ average test scores. Historically, the average test score has been 75. A sample of 40 students taught with the new method had a mean score of 77.5 with a standard deviation of 10. Can we conclude that the new method improves average scores? Use the <span class="math inline">\(p\)</span>-value approach and a significance level of 5%.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Hypotheses:</strong><br><span class="math display">\[
\begin{align*}
H_0 &amp;: \mu = 75 \\
H_1 &amp;: \mu &gt; 75
\end{align*}
\]</span></p>
<p><strong>Compute the test statistic</strong><br>
We use a <span class="math inline">\(z\)</span>-test (sample is large, <span class="math inline">\(n = 40\)</span>): <span class="math display">\[
z = \frac{\bar{x} - \mu_0}{s / \sqrt{n}} = \frac{77.5 - 75}{10 / \sqrt{40}} = \frac{2.5}{1.58} \approx 1.58
\]</span></p>
<p><strong>Find the p-value</strong><br>
We calculate the area to the right of <span class="math inline">\(z = 1.58\)</span> under the standard normal distribution: <span class="math display">\[
p\text{-value} = P(Z &gt; 1.58) \approx 0.0571
\]</span></p>
<p><strong>Compare with significance level</strong><br>
Since <span class="math inline">\(p = 0.0571 &gt; \alpha = 0.05\)</span>, we fail to reject the null hypothesis.</p>
<p><strong>Conclusion:</strong><br>
There is not enough evidence at the 5% significance level to conclude that the new teaching method improves scores.</p>
</div>
</div>
</div>
<ol start="4" type="1">
<li>A researcher wants to know if a new tutoring program changes student performance. Six students take a test before and after the program. Their scores are:</li>
</ol>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: left;">Student</th>
<th style="text-align: center;">Before</th>
<th style="text-align: right;">After</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: center;">72</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: center;">65</td>
<td style="text-align: right;">70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: center;">80</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: center;">75</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: center;">68</td>
<td style="text-align: right;">74</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: center;">74</td>
<td style="text-align: right;">78</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Test if the tutoring program had an effect at the 5% significance level.</li>
<li>Compute the <span class="math inline">\(p\)</span>-value for the test in (a).</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>We go through all steps of the test:</li>
</ol>
<p><strong>Step 1: Hypotheses</strong><br><span class="math display">\[
H_0: \mu_d = 0 \quad \text{(no mean difference)} \\
H_1: \mu_d \neq 0 \quad \text{(mean difference exists)}
\]</span></p>
<p><strong>Step 2: Significance level</strong><br><span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Step 3: Test statistic</strong><br><span class="math display">\[
t = \frac{\bar{d}}{s_d / \sqrt{n}} \sim t(n-1)
\]</span></p>
<p><strong>Step 4: Decision Rule</strong><br>
Degrees of freedom: <span class="math display">\[
df = n - 1 = 5
\]</span> Significance level (two-tailed): <span class="math display">\[
\alpha = 0.05 \Rightarrow \alpha/2 = 0.025
\]</span> From t-table: <span class="math display">\[
t_{\text{crit}} = t_{0.025, 5} \approx 2.571
\]</span> So we reject <span class="math inline">\(H_0\)</span> if:</p>
<p><span class="math display">\[
|t_{obs}| &gt; t_{\text{crit}} = 2.571
\]</span></p>
<p><strong>Step 5: Observation</strong><br></p>
<p>Compute the sample statistics needed first using the data in the table. Differences are given by:</p>
<p><span class="math display">\[
d_i = \text{After} - \text{Before}
\]</span></p>
<table class="caption-top table">
<thead><tr class="header">
<th>Student</th>
<th><span class="math inline">\(d_i\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>6</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
</tr>
<tr class="odd">
<td>3</td>
<td>5</td>
</tr>
<tr class="even">
<td>4</td>
<td>0</td>
</tr>
<tr class="odd">
<td>5</td>
<td>6</td>
</tr>
<tr class="even">
<td>6</td>
<td>4</td>
</tr>
</tbody>
</table>
<p>Sample mean and sample standard deviation of differences are given by: <span class="math display">\[
\bar{d} = \frac{6 + 5 + 5 + 0 + 6 + 4}{6} = \frac{26}{6} \approx 4.33
\]</span> <span class="math display">\[
s_d^2 = \frac{1}{n-1} \sum (d_i - \bar{d})^2 = \frac{25.33}{5} = 5.07
\]</span> Thus the standard deviation is <span class="math display">\[
s_d = \sqrt{5.07} \approx 2.25
\]</span> The observed value of the test statistic is then given by: <span class="math display">\[
t_{obs} = \frac{\bar{d}}{s_d / \sqrt{n}} = \frac{4.33}{2.25 / \sqrt{6}} \approx 4.70
\]</span></p>
<p><strong>Step 6: Conclusion:</strong></p>
<p>We reject the null hypothesis since <span class="math inline">\(t_{obs} = 4.70 &gt; 2.571\)</span>. The observed mean difference is statistically significant. The tutoring program appears to have a real effect on student performance.</p>
<ol start="2" type="a">
<li>This is a two-tailed test so the <span class="math inline">\(p\)</span>-value is <span class="math display">\[
p = 2 \cdot P(T &gt; 4.70) \approx 0.005
\]</span> We reject the null hypothesis on any significance level <span class="math inline">\(\alpha &gt; 0.005\)</span>. The data suggests that the tutoring program has a statistically significant effect on student scores.</li>
</ol>
</div>
</div>
</div>
<ol start="5" type="1">
<li>
<p>A company wants to compare the average productivity (measured in units/hour) of two different manufacturing plants, A and B. Management suspects there may be a difference in mean productivity between the two locations.</p>
<p>A random sample of 100 workers from Plant A had a mean productivity of 52.3 units/hour with a standard deviation of 8.5.<br>
A random sample of 120 workers from Plant B had a mean productivity of 49.7 units/hour with a standard deviation of 9.2.</p>
<p>Test, at the 5% significance level, whether there is a difference in mean productivity between the two plants, i.e.: <span class="math display">\[
\begin{split}
&amp; H_0: \mu_A - \mu_B = 0 \\ &amp;
H_1: \mu_A - \mu_B \neq 0
\end{split}
\]</span></p>
</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Hypotheses</strong> <span class="math display">\[
\begin{split}
&amp; H_0: \mu_A - \mu_B = 0 \\ &amp;
H_1: \mu_A - \mu_B \neq 0
\end{split}
\]</span> <strong>Step 2: Significance level</strong><br><span class="math inline">\(\alpha = 0.05\)</span></p>
<p><strong>Step 3: Test statistic</strong><br>
Large samples and unknown variances: <span class="math display">\[
z = \frac{(\bar{x}_A - \bar{x}_B) - 0}{\sqrt{\frac{s_A^2}{n_A} + \frac{s_B^2}{n_B}}} \sim N(0,1)
\]</span></p>
<p><strong>Step 4: Decision rule</strong><br>
For a two-tailed test at <span class="math inline">\(\alpha = 0.05\)</span>, the critical values are: <span class="math display">\[
z_{\text{crit}} = \pm 1.96
\]</span> We reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|z_{obs}| &gt; 1.96\)</span>.</p>
<p><strong>Step 5: Observation</strong><br>
The observed sample values are as follows:</p>
<ul>
<li>
<span class="math inline">\(\bar{x}_A = 52.3\)</span>, <span class="math inline">\(s_A = 8.5\)</span>, <span class="math inline">\(n_A = 100\)</span><br>
</li>
<li>
<span class="math inline">\(\bar{x}_B = 49.7\)</span>, <span class="math inline">\(s_B = 9.2\)</span>, <span class="math inline">\(n_B = 120\)</span>
</li>
</ul>
<p>The standard error is given by <span class="math display">\[
\begin{split}
\sqrt{\frac{s_A^2}{n_A} + \frac{s_B^2}{n_B}}&amp;  = \sqrt{\frac{8.5^2}{100} + \frac{9.2^2}{120}} \\ &amp;
= \sqrt{\frac{72.25}{100} + \frac{84.64}{120}}  \\ &amp; = \sqrt{0.7225 + 0.7053} \approx \sqrt{1.4278} \approx 1.194
\end{split}
\]</span> and the observed values is then equal to <span class="math display">\[
z_{obs} = \frac{(\bar{x}_A - \bar{x}_B) - 0}{SE} = \frac{52.3 - 49.7}{1.194} \approx \frac{2.6}{1.194} \approx 2.18
\]</span></p>
<p><strong>Step 5: Conclusion</strong><br>
Since <span class="math inline">\(z = 2.18 &gt; 1.96\)</span>, we reject the null hypothesis. There is statistical evidence at the 5% level to suggest that there is a significant difference in mean productivity between the two plants.</p>
</div>
</div>
</div>
<ol start="6" type="1">
<li>A nutritionist claims that the average daily intake of sugar among adults in a certain city is more than 50 grams. A random sample of 36 adults shows a mean intake of 52.8 grams with a standard deviation of 6 grams. Can we support the nutritionist’s claim at the 1% significance level using a confidence interval?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We are testing the following: <span class="math display">\[
H_0: \mu \leq 50 \quad \text{vs.} \quad H_1: \mu &gt; 50
\]</span></p>
<p>A significance level of 1% <span class="math inline">\((\alpha = 0.01)\)</span> corresponds to a 99% confidence interval (<span class="math inline">\((1-\alpha) = 0.99\)</span>).</p>
<p><strong>Given:</strong></p>
<ul>
<li><span class="math inline">\(\bar{x} = 52.8\)</span></li>
<li><span class="math inline">\(s = 6\)</span></li>
<li><span class="math inline">\(n = 36\)</span></li>
<li>Confidence level = 99% ⇒ <span class="math inline">\(z_{\alpha/2} = z_{0.005} = 2.576\)</span>
</li>
</ul>
<p>The confidence interval is given by <span class="math inline">\(\bar{x} \pm \underbrace{z_{\alpha/2} \left( \frac{s}{\sqrt{n}} \right) }_{\text{margin of error}}\)</span></p>
<p><strong>Compute the margin of error (ME):</strong> <span class="math display">\[
z_{0.005} \cdot \frac{s}{\sqrt{n}} = 2.576 \cdot \frac{6}{\sqrt{36}} = 2.576 \cdot 1 = 2.576
\]</span></p>
<p><strong>Construct the interval:</strong> <span class="math display">\[
\bar{x} \pm ME = 52.8 \pm 2.576 = (50.224,\ 55.376)
\]</span></p>
<p><strong>Decision based on CI:</strong> Since the null value <span class="math inline">\(\mu = 50\)</span> is just outside the confidence interval, we reject the null hypothesis. The 99% confidence interval does <strong>not</strong> contain the hypothesized value 50, which implies that the data provides enough evidence (at the 1% significance level) to support the claim that the average sugar intake is greater than 50 grams.</p>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/termehs\.github\.io\/found-stats\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../inferential/estimation.html" class="pagination-link" aria-label="Estimation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chi2/chi2.html" class="pagination-link" aria-label="The Chi Square Method">
        <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Chi Square Method</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Foundational Statistics by Termeh Shafie.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/termehs/found-stats/edit/main/inferential/hyp-test.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/termehs/found-stats/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>