<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Termeh Shafie">
<title>32&nbsp; Instrumental Variables Estimation – Foundational Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../appendix/normal-table.html" rel="next">
<link href="../regression/reg-diagnostics.html" rel="prev">
<link href="../cover.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6bb5ad484749947dbf006bb4d74c4af5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link href="../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><script src="../site_libs/viz-1.8.2/viz.js"></script><link href="../site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="../site_libs/grViz-binding-1.0.11/grViz.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../regression/reg-framework.html">Regression Analysis</a></li><li class="breadcrumb-item"><a href="../regression/iv-est.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Instrumental Variables Estimation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundational Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/termehs/found-stats" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/what-is-stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Unavoidable Math</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-surveys.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Surveys: Key Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/variable-class.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variable Classification</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/describe-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing a Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/central-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of Central Tendency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/dispersion-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Measures of Dispersion</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/what-is-prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/count-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Counting Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Random Variables and Probability Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/discrete-dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/cont-dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/jointly-dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Jointly Distributed Random Variables</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Sampling and Sampling Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling-dist-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling Distributions for a Sample Mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling-dist-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Sampling Distributions for a Sample Proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/intro-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">From Probability to Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/hyp-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Chi Square Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Chi Square Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Goodness-of-Fit Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2-ind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing for Independence</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The Regression Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-inf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regression Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Categorical Variables in Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Residual Analysis and Model Diagnostics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/iv-est.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Instrumental Variables Estimation</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/normal-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Standard Normal Distribution Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/t-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span> Distribution Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/chi2-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(\chi^2\)</span> Distribution Table</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#what-makes-a-good-instrument" id="toc-what-makes-a-good-instrument" class="nav-link active" data-scroll-target="#what-makes-a-good-instrument"><span class="header-section-number">32.1</span> What Makes a Good Instrument?</a>
  <ul class="collapse">
<li><a href="#relevance" id="toc-relevance" class="nav-link" data-scroll-target="#relevance"><span class="header-section-number">32.1.1</span> Relevance</a></li>
  <li><a href="#exogeneity-exclusion-restriction" id="toc-exogeneity-exclusion-restriction" class="nav-link" data-scroll-target="#exogeneity-exclusion-restriction"><span class="header-section-number">32.1.2</span> Exogeneity (Exclusion Restriction)</a></li>
  </ul>
</li>
  <li><a href="#two-stage-least-squares-2sls" id="toc-two-stage-least-squares-2sls" class="nav-link" data-scroll-target="#two-stage-least-squares-2sls"><span class="header-section-number">32.2</span> Two-Stage Least Squares (2SLS)</a></li>
  <li>
<a href="#identification" id="toc-identification" class="nav-link" data-scroll-target="#identification"><span class="header-section-number">32.3</span> Identification</a>
  <ul class="collapse">
<li><a href="#exactly-identified-models" id="toc-exactly-identified-models" class="nav-link" data-scroll-target="#exactly-identified-models"><span class="header-section-number">32.3.1</span> Exactly Identified Models</a></li>
  <li><a href="#overidentified-models" id="toc-overidentified-models" class="nav-link" data-scroll-target="#overidentified-models"><span class="header-section-number">32.3.2</span> Overidentified Models</a></li>
  <li><a href="#underidentified-models" id="toc-underidentified-models" class="nav-link" data-scroll-target="#underidentified-models"><span class="header-section-number">32.3.3</span> Underidentified Models</a></li>
  </ul>
</li>
  <li>
<a href="#multiple-instruments-and-multiple-endogenous-variables" id="toc-multiple-instruments-and-multiple-endogenous-variables" class="nav-link" data-scroll-target="#multiple-instruments-and-multiple-endogenous-variables"><span class="header-section-number">32.4</span> Multiple Instruments and Multiple Endogenous Variables</a>
  <ul class="collapse">
<li><a href="#multiple-instruments" id="toc-multiple-instruments" class="nav-link" data-scroll-target="#multiple-instruments"><span class="header-section-number">32.4.1</span> Multiple Instruments</a></li>
  <li><a href="#multiple-endogenous-variables" id="toc-multiple-endogenous-variables" class="nav-link" data-scroll-target="#multiple-endogenous-variables"><span class="header-section-number">32.4.2</span> Multiple Endogenous Variables</a></li>
  </ul>
</li>
  <li>
<a href="#weak-instruments" id="toc-weak-instruments" class="nav-link" data-scroll-target="#weak-instruments"><span class="header-section-number">32.5</span> Weak Instruments</a>
  <ul class="collapse">
<li><a href="#consequences-of-weak-instruments" id="toc-consequences-of-weak-instruments" class="nav-link" data-scroll-target="#consequences-of-weak-instruments"><span class="header-section-number">32.5.1</span> Consequences of Weak Instruments</a></li>
  <li><a href="#detecting-weak-instruments" id="toc-detecting-weak-instruments" class="nav-link" data-scroll-target="#detecting-weak-instruments"><span class="header-section-number">32.5.2</span> Detecting Weak Instruments</a></li>
  <li><a href="#improving-instrument-strength" id="toc-improving-instrument-strength" class="nav-link" data-scroll-target="#improving-instrument-strength"><span class="header-section-number">32.5.3</span> Improving Instrument Strength</a></li>
  </ul>
</li>
  <li>
<a href="#testing-for-endogeneity" id="toc-testing-for-endogeneity" class="nav-link" data-scroll-target="#testing-for-endogeneity"><span class="header-section-number">32.6</span> Testing for Endogeneity</a>
  <ul class="collapse">
<li><a href="#the-intuition" id="toc-the-intuition" class="nav-link" data-scroll-target="#the-intuition"><span class="header-section-number">32.6.1</span> The Intuition</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results"><span class="header-section-number">32.6.2</span> Interpreting the Results</a></li>
  </ul>
</li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together"><span class="header-section-number">32.7</span> Putting It All Together</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">32.8</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/termehs/found-stats/edit/main/regression/iv-est.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/termehs/found-stats/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../regression/reg-framework.html">Regression Analysis</a></li><li class="breadcrumb-item"><a href="../regression/iv-est.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Instrumental Variables Estimation</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-iv" class="quarto-section-identifier"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Instrumental Variables Estimation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In the previous chapter, we introduced the <strong>zero conditional mean assumption</strong>,</p>
<p><span class="math display">\[
E(\varepsilon \mid X_1, X_2, \ldots, X_K) = 0,
\]</span></p>
<p>and discussed why it is fundamental for the ordinary least squares (OLS) estimator to produce unbiased and consistent estimates. We also saw that this assumption is violated when one or more explanatory variables are <strong>endogenous</strong>, meaning they are correlated with the error term. Endogeneity can arise through omitted variables, simultaneity (or reverse causality), and measurement error, and it prevents OLS from recovering the true causal effect of an explanatory variable.</p>
<p>In many empirical applications, however, endogeneity is unavoidable. For example, more educated individuals may also possess higher innate ability, regions experiencing poor health outcomes may increase public health spending, and survey variables are often measured with error. In each of these situations, the explanatory variable is correlated with unobserved factors that also affect the outcome, making a simple regression analysis unreliable.</p>
<p>This raises an important question:</p>
<blockquote class="blockquote">
<p><em>How can we estimate causal effects when the explanatory variable is endogenous?</em></p>
</blockquote>
<p>One of the most widely used solutions is <strong>instrumental variables (IV) estimation</strong>. Rather than using all of the observed variation in an endogenous explanatory variable, IV estimation exploits only the variation generated by an external variable, known as an <strong>instrument</strong>. If the instrument satisfies certain conditions, this variation is exogenous, allowing us to identify the causal effect even when OLS fails.</p>
<p>The central idea is illustrated in Figure <a href="#fig-iv-intuition" class="quarto-xref">Figure&nbsp;<span>32.1</span></a>. Instead of relying on the potentially endogenous relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, we use a third variable, <span class="math inline">\(z\)</span>, that influences <span class="math inline">\(x\)</span> but has no direct effect on <span class="math inline">\(y\)</span>. By isolating the component of <span class="math inline">\(x\)</span> that is explained by <span class="math inline">\(z\)</span>, we obtain variation that is free from the endogeneity problem.</p>
<div class="cell">
<div id="fig-iv-intuition" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-iv-intuition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="grViz html-widget html-fill-item" id="htmlwidget-52116a5bbc4da741e515" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-52116a5bbc4da741e515">{"x":{"diagram":"\ndigraph {\n\ngraph [layout = dot, rankdir = LR]\n\nnode [\n  shape = circle,\n  style = filled,\n  fillcolor = LightGray,\n  fontsize = 16\n]\n\nz [label = \"z\"]\nx [label = \"x\"]\ny [label = \"y\"]\ne [label = \"ε\"]\n\nz -> x [label = \"relevance\"]\nx -> y [label = \"causal effect\"]\ne -> y\n\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iv-intuition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.1: The basic idea of instrumental variables estimation. The instrument <span class="math inline">\(z\)</span> affects the outcome only indirectly through the endogenous explanatory variable <span class="math inline">\(x\)</span>.
</figcaption></figure>
</div>
</div>
<p>Throughout this chapter, we examine the conditions that make an instrument valid, derive the instrumental variables estimator, and show how it is implemented using <strong>two-stage least squares (2SLS)</strong>. We also discuss practical issues such as identification, weak instruments, and diagnostic tests that help assess whether an IV strategy is credible.</p>
<section id="example-32.1-public-health-expenditure-and-health-outcomes" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-32.1-public-health-expenditure-and-health-outcomes">Example 32.1: Public Health Expenditure and Health Outcomes</h4>
<p>To illustrate the need for instrumental variables, consider a study of the relationship between public health expenditure and health outcomes across a sample of cities. For each city <span class="math inline">\(i\)</span>, suppose we observe</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span>: a measure of public health outcomes, such as the proportion of children suffering from a particular disease;</li>
<li>
<span class="math inline">\(x_i\)</span>: public health expenditure per capita.</li>
</ul>
<p>Our objective is to estimate the regression model</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \varepsilon_i,
\]</span></p>
<p>where <span class="math inline">\(\beta_1\)</span> measures the causal effect of public health expenditure on health outcomes.</p>
<p>Based on economic reasoning, we expect greater investment in public health to improve health outcomes. For example, higher spending may finance vaccination programs, sanitation projects, or improved access to healthcare, thereby reducing the incidence of disease.</p>
<p>At first glance, it might seem sufficient to estimate this relationship using OLS. However, there is an important complication. Public health expenditure is not determined randomly. Cities experiencing poorer health outcomes are likely to increase their health spending in response to disease outbreaks. Consequently, health expenditure and health outcomes are jointly determined.</p>
<p>This reverse causality implies that the explanatory variable <span class="math inline">\(x_i\)</span> is correlated with the error term,</p>
<p><span class="math display">\[
\operatorname{Cov}(x_i,\varepsilon_i) \neq 0,
\]</span></p>
<p>violating the zero conditional mean assumption discussed in the previous chapter. As a result, OLS no longer estimates the causal effect of public health expenditure.</p>
<p>One possible solution is to find another variable that influences public health expenditure but has no direct effect on health outcomes. Suppose we observe</p>
<ul>
<li>
<span class="math inline">\(z_i\)</span>: per capita income in city <span class="math inline">\(i\)</span>.</li>
</ul>
<p>Cities with higher incomes typically have a larger tax base and therefore more resources to spend on public health. Thus, income is likely to be correlated with public health expenditure. At the same time, provided that income does not directly affect health outcomes after accounting for other relevant factors, it affects health only indirectly through public health expenditure.</p>
<p>Figure <a href="#fig-health-iv" class="quarto-xref">Figure&nbsp;<span>32.2</span></a> illustrates this idea.</p>
<div class="cell">
<div id="fig-health-iv" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-health-iv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="grViz html-widget html-fill-item" id="htmlwidget-3b708029a35b4e49af09" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-3b708029a35b4e49af09">{"x":{"diagram":"\ndigraph {\n\ngraph [layout = dot, rankdir = LR]\n\nnode [\nshape = rectangle,\nstyle = rounded,\nfontsize = 15\n]\n\nz [label=\"Per capita\nincome\n(zᵢ)\"]\nx [label=\"Public health\nexpenditure\n(xᵢ)\"]\ny [label=\"Health\noutcomes\n(yᵢ)\"]\nu [label=\"Unobserved\nhealth factors\n(εᵢ)\"]\n\nz -> x\nx -> y\nu -> y\n\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-health-iv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.2: Per capita income (<span class="math inline">\(z_i\)</span>) is used as an instrument for public health expenditure (<span class="math inline">\(x_i\)</span>).
</figcaption></figure>
</div>
</div>
<p>Per capita income therefore provides a source of variation in public health expenditure that is plausibly unrelated to the unobserved determinants of health outcomes. Instrumental variables estimation exploits this exogenous variation to estimate the causal effect of public health expenditure, even though a simple OLS regression cannot.</p>
<p>This example illustrates the central idea of instrumental variables estimation: rather than using all observed variation in the endogenous explanatory variable <span class="math inline">\(x_i\)</span>, we isolate the component of <span class="math inline">\(x_i\)</span> that is explained by an external source of variation, namely the instrument <span class="math inline">\(z_i\)</span>.</p>
</section><section id="what-makes-a-good-instrument" class="level2" data-number="32.1"><h2 data-number="32.1" class="anchored" data-anchor-id="what-makes-a-good-instrument">
<span class="header-section-number">32.1</span> What Makes a Good Instrument?</h2>
<p>The motivating example in the previous section introduced the idea of an instrumental variable. However, not every variable can serve as a valid instrument. For an instrument to identify a causal effect, it must satisfy <strong>two fundamental conditions</strong>:</p>
<ol type="1">
<li>
<strong>Relevance</strong>: the instrument must be related to the endogenous explanatory variable.</li>
<li>
<strong>Exogeneity (or the exclusion restriction)</strong>: the instrument must not affect the outcome except through the explanatory variable.</li>
</ol>
<p>Both conditions are essential. If either one fails, the instrumental variables estimator is generally inconsistent and cannot be interpreted as measuring a causal effect.</p>
<p>Figure <a href="#fig-valid-iv" class="quarto-xref">Figure&nbsp;<span>32.3</span></a> summarizes these relationships.</p>
<div class="cell">
<div id="fig-valid-iv" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-valid-iv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="grViz html-widget html-fill-item" id="htmlwidget-d5bb21db184a1cc848eb" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-d5bb21db184a1cc848eb">{"x":{"diagram":"\ndigraph {\n\ngraph [layout = dot, rankdir = LR]\n\nnode [\nshape = rectangle,\nstyle = rounded,\nfontsize = 15\n]\n\nz [label=\"Instrument\n(zᵢ)\"]\nx [label=\"Endogenous\nvariable\n(xᵢ)\"]\ny [label=\"Outcome\n(yᵢ)\"]\ne [label=\"Structural\nerror\n(εᵢ)\"]\n\nz -> x [label=\"Relevance\"]\nx -> y [label=\"Causal effect\"]\ne -> y\n\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-valid-iv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.3: A valid instrument influences the outcome only indirectly through the endogenous explanatory variable.
</figcaption></figure>
</div>
</div>
<p>Notice that the instrument affects the outcome only through the explanatory variable. There is no direct path from the instrument to the outcome, nor is the instrument related to the structural error term. These are precisely the conditions required for instrumental variables estimation to recover the causal effect.</p>
<section id="relevance" class="level3" data-number="32.1.1"><h3 data-number="32.1.1" class="anchored" data-anchor-id="relevance">
<span class="header-section-number">32.1.1</span> Relevance</h3>
<p>The <strong>relevance condition</strong> requires that the instrument be correlated with the endogenous explanatory variable. In other words, changes in the instrument must induce changes in the explanatory variable.</p>
<p>Formally,</p>
<p><span class="math display">\[
\operatorname{Cov}(z_i,x_i)\neq0.
\]</span></p>
<p>Returning to our public health example, per capita income is a plausible instrument because wealthier cities generally have a larger tax base and can therefore spend more on public health. Income is expected to explain at least some of the variation in public health expenditure.</p>
<p>If the instrument has little or no relationship with the explanatory variable, it contains no useful information for identifying the causal effect. Such instruments are known as <strong>weak instruments</strong>, and they can lead to highly unreliable estimates. We discuss this issue in more detail later in the chapter.</p>
</section><section id="exogeneity-exclusion-restriction" class="level3" data-number="32.1.2"><h3 data-number="32.1.2" class="anchored" data-anchor-id="exogeneity-exclusion-restriction">
<span class="header-section-number">32.1.2</span> Exogeneity (Exclusion Restriction)</h3>
<p>The second requirement is the <strong>exogeneity</strong> or <strong>exclusion restriction</strong>. It states that the instrument must influence the outcome only through its effect on the endogenous explanatory variable.</p>
<p>Mathematically,</p>
<p><span class="math display">\[
\operatorname{Cov}(z_i,\varepsilon_i)=0.
\]</span></p>
<p>This assumption means that the instrument must not be correlated with any unobserved factors affecting the outcome variable.</p>
<p>In the public health example, this requires that per capita income affects health outcomes only through public health expenditure. If income also directly improves health—for example, because wealthier individuals can purchase better nutrition or healthcare independently of public spending—then income would violate the exclusion restriction and would no longer be a valid instrument.</p>
<p>Unlike the relevance condition, which can be assessed empirically, the exclusion restriction cannot usually be tested directly. Instead, its validity depends on careful subject-matter knowledge of the application being studied. Consequently, the credibility of an instrumental variables analysis rests not only on statistical evidence but also on the plausibility of the proposed instrument.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Key Point">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Point
</div>
</div>
<div class="callout-body-container callout-body">
<p>A valid instrument must satisfy <strong>both</strong> conditions simultaneously.</p>
<ul>
<li>
<strong>Relevance</strong> ensures that the instrument contains useful information about the endogenous explanatory variable.</li>
<li>
<strong>Exogeneity</strong> ensures that this information is free from the endogeneity problem affecting the original regression.</li>
</ul>
<p>An instrument that satisfies only one of these conditions is <strong>not</strong> a valid instrument.</p>
</div>
</div>
</section></section><section id="two-stage-least-squares-2sls" class="level2" data-number="32.2"><h2 data-number="32.2" class="anchored" data-anchor-id="two-stage-least-squares-2sls">
<span class="header-section-number">32.2</span> Two-Stage Least Squares (2SLS)</h2>
<p>Instrumental variables estimation is most commonly implemented using the <strong>two-stage least squares (2SLS)</strong> estimator. As its name suggests, the method consists of two ordinary least squares (OLS) regressions. The first regression isolates the exogenous component of the endogenous explanatory variable, while the second regression uses this exogenous variation to estimate the causal effect on the outcome.</p>
<p>Recall that the problem with OLS is that the explanatory variable <span class="math inline">\(x_i\)</span> is correlated with the structural error term,</p>
<p><span class="math display">\[
\operatorname{Cov}(x_i,\varepsilon_i)\neq0,
\]</span></p>
<p>which violates the zero conditional mean assumption. Consequently, the observed variation in <span class="math inline">\(x_i\)</span> contains two distinct components:</p>
<ul>
<li>
<strong>Exogenous variation</strong>, which is unrelated to the error term and can be used to estimate the causal effect.</li>
<li>
<strong>Endogenous variation</strong>, which is correlated with the error term and leads to biased and inconsistent OLS estimates.</li>
</ul>
<p>The objective of 2SLS is to separate these two sources of variation and retain only the exogenous component.</p>
<p>Suppose that, in addition to observing the outcome variable <span class="math inline">\(y_i\)</span> and the endogenous explanatory variable <span class="math inline">\(x_i\)</span>, we also observe an instrumental variable <span class="math inline">\(z_i\)</span>. If the instrument is valid, it provides a source of variation in <span class="math inline">\(x_i\)</span> that is unrelated to the structural error term <span class="math inline">\(\varepsilon_i\)</span>. The first stage of the procedure exploits this relationship by regressing <span class="math inline">\(x_i\)</span> on the instrument,</p>
<p><span class="math display">\[
x_i=\gamma_0+\gamma_1z_i+v_i,
\]</span></p>
<p>where <span class="math inline">\(\gamma_0\)</span> and <span class="math inline">\(\gamma_1\)</span> are unknown parameters and <span class="math inline">\(v_i\)</span> represents the remaining variation in <span class="math inline">\(x_i\)</span> that is not explained by the instrument.</p>
<p>This regression is referred to as the <strong>first-stage regression</strong>. Its purpose is not to estimate the causal effect of interest, but rather to identify the component of <span class="math inline">\(x_i\)</span> that is explained by the instrument. From this regression we obtain the fitted values</p>
<p><span class="math display">\[
\hat{x}_i=\hat{\gamma}_0+\hat{\gamma}_1z_i,
\]</span></p>
<p>which represent the variation in <span class="math inline">\(x_i\)</span> attributable to the instrument.</p>
<p>If the instrument satisfies the relevance and exclusion assumptions discussed earlier, the fitted values <span class="math inline">\(\hat{x}_i\)</span> are uncorrelated with the structural error term. They therefore provide an exogenous version of the original explanatory variable.</p>
<p>In the <strong>second stage</strong>, the original endogenous variable is replaced by its fitted values, and the regression model is estimated using OLS:</p>
<p><span class="math display">\[
y_i=\beta_0+\beta_1\hat{x}_i+\varepsilon_i.
\]</span></p>
<p>The estimated coefficient <span class="math inline">\(\hat{\beta}_1\)</span> measures the effect of the component of <span class="math inline">\(x_i\)</span> that is generated by the instrument. Because this variation is exogenous, the resulting estimator is consistent for the true causal effect.</p>
<p>The two-stage procedure is illustrated in Figure <a href="#fig-twostage" class="quarto-xref">Figure&nbsp;<span>32.4</span></a>.</p>
<div class="cell">
<div id="fig-twostage" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-twostage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="grViz html-widget html-fill-item" id="htmlwidget-5ce7816fd91e121e8cbc" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-5ce7816fd91e121e8cbc">{"x":{"diagram":"\ndigraph {\n\ngraph [layout = dot, rankdir = LR]\n\nnode [\nshape = rectangle,\nstyle = rounded,\nfontsize = 15\n]\n\nz [label=\"Instrument\nzᵢ\"]\nx [label=\"Endogenous\nvariable\nxᵢ\"]\nxh [label=\"Predicted\nvalue\nx̂ᵢ\"]\ny [label=\"Outcome\nyᵢ\"]\n\nz -> x [label=\"Stage 1\"]\nx -> xh [label=\"Fitted values\"]\nxh -> y [label=\"Stage 2\"]\n\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-twostage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.4: The logic of two-stage least squares (2SLS).
</figcaption></figure>
</div>
</div>
<p>The intuition behind 2SLS is straightforward. The observed explanatory variable <span class="math inline">\(x_i\)</span> contains both exogenous and endogenous variation. The first stage uses the instrument to extract only the exogenous component, represented by <span class="math inline">\(\hat{x}_i\)</span>. The second stage then estimates the relationship between this exogenous component and the outcome variable. In this way, 2SLS removes the source of bias that makes ordinary least squares unreliable when the explanatory variable is endogenous.</p>
<div class="callout callout-style-default callout-note callout-titled" title="A Mathematical Derivation of the IV Estimator">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A Mathematical Derivation of the IV Estimator
</div>
</div>
<div class="callout-body-container callout-body">
<p>The two-stage least squares algorithm provides an intuitive way to estimate an instrumental variables model. In the special case of <strong>one endogenous explanatory variable</strong> and <strong>one instrument</strong>, however, the estimator can also be derived directly using properties of covariance.</p>
<p>Starting from the structural model,</p>
<p><span class="math display">\[
y_i=\beta_0+\beta_1x_i+\varepsilon_i,
\]</span></p>
<p>take the covariance of both sides with the instrument <span class="math inline">\(z_i\)</span>:</p>
<p><span class="math display">\[
\operatorname{Cov}(y_i,z_i)
=
\operatorname{Cov}(\beta_0+\beta_1x_i+\varepsilon_i,z_i).
\]</span></p>
<p>Using the linearity of covariance,</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{Cov}(y_i,z_i)
&amp;=
\operatorname{Cov}(\beta_0,z_i)
+\operatorname{Cov}(\beta_1x_i,z_i)
+\operatorname{Cov}(\varepsilon_i,z_i) \\
&amp;=
0+\beta_1\operatorname{Cov}(x_i,z_i)+0.
\end{aligned}
\]</span></p>
<p>The first term is zero because <span class="math inline">\(\beta_0\)</span> is a constant, while the final term is zero because a valid instrument satisfies the exclusion restriction,</p>
<p><span class="math display">\[
\operatorname{Cov}(z_i,\varepsilon_i)=0.
\]</span></p>
<p>Rearranging gives</p>
<p><span class="math display">\[
\beta_1=
\frac{\operatorname{Cov}(y_i,z_i)}
{\operatorname{Cov}(x_i,z_i)}.
\]</span></p>
<p>In practice, the population covariances are unknown and are replaced by sample covariances,</p>
<p><span class="math display">\[
\hat{\beta}_{IV}
=
\frac{\widehat{\operatorname{Cov}}(y,z)}
{\widehat{\operatorname{Cov}}(x,z)}.
\]</span></p>
<p>This expression is known as the <strong>instrumental variables (IV) estimator</strong> or, in this simple setting, the <strong>Wald estimator</strong>. Although it looks quite different from the two-stage least squares algorithm, the two approaches produce exactly the same estimate when there is a single endogenous explanatory variable and a single instrument. The 2SLS formulation is preferred because it extends naturally to models with multiple instruments and multiple endogenous explanatory variables.</p>
</div>
</div>
</section><section id="identification" class="level2" data-number="32.3"><h2 data-number="32.3" class="anchored" data-anchor-id="identification">
<span class="header-section-number">32.3</span> Identification</h2>
<p>So far, we have considered the simplest possible instrumental variables model, consisting of a single endogenous explanatory variable and a single instrument. In this setting, the two-stage least squares estimator is straightforward to compute, and the causal effect can be identified provided that the instrument satisfies the relevance and exclusion conditions.</p>
<p>In practice, however, empirical applications are often more complex. A model may contain several endogenous explanatory variables, multiple potential instruments, or both. Before an IV model can be estimated, we must determine whether there is sufficient information to identify all of the causal effects of interest.</p>
<p>This leads to the concept of <strong>identification</strong>.</p>
<p>Suppose a regression model contains</p>
<ul>
<li>
<span class="math inline">\(K_e\)</span> endogenous explanatory variables, and</li>
<li>
<span class="math inline">\(L\)</span> instrumental variables.</li>
</ul>
<p>The relationship between <span class="math inline">\(K_e\)</span> and <span class="math inline">\(L\)</span> determines whether the model is identified.</p>
<section id="exactly-identified-models" class="level3" data-number="32.3.1"><h3 data-number="32.3.1" class="anchored" data-anchor-id="exactly-identified-models">
<span class="header-section-number">32.3.1</span> Exactly Identified Models</h3>
<p>A model is <strong>exactly identified</strong> (or <strong>just identified</strong>) when the number of instruments equals the number of endogenous explanatory variables,</p>
<p><span class="math display">\[
L = K_e.
\]</span></p>
<p>In this case, there are just enough instruments to identify all of the endogenous variables in the model. The examples considered so far in this chapter fall into this category, where</p>
<ul>
<li>
<span class="math inline">\(K_e = 1\)</span> (one endogenous explanatory variable, <span class="math inline">\(x_i\)</span>), and</li>
<li>
<span class="math inline">\(L = 1\)</span> (one instrument, <span class="math inline">\(z_i\)</span>).</li>
</ul>
<p>Exactly identified models can be estimated using two-stage least squares, but because there is only one instrument available for each endogenous variable, there is no way to empirically assess whether the instruments satisfy the exclusion restriction.</p>
</section><section id="overidentified-models" class="level3" data-number="32.3.2"><h3 data-number="32.3.2" class="anchored" data-anchor-id="overidentified-models">
<span class="header-section-number">32.3.2</span> Overidentified Models</h3>
<p>A model is <strong>overidentified</strong> when there are more instruments than endogenous explanatory variables,</p>
<p><span class="math display">\[
L &gt; K_e.
\]</span></p>
<p>In this situation, the model contains more information than is strictly necessary for identification. This is often desirable because additional valid instruments can improve the efficiency of the estimator by exploiting more exogenous variation.</p>
<p>An important advantage of overidentified models is that they allow the validity of the instruments to be assessed using <strong>overidentification tests</strong>, such as the Sargan or Hansen <span class="math inline">\(J\)</span> test, which are discussed later in the chapter.</p>
<p>However, adding instruments is beneficial only if they are both <strong>relevant</strong> and <strong>valid</strong>. Including weak or invalid instruments may reduce the precision and reliability of the estimates.</p>
</section><section id="underidentified-models" class="level3" data-number="32.3.3"><h3 data-number="32.3.3" class="anchored" data-anchor-id="underidentified-models">
<span class="header-section-number">32.3.3</span> Underidentified Models</h3>
<p>A model is <strong>underidentified</strong> when there are fewer instruments than endogenous explanatory variables,</p>
<p><span class="math display">\[
L &lt; K_e.
\]</span></p>
<p>In this case, there is insufficient exogenous information to disentangle the endogenous variation from the exogenous variation in every explanatory variable. Consequently, the causal effects cannot be identified, and the model cannot be estimated using instrumental variables.</p>
<p>The only solution is to find additional valid instruments.</p>
<p>Figure <a href="#fig-identification" class="quarto-xref">Figure&nbsp;<span>32.5</span></a> summarizes the three possible cases.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-identification" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-identification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="iv-est_files/figure-html/fig-identification-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-identification-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.5: Identification depends on the relationship between the number of endogenous explanatory variables (<span class="math inline">\(K_e\)</span>) and the number of available instruments (<span class="math inline">\(L\)</span>).
</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Key Point">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Point
</div>
</div>
<div class="callout-body-container callout-body">
<p>An instrumental variables model can be estimated only if there are <strong>at least as many valid instruments as endogenous explanatory variables</strong>.</p>
<ul>
<li>If <span class="math inline">\(L &lt; K_e\)</span>, the model is <strong>underidentified</strong> and cannot be estimated.</li>
<li>If <span class="math inline">\(L = K_e\)</span>, the model is <strong>exactly identified</strong>.</li>
<li>If <span class="math inline">\(L &gt; K_e\)</span>, the model is <strong>overidentified</strong>, allowing additional efficiency and the possibility of testing the validity of the instruments.</li>
</ul>
</div>
</div>
<p>Now that we understand the conditions for identification, the next question is how two-stage least squares is implemented when a model contains multiple instruments or multiple endogenous explanatory variables. Fortunately, the estimation procedure is a straightforward extension of the two-stage least squares algorithm introduced earlier.</p>
</section></section><section id="multiple-instruments-and-multiple-endogenous-variables" class="level2" data-number="32.4"><h2 data-number="32.4" class="anchored" data-anchor-id="multiple-instruments-and-multiple-endogenous-variables">
<span class="header-section-number">32.4</span> Multiple Instruments and Multiple Endogenous Variables</h2>
<p>The previous sections focused on the simplest IV model, consisting of one endogenous explanatory variable and one instrument. In practice, however, empirical models often contain several instruments, several endogenous explanatory variables, or both.</p>
<p>Fortunately, extending two-stage least squares to these settings is straightforward. The underlying idea remains exactly the same: each endogenous explanatory variable is replaced by the component that can be explained by the available instruments.</p>
<section id="multiple-instruments" class="level3" data-number="32.4.1"><h3 data-number="32.4.1" class="anchored" data-anchor-id="multiple-instruments">
<span class="header-section-number">32.4.1</span> Multiple Instruments</h3>
<p>Suppose there is one endogenous explanatory variable, <span class="math inline">\(x_i\)</span>, and <span class="math inline">\(L\)</span> valid instruments,</p>
<p><span class="math display">\[
z_{i1},z_{i2},\ldots,z_{iL}.
\]</span></p>
<p>Instead of regressing <span class="math inline">\(x_i\)</span> on a single instrument, the first-stage regression becomes</p>
<p><span class="math display">\[
x_i
=
\gamma_0
+
\gamma_1z_{i1}
+\cdots+
\gamma_Lz_{iL}
+
v_i.
\]</span></p>
<p>The fitted values,</p>
<p><span class="math display">\[
\hat{x}_i,
\]</span></p>
<p>replace <span class="math inline">\(x_i\)</span> in the second-stage regression,</p>
<p><span class="math display">\[
y_i
=
\beta_0
+
\beta_1\hat{x}_i
+
\varepsilon_i.
\]</span></p>
</section><section id="multiple-endogenous-variables" class="level3" data-number="32.4.2"><h3 data-number="32.4.2" class="anchored" data-anchor-id="multiple-endogenous-variables">
<span class="header-section-number">32.4.2</span> Multiple Endogenous Variables</h3>
<p>If the model contains several endogenous explanatory variables, a separate first-stage regression is estimated for each one.</p>
<p>For example, if both <span class="math inline">\(x_{i1}\)</span> and <span class="math inline">\(x_{i2}\)</span> are endogenous,</p>
<p><span class="math display">\[
x_{i1}
=
\gamma_{10}
+\gamma_{11}z_{i1}
+\cdots+
\gamma_{1L}z_{iL}
+
v_{i1},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
x_{i2}
=
\gamma_{20}
+\gamma_{21}z_{i1}
+\cdots+
\gamma_{2L}z_{iL}
+
v_{i2}.
\]</span></p>
<p>The resulting fitted values, <span class="math inline">\(\hat{x}_{i1}\)</span> and <span class="math inline">\(\hat{x}_{i2}\)</span>, are then used in the second-stage regression.</p>
<p>Although the notation becomes more involved, the estimation procedure is identical to the single-variable case.</p>
<p>Regardless of the number of instruments, the quality of the estimates depends critically on how strongly the instruments explain the endogenous explanatory variables. We now turn to the important issue of weak instruments.</p>
</section></section><section id="weak-instruments" class="level2" data-number="32.5"><h2 data-number="32.5" class="anchored" data-anchor-id="weak-instruments">
<span class="header-section-number">32.5</span> Weak Instruments</h2>
<p>Throughout this chapter we have assumed that the instruments are sufficiently related to the endogenous explanatory variables to identify the causal effect. In practice, however, not all instruments are equally informative. Some instruments explain only a very small proportion of the variation in the endogenous variables. These are known as <strong>weak instruments</strong>.</p>
<p>Weak instruments are problematic because they provide little information about the exogenous component of the endogenous explanatory variable. As a result, the first-stage regression produces fitted values that are only weakly related to the original explanatory variable, making the second-stage estimates unstable and imprecise.</p>
<p>To see why this occurs, recall the instrumental variables estimator for the simple case of one endogenous explanatory variable and one instrument:</p>
<p><span class="math display">\[
\hat{\beta}_{IV}
=
\frac{\widehat{\operatorname{Cov}}(y,z)}
{\widehat{\operatorname{Cov}}(x,z)}.
\]</span></p>
<p>The denominator,</p>
<p><span class="math display">\[
\widehat{\operatorname{Cov}}(x,z),
\]</span></p>
<p>measures the strength of the relationship between the instrument and the endogenous explanatory variable. If this covariance is close to zero, even small changes from one sample to another can produce large changes in the estimated coefficient. Consequently, the IV estimator becomes highly variable and statistical inference becomes unreliable.</p>
<section id="consequences-of-weak-instruments" class="level3" data-number="32.5.1"><h3 data-number="32.5.1" class="anchored" data-anchor-id="consequences-of-weak-instruments">
<span class="header-section-number">32.5.1</span> Consequences of Weak Instruments</h3>
<p>Weak instruments can lead to several problems:</p>
<ul>
<li>estimates with large standard errors;</li>
<li>confidence intervals that are unnecessarily wide;</li>
<li>hypothesis tests with incorrect rejection rates;</li>
<li>estimates that may be substantially biased, particularly in small samples.</li>
</ul>
<p>Although two-stage least squares is consistent when the instrument is valid, this large-sample result relies on the instrument providing a sufficiently strong source of exogenous variation. When instruments are weak, the usual large-sample approximations may perform poorly, even in relatively large datasets.</p>
</section><section id="detecting-weak-instruments" class="level3" data-number="32.5.2"><h3 data-number="32.5.2" class="anchored" data-anchor-id="detecting-weak-instruments">
<span class="header-section-number">32.5.2</span> Detecting Weak Instruments</h3>
<p>The most common diagnostic for weak instruments is the <strong>first-stage F-statistic</strong>.</p>
<p>Recall that the first-stage regression relates the endogenous explanatory variable to the instruments. If the instruments are useful, they should explain a substantial amount of the variation in the endogenous variable.</p>
<p>Consequently, we test the null hypothesis that the coefficients on all instruments are jointly equal to zero:</p>
<p><span class="math display">\[
H_0:
\gamma_1
=
\gamma_2
=
\cdots
=
\gamma_L
=
0.
\]</span></p>
<p>If this null hypothesis cannot be rejected, the instruments have little explanatory power and are likely to be weak.</p>
<p>As a practical rule of thumb, a first-stage F-statistic smaller than <strong>10</strong> is often taken as evidence of potentially weak instruments. Although this threshold is not a formal statistical rule, it is widely used as a simple diagnostic in applied econometric analysis.</p>
<p>When there is only one instrument, the first-stage regression contains a single explanatory variable. In this case, the familiar relationship between the <span class="math inline">\(t\)</span>-test and the <span class="math inline">\(F\)</span>-test applies,</p>
<p><span class="math display">\[
F=t^2,
\]</span></p>
<p>so either statistic can be used to assess instrument relevance.</p>
</section><section id="improving-instrument-strength" class="level3" data-number="32.5.3"><h3 data-number="32.5.3" class="anchored" data-anchor-id="improving-instrument-strength">
<span class="header-section-number">32.5.3</span> Improving Instrument Strength</h3>
<p>If the first-stage regression suggests that the instruments are weak, several approaches may improve the analysis:</p>
<ul>
<li>search for instruments that are more strongly related to the endogenous explanatory variable;</li>
<li>remove instruments that contribute little explanatory power;</li>
<li>reconsider the research design and whether a convincing instrument exists.</li>
</ul>
<p>Simply adding more instruments is not necessarily beneficial. Additional instruments increase precision only if they are both <strong>valid</strong> and <strong>strong</strong>. Including many weak instruments can actually worsen the performance of the estimator.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Key Point">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Point
</div>
</div>
<div class="callout-body-container callout-body">
<p>A valid instrument must satisfy <strong>both</strong> the relevance and exclusion conditions. An instrument that satisfies the exclusion restriction but is only weakly correlated with the endogenous explanatory variable is still a poor instrument because it provides too little information to estimate the causal effect reliably.</p>
<p>For this reason, researchers should always examine the first-stage regression before interpreting the results of an instrumental variables analysis.</p>
</div>
</div>
</section></section><section id="testing-for-endogeneity" class="level2" data-number="32.6"><h2 data-number="32.6" class="anchored" data-anchor-id="testing-for-endogeneity">
<span class="header-section-number">32.6</span> Testing for Endogeneity</h2>
<p>Instrumental variables estimation is designed to address endogeneity. However, if the explanatory variables are actually exogenous, ordinary least squares (OLS) remains the preferred estimator because it is generally more efficient than two-stage least squares. Consequently, before relying on an IV model, it is useful to determine whether endogeneity is present.</p>
<p>One commonly used diagnostic is the <strong>Wu–Hausman test</strong>. The test evaluates whether the explanatory variable is endogenous by comparing the information contained in the original explanatory variable with that contained in the instrumental variables.</p>
<section id="the-intuition" class="level3" data-number="32.6.1"><h3 data-number="32.6.1" class="anchored" data-anchor-id="the-intuition">
<span class="header-section-number">32.6.1</span> The Intuition</h3>
<p>Recall that the first-stage regression decomposes the endogenous explanatory variable into two components:</p>
<ul>
<li>the variation explained by the instruments (the exogenous component), and</li>
<li>the remaining unexplained variation.</li>
</ul>
<p>If the explanatory variable is truly exogenous, then this unexplained component should not be related to the structural error term in the original regression model.</p>
<p>On the other hand, if the unexplained component is correlated with the outcome after controlling for the explanatory variable, this provides evidence that the explanatory variable is endogenous.</p>
<p>The Wu–Hausman test formalizes this idea.</p>
<section id="step-1-estimate-the-first-stage-regression" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="step-1-estimate-the-first-stage-regression">Step 1: Estimate the First-Stage Regression</h4>
<p>Estimate the first-stage regression,</p>
<p><span class="math display">\[
x_i
=
\gamma_0
+
\gamma_1z_{i1}
+
\cdots
+
\gamma_Lz_{iL}
+
v_i,
\]</span></p>
<p>and save the residuals,</p>
<p><span class="math display">\[
\hat{v}_i.
\]</span></p>
<p>These residuals represent the component of the explanatory variable that cannot be explained by the instruments.</p>
</section><section id="step-2-estimate-an-augmented-regression" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="step-2-estimate-an-augmented-regression">Step 2: Estimate an Augmented Regression</h4>
<p>Next, estimate the original regression model, but include the first-stage residuals as an additional explanatory variable:</p>
<p><span class="math display">\[
y_i
=
\beta_0
+
\beta_1x_i
+
\delta\hat{v}_i
+
\varepsilon_i.
\]</span></p>
<p>The coefficient <span class="math inline">\(\delta\)</span> measures whether the unexplained component of <span class="math inline">\(x_i\)</span> is related to the outcome after controlling for <span class="math inline">\(x_i\)</span> itself.</p>
</section><section id="step-3-test-the-residual-coefficient" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="step-3-test-the-residual-coefficient">Step 3: Test the Residual Coefficient</h4>
<p>The null hypothesis is</p>
<p><span class="math display">\[
H_0:\delta=0,
\]</span></p>
<p>which states that the explanatory variable is exogenous.</p>
<p>The alternative hypothesis is</p>
<p><span class="math display">\[
H_A:\delta\neq0,
\]</span></p>
<p>which implies that the explanatory variable is endogenous.</p>
<p>The significance of <span class="math inline">\(\delta\)</span> is evaluated using the usual <span class="math inline">\(t\)</span>-test.</p>
</section></section><section id="interpreting-the-results" class="level3" data-number="32.6.2"><h3 data-number="32.6.2" class="anchored" data-anchor-id="interpreting-the-results">
<span class="header-section-number">32.6.2</span> Interpreting the Results</h3>
<p>The interpretation of the Wu–Hausman test is straightforward.</p>
<ul>
<li><p>If the coefficient on <span class="math inline">\(\hat{v}_i\)</span> is <strong>not statistically significant</strong>, we fail to reject the null hypothesis. There is little evidence that the explanatory variable is endogenous, and OLS is generally preferred because it is more efficient.</p></li>
<li><p>If the coefficient on <span class="math inline">\(\hat{v}_i\)</span> <strong>is statistically significant</strong>, we reject the null hypothesis and conclude that the explanatory variable is endogenous. In this case, instrumental variables estimation is preferred because OLS is no longer consistent.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpreting the Wu–Hausman Test">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting the Wu–Hausman Test
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Wu–Hausman test helps determine whether instrumental variables estimation is necessary.</p>
<ul>
<li>
<strong>Fail to reject <span class="math inline">\(H_0\)</span></strong>: little evidence of endogeneity; OLS is appropriate.</li>
<li>
<strong>Reject <span class="math inline">\(H_0\)</span></strong>: evidence of endogeneity; IV estimation should be used.</li>
</ul>
<p>Like any hypothesis test, the Wu–Hausman test should be interpreted alongside subject-matter knowledge of the application. A statistically significant result does not validate the instrument itself; it only provides evidence that the explanatory variable is endogenous.</p>
</div>
</div>
</section></section><section id="putting-it-all-together" class="level2" data-number="32.7"><h2 data-number="32.7" class="anchored" data-anchor-id="putting-it-all-together">
<span class="header-section-number">32.7</span> Putting It All Together</h2>
<p>Instrumental variables estimation provides a powerful solution when ordinary least squares cannot recover a causal effect because one or more explanatory variables are endogenous. However, a successful IV analysis involves more than simply estimating a two-stage least squares model. Before interpreting the results, researchers should carefully assess whether the assumptions underlying the analysis are reasonable.</p>
<p>A typical instrumental variables analysis consists of the following steps.</p>
<ol type="1">
<li>
<p><strong>Identify the source of endogeneity.</strong></p>
<p>Explain why the explanatory variable is likely to be correlated with the structural error term. Common sources include omitted variables, simultaneity, and measurement error.</p>
</li>
<li>
<p><strong>Propose a valid instrument.</strong></p>
<p>The instrument should satisfy two conditions:</p>
<ul>
<li>
<strong>Relevance:</strong> it must be correlated with the endogenous explanatory variable.</li>
<li>
<strong>Exogeneity (exclusion restriction):</strong> it must affect the outcome only through the endogenous explanatory variable.</li>
</ul>
</li>
<li>
<p><strong>Estimate the first-stage regression.</strong></p>
<p>Regress each endogenous explanatory variable on the available instruments. This step produces the fitted values that represent the exogenous component of the explanatory variables.</p>
</li>
<li>
<p><strong>Assess instrument strength.</strong></p>
<p>Examine the first-stage regression to ensure that the instruments are sufficiently related to the endogenous explanatory variables. In practice, researchers commonly inspect the first-stage <span class="math inline">\(F\)</span>-statistic as a diagnostic for weak instruments.</p>
</li>
<li>
<p><strong>Estimate the second-stage regression.</strong></p>
<p>Replace each endogenous explanatory variable with its fitted values and estimate the structural model using two-stage least squares.</p>
</li>
<li>
<p><strong>Interpret the results.</strong></p>
<p>If the instruments are valid, the estimated coefficients measure the causal effect of the endogenous explanatory variables on the outcome.</p>
</li>
<li>
<p><strong>Perform diagnostic tests.</strong></p>
<p>Where appropriate, additional diagnostic tests can be used to evaluate the assumptions underlying the IV model. These include tests for endogeneity, such as the Wu–Hausman test, and, in overidentified models, tests of instrument validity such as the Sargan or Hansen <span class="math inline">\(J\)</span> test.</p>
</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="A Checklist for Instrumental Variables Estimation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A Checklist for Instrumental Variables Estimation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before interpreting the results of an IV analysis, ask yourself:</p>
<ul>
<li>Why is the explanatory variable endogenous?</li>
<li>Is there a convincing argument that the proposed instrument satisfies the exclusion restriction?</li>
<li>Is the instrument strongly related to the endogenous explanatory variable?</li>
<li>Is the model identified?</li>
<li>Do the diagnostic tests support the validity of the IV specification?</li>
</ul>
<p>Answering these questions is often more important than obtaining a statistically significant coefficient estimate.</p>
</div>
</div>
<p>In the next section, we illustrate each of these steps using a complete instrumental variables analysis.</p>
<section id="example-32.2-cigarette-prices-on-cigarette-consumption" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-32.2-cigarette-prices-on-cigarette-consumption">Example 32.2: Cigarette Prices on Cigarette Consumption</h4>
<p>In this example, we estimate the effect of cigarette prices on cigarette consumption. The outcome variable is cigarette sales per capita, and the potentially endogenous explanatory variable is cigarette price.</p>
<p>The concern is that cigarette prices may be endogenous because prices are affected by both supply and demand conditions. To address this, we use the cigarette tax as an instrument for price.</p>
<p>The structural model of interest is</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \varepsilon_i,
\]</span></p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span> is the number of cigarette packs sold per capita in state <span class="math inline">\(i\)</span>;</li>
<li>
<span class="math inline">\(x_i\)</span> is the real price of cigarettes in state <span class="math inline">\(i\)</span>;</li>
<li>
<span class="math inline">\(\varepsilon_i\)</span> represents all other unobserved factors affecting cigarette consumption.</li>
</ul>
<p>The explanatory variable <span class="math inline">\(x_i\)</span> is potentially endogenous because cigarette prices may be influenced by both supply- and demand-side factors. To address this problem, we use the real cigarette tax as an instrumental variable,</p>
<p><span class="math display">\[
z_i,
\]</span></p>
<p>where <span class="math inline">\(z_i\)</span> denotes the real cigarette tax per pack in state <span class="math inline">\(i\)</span>.</p>
<p>First, estimate the model using OLS.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = packs ~ price, data = cigs)

Residuals:
    Min      1Q  Median      3Q     Max 
-48.470 -10.771   0.373   9.754  53.133 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 210.3342    20.9422   10.04 3.54e-13 ***
price        -0.9481     0.1727   -5.49 1.67e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.69 on 46 degrees of freedom
Multiple R-squared:  0.3958,    Adjusted R-squared:  0.3827 
F-statistic: 30.14 on 1 and 46 DF,  p-value: 1.673e-06</code></pre>
</div>
</div>
<p>The OLS estimates suggest a negative relationship between cigarette prices and cigarette consumption. The estimated coefficient on <code>price</code> is approximately <strong>−0.95</strong>, indicating that, on average, a one-unit increase in the real price of cigarettes is associated with a decrease of about <strong>0.95 packs per capita</strong>.</p>
<p>The coefficient is highly statistically significant (<span class="math inline">\(p &lt; 0.001\)</span>), providing strong evidence of a negative association between price and cigarette consumption. However, because cigarette prices may be endogenous, this estimate should not necessarily be interpreted as the causal effect of price.</p>
<p>Now estimate the first-stage regression. This shows whether the instrument, real cigarette tax, is strongly related to cigarette price.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ tax, data = cigs)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.7121 -3.8703 -0.7123  2.0566 14.9957 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 69.14076    2.68955   25.71   &lt;2e-16 ***
tax          1.45046    0.07334   19.78   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.174 on 46 degrees of freedom
Multiple R-squared:  0.8948,    Adjusted R-squared:  0.8925 
F-statistic: 391.2 on 1 and 46 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The first-stage regression examines whether the proposed instrument, the real cigarette tax, is strongly related to cigarette prices.</p>
<p>The estimated coefficient on <code>tax</code> is positive and highly statistically significant (<span class="math inline">\(p &lt; 0.001\)</span>), indicating that states with higher cigarette taxes tend to have higher cigarette prices. This provides evidence that the instrument satisfies the <strong>relevance</strong> condition.</p>
<p>The first-stage <span class="math inline">\(F\)</span>-statistic is <strong>391.2</strong>, which is well above the commonly used threshold of <strong>10</strong>. This suggests that the instrument is very strong and that weak instrument problems are unlikely in this example.</p>
<p>The fitted values from the first stage represent the component of price explained by the instrument.</p>
<p>The second-stage regression replaces the original price variable with the fitted values from the first stage.</p>
<p>The IV model is thus:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = packs ~ price | tax, data = cigs)

Residuals:
     Min       1Q   Median       3Q      Max 
-48.4535 -10.6514   0.3985   9.5654  53.4038 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 209.0024    22.1210   9.448 2.40e-12 ***
price        -0.9371     0.1826  -5.132 5.64e-06 ***

Diagnostic tests:
                 df1 df2 statistic p-value    
Weak instruments   1  46   391.163  &lt;2e-16 ***
Wu-Hausman         1  45     0.034   0.854    
Sargan             0  NA        NA      NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.69 on 46 degrees of freedom
Multiple R-Squared: 0.3958, Adjusted R-squared: 0.3826 
Wald test: 26.34 on 1 and 46 DF,  p-value: 5.64e-06 </code></pre>
</div>
</div>
<p>Here, <code>price</code> is treated as endogenous and <code>tax</code> is used as the instrument.</p>
<p>The IV estimate of the price coefficient is approximately <strong>−0.94</strong>, indicating that higher cigarette prices are associated with lower cigarette consumption. In this example, the IV estimate is very similar to the OLS estimate, suggesting that accounting for potential endogeneity does not substantially change the estimated relationship.</p>
<p>The diagnostic tests also support this interpretation. The <strong>Weak Instruments</strong> test is highly significant, confirming that cigarette tax is strongly related to cigarette price. The <strong>Wu–Hausman</strong> test is not statistically significant (<span class="math inline">\(p = 0.854\)</span>), indicating little statistical evidence that cigarette price is endogenous in this specification. Thus, in this example, there is little evidence against using OLS.</p>
<p>The output also includes a row labeled <strong>Sargan</strong>, but it is not interpreted here because this chapter has not introduced overidentification tests.</p>
</section></section><section id="exercises" class="level2" data-number="32.8"><h2 data-number="32.8" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">32.8</span> Exercises</h2>
<ol type="1">
<li>For each situation, explain whether endogeneity is likely to be present. If so, identify the most likely source of endogeneity: omitted variable bias, simultaneity, or measurement error.</li>
</ol>
<ol type="a">
<li>Estimating the effect of years of education on wages.</li>
<li>Estimating the effect of police expenditure on crime rates.</li>
<li>Estimating the effect of advertising expenditure on product sales.</li>
<li>Estimating the effect of fertilizer use on crop yields.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p><strong>Education and wages:</strong> Endogeneity is likely because unobserved ability, motivation, or family background may affect both education and wages. This is mainly omitted variable bias.</p></li>
<li><p><strong>Police expenditure and crime:</strong> Endogeneity is likely because areas with higher crime may increase police spending. This is simultaneity or reverse causality.</p></li>
<li><p><strong>Advertising and sales:</strong> Endogeneity is possible because firms may increase advertising when they expect higher sales, or because unobserved product quality affects both advertising and sales. This may involve simultaneity and omitted variable bias.</p></li>
<li><p><strong>Fertilizer and crop yields:</strong> Endogeneity may arise if farmers use more fertilizer on land that is more productive or less productive. Soil quality, rainfall, and farmer ability may be omitted variables.</p></li>
</ol>
</div>
</div>
</div>
<ol start="2" type="1">
<li>For each scenario, propose a potential instrumental variable. Explain why it might satisfy the relevance condition and discuss whether the exclusion restriction is likely to hold.</li>
</ol>
<ol type="a">
<li>Estimating the effect of class size on student achievement.</li>
<li>Estimating the effect of smoking on birth weight.</li>
<li>Estimating the effect of exercise on blood pressure.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p><strong>Class size and student achievement:</strong> A possible instrument is a rule that caps class size at a particular enrollment threshold. It is relevant because it affects class size. The exclusion restriction may hold if the threshold affects achievement only through class size, not through school resources or student composition.</p></li>
<li><p><strong>Smoking and birth weight:</strong> A possible instrument is cigarette taxes. Taxes are relevant because they affect smoking behavior. The exclusion restriction requires that taxes affect birth weight only through maternal smoking, which may be questionable if taxes are correlated with broader state health policies.</p></li>
<li><p><strong>Exercise and blood pressure:</strong> A possible instrument is distance to recreational facilities or local weather variation. It may be relevant if it affects exercise. The exclusion restriction requires that it does not directly affect blood pressure except through exercise, which may be difficult to defend.</p></li>
</ol>
</div>
</div>
</div>
<ol start="3" type="1">
<li>For each proposed instrument, determine whether it is likely to be valid. Discuss both relevance and exclusion.</li>
</ol>
<ol type="a">
<li>Distance to the nearest university as an instrument for years of education.</li>
<li>Weather conditions as an instrument for outdoor exercise.</li>
<li>Lottery winnings as an instrument for household income.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p><strong>Distance to university:</strong> This may be relevant because students living closer to a university may obtain more education. The exclusion restriction requires that distance affects wages only through education. This may fail if distance is related to local labor markets, family background, or urbanization.</p></li>
<li><p><strong>Weather and outdoor exercise:</strong> Weather may be relevant because it affects outdoor exercise. The exclusion restriction may fail if weather directly affects health, mood, pollution exposure, or blood pressure.</p></li>
<li><p><strong>Lottery winnings and income:</strong> Lottery winnings are likely relevant because they increase income. The exclusion restriction may be plausible if winnings affect the outcome only through income, but it may fail if winning the lottery directly changes stress, work behavior, or lifestyle.</p></li>
</ol>
</div>
</div>
</div>
<ol start="4" type="1">
<li>Suppose a regression model contains the following numbers of endogenous explanatory variables, <span class="math inline">\(K_e\)</span>, and instruments, <span class="math inline">\(L\)</span>.</li>
</ol>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: right;"><span class="math inline">\(K_e\)</span></th>
<th style="text-align: right;"><span class="math inline">\(L\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
<p>For each case, state whether the model is underidentified, exactly identified, or overidentified. Explain whether two-stage least squares can be used.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: right;"><span class="math inline">\(K_e\)</span></th>
<th style="text-align: right;"><span class="math inline">\(L\)</span></th>
<th>Identification status</th>
<th>Can 2SLS be used?</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td>Exactly identified</td>
<td>Yes</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td>Overidentified</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td>Exactly identified</td>
<td>Yes</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td>Underidentified</td>
<td>No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td>Overidentified</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p>The general rule is:</p>
<ul>
<li>if <span class="math inline">\(L&lt;K_e\)</span>, the model is underidentified;</li>
<li>if <span class="math inline">\(L=K_e\)</span>, the model is exactly identified;</li>
<li>if <span class="math inline">\(L&gt;K_e\)</span>, the model is overidentified.</li>
</ul>
</div>
</div>
</div>
<ol start="5" type="1">
<li>An IV model produces the following output.</li>
</ol>
<table class="caption-top table">
<thead><tr class="header">
<th>Test</th>
<th style="text-align: right;">Statistic</th>
<th style="text-align: right;">p-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Weak instruments</td>
<td style="text-align: right;">8.4</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="even">
<td>Wu–Hausman</td>
<td style="text-align: right;">5.73</td>
<td style="text-align: right;">0.021</td>
</tr>
</tbody>
</table>
<p>Answer the following questions.</p>
<ol type="a">
<li>Is there evidence of weak instruments?</li>
<li>Is there evidence of endogeneity?</li>
<li>Would you recommend OLS or instrumental variables estimation? Explain your reasoning.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>The weak instruments test is statistically significant, so the instruments appear to be related to the endogenous explanatory variable. However, a statistic of 8.4 is below the common rule-of-thumb threshold of 10, so instrument strength may still be a concern.</p></li>
<li><p>The Wu–Hausman test is statistically significant at the 5% level because <span class="math inline">\(p=0.021\)</span>. This provides evidence that the explanatory variable is endogenous.</p></li>
<li><p>Since there is evidence of endogeneity, IV estimation is preferred over OLS. However, because the weak instrument statistic is below 10, the IV estimates should be interpreted cautiously.</p></li>
</ol>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/termehs\.github\.io\/found-stats\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../regression/reg-diagnostics.html" class="pagination-link" aria-label="Residual Analysis and Model Diagnostics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Residual Analysis and Model Diagnostics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../appendix/normal-table.html" class="pagination-link" aria-label="The Standard Normal Distribution Table">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Standard Normal Distribution Table</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Foundational Statistics by Termeh Shafie.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/termehs/found-stats/edit/main/regression/iv-est.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/termehs/found-stats/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>