<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Termeh Shafie">
<title>29&nbsp; Regression Inference – Foundational Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../regression/reg-cats.html" rel="next">
<link href="../regression/mlr.html" rel="prev">
<link href="../cover.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6bb5ad484749947dbf006bb4d74c4af5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../regression/reg-framework.html">Regression Analysis</a></li><li class="breadcrumb-item"><a href="../regression/reg-inf.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regression Inference</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundational Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/termehs/found-stats" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/what-is-stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Statistics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Unavoidable Math</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/intro-surveys.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Surveys: Key Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/variable-class.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variable Classification</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Descriptive Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/describe-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing a Dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/central-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measures of Central Tendency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../descriptive-stats/dispersion-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Measures of Dispersion</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Concepts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/what-is-prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What is Probability?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/count-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Counting Rules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prob-theory/prob-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Rules</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Random Variables and Probability Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/discrete-dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/cont-dists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rvs-probdists/jointly-dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Jointly Distributed Random Variables</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Sampling and Sampling Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling-dist-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Sampling Distributions for a Sample Mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/sampling-dist-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Sampling Distributions for a Sample Proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling-dists/clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferential Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/intro-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">From Probability to Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inferential/hyp-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Chi Square Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Chi Square Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2-gof.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Goodness-of-Fit Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chi2/chi2-ind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Testing for Independence</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The Regression Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-inf.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regression Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-cats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Categorical Variables in Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regression/reg-diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Residual Analysis and Model Diagnostics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/normal-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Standard Normal Distribution Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/t-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(t\)</span> Distribution Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendix/chi2-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">The <span class="math inline">\(\chi^2\)</span> Distribution Table</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link active" data-scroll-target="#simple-linear-regression"><span class="header-section-number">29.1</span> Simple Linear Regression</a>
  <ul class="collapse">
<li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">29.1.1</span> Assumptions</a></li>
  <li><a href="#variance-of-the-estimator-b_1" id="toc-variance-of-the-estimator-b_1" class="nav-link" data-scroll-target="#variance-of-the-estimator-b_1"><span class="header-section-number">29.1.2</span> Variance of the Estimator <span class="math inline">\(b_1\)</span></a></li>
  <li><a href="#confidence-interval-for-beta_1" id="toc-confidence-interval-for-beta_1" class="nav-link" data-scroll-target="#confidence-interval-for-beta_1"><span class="header-section-number">29.1.3</span> Confidence Interval for <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#hypothesis-testing-for-beta_1" id="toc-hypothesis-testing-for-beta_1" class="nav-link" data-scroll-target="#hypothesis-testing-for-beta_1"><span class="header-section-number">29.1.4</span> Hypothesis Testing for <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#hypothesis-testing-for-beta_1-t-test-and-f-test-equivalence" id="toc-hypothesis-testing-for-beta_1-t-test-and-f-test-equivalence" class="nav-link" data-scroll-target="#hypothesis-testing-for-beta_1-t-test-and-f-test-equivalence"><span class="header-section-number">29.1.5</span> Hypothesis Testing for <span class="math inline">\(\beta_1\)</span>: t-Test and F-Test Equivalence</a></li>
  </ul>
</li>
  <li><a href="#the-multiple-linear-regression-model" id="toc-the-multiple-linear-regression-model" class="nav-link" data-scroll-target="#the-multiple-linear-regression-model"><span class="header-section-number">29.2</span> The Multiple Linear Regression Model</a></li>
  <li><a href="#assumptions-and-the-gaussmarkov-theorem" id="toc-assumptions-and-the-gaussmarkov-theorem" class="nav-link" data-scroll-target="#assumptions-and-the-gaussmarkov-theorem"><span class="header-section-number">29.3</span> Assumptions and the Gauss–Markov Theorem</a></li>
  <li><a href="#confidence-intervals-for-coefficients" id="toc-confidence-intervals-for-coefficients" class="nav-link" data-scroll-target="#confidence-intervals-for-coefficients"><span class="header-section-number">29.4</span> Confidence Intervals for Coefficients</a></li>
  <li><a href="#hypothesis-testing-for-individual-predictors" id="toc-hypothesis-testing-for-individual-predictors" class="nav-link" data-scroll-target="#hypothesis-testing-for-individual-predictors"><span class="header-section-number">29.5</span> Hypothesis Testing for Individual Predictors</a></li>
  <li><a href="#joint-hypothesis-testing-in-multiple-linear-regression" id="toc-joint-hypothesis-testing-in-multiple-linear-regression" class="nav-link" data-scroll-target="#joint-hypothesis-testing-in-multiple-linear-regression"><span class="header-section-number">29.6</span> Joint Hypothesis Testing in Multiple Linear Regression</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/termehs/found-stats/edit/main/regression/reg-inf.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/termehs/found-stats/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../regression/reg-framework.html">Regression Analysis</a></li><li class="breadcrumb-item"><a href="../regression/reg-inf.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regression Inference</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-reginf" class="quarto-section-identifier"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regression Inference</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Up until now, we have focused on fitting a straight line to a given dataset. This is a purely descriptive task, we are summarizing the data using a linear trend.</p>
<p>Now we shift our attention to <strong>statistical inference</strong>. Instead of just describing the data, we want to draw conclusions about the underlying <strong>data-generating process</strong>. In this context, we assume that the data were produced by a regression model; a hypothetical mechanism involving randomness that governs how the observed values arise.</p>
<p>Our concern is understanding the reliability of the coefficient estimates. Are they statistically significant? Are they meaningfully different from zero? To address such questions, we use tools like confidence intervals and hypothesis tests, just as we did in <a href="../inferential/estimation.html" class="quarto-xref"><span>Chapter 21</span></a> and <a href="../inferential/hyp-test.html" class="quarto-xref"><span>Chapter 22</span></a>.</p>
<section id="simple-linear-regression" class="level2" data-number="29.1"><h2 data-number="29.1" class="anchored" data-anchor-id="simple-linear-regression">
<span class="header-section-number">29.1</span> Simple Linear Regression</h2>
<p>We think of each observed value <span class="math inline">\(y_i\)</span> not just as a number, but as a realization of a <strong>random variable</strong> <span class="math inline">\(Y_i\)</span>, generated according to the following model:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x + \varepsilon
\]</span></p>
<p>Here, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are unknown parameters, and <span class="math inline">\(\varepsilon\)</span> is a random error term. This expression means that the outcome <span class="math inline">\(Y\)</span> is made up of two parts:</p>
<ul>
<li>A <strong>deterministic part</strong>, which is a linear function of the predictor <span class="math inline">\(x\)</span>: <span class="math inline">\(\beta_0 + \beta_1 x\)</span>
</li>
<li>A <strong>random part</strong>, the error term <span class="math inline">\(\varepsilon\)</span>, which captures the effect of other influences not included in the model</li>
</ul>
<p>see <a href="reg-framework.html" class="quarto-xref"><span>Chapter 26</span></a> for more detail.</p>
<section id="assumptions" class="level3" data-number="29.1.1"><h3 data-number="29.1.1" class="anchored" data-anchor-id="assumptions">
<span class="header-section-number">29.1.1</span> Assumptions</h3>
<p>In the <strong>standard model for simple linear regression</strong>, we make the following assumptions:</p>
<ol type="1">
<li><p>The values <span class="math inline">\(x_1, x_2, \dots, x_n\)</span> are treated as fixed, non-random inputs.</p></li>
<li>
<p>For each fixed <span class="math inline">\(x_i\)</span>, the corresponding response variable <span class="math inline">\(Y_i\)</span> satisfies:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i
\]</span></p>
</li>
<li>
<p>The error terms <span class="math inline">\(\varepsilon_1, \varepsilon_2, \dots, \varepsilon_n\)</span> are <strong>independent and normally distributed random variables</strong> with:</p>
<p><span class="math display">\[
\varepsilon_i \sim \mathcal{N}(0, \sigma^2)
\]</span></p>
<p>That is, they have mean 0 and the same variance <span class="math inline">\(\sigma^2\)</span>, and they are mutually independent.</p>
</li>
</ol>
<p>Our goal is to estimate the unknown parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. In practice, it is often <span class="math inline">\(\beta_1\)</span>, the slope, that is of greatest interest, as it measures the strength and direction of the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p>To estimate these parameters, we use the <strong>least squares method</strong>, fitting a line of the form:</p>
<p><span class="math display">\[
y = b_0 + b_1 x
\]</span></p>
<p>The resulting estimates <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are called <strong>point estimates</strong> of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, respectively:</p>
<p><span class="math display">\[
\hat{\beta}_0 = b_0 \quad \text{and} \quad \hat{\beta}_1 = b_1
\]</span></p>
<p>Under the model assumptions, it can be shown that both <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are <strong>unbiased estimators</strong>, meaning:</p>
<p><span class="math display">\[
E(b_0) = \beta_0 \quad \text{and} \quad E(b_1) = \beta_1
\]</span></p>
</section><section id="variance-of-the-estimator-b_1" class="level3" data-number="29.1.2"><h3 data-number="29.1.2" class="anchored" data-anchor-id="variance-of-the-estimator-b_1">
<span class="header-section-number">29.1.2</span> Variance of the Estimator <span class="math inline">\(b_1\)</span>
</h3>
<p>We are also interested in how precise our estimate <span class="math inline">\(b_1\)</span> is. The variance of <span class="math inline">\(b_1\)</span> is given by:</p>
<p><span class="math display">\[
\mathrm{Var}(b_1) = \frac{\sigma^2}{\sum (x_i - \bar{x})^2} = \frac{\sigma^2}{(n - 1)s_x^2}
\]</span></p>
<p>This tells us that the spread of the <span class="math inline">\(x\)</span> values (captured by <span class="math inline">\(s_x^2\)</span>) plays an important role in determining the precision of the slope estimate.</p>
<p>In practice, the true error variance <span class="math inline">\(\sigma^2\)</span> is unknown. To estimate <span class="math inline">\(\mathrm{Var}(b_1)\)</span> from the data, we replace <span class="math inline">\(\sigma^2\)</span> with the <strong>residual variance</strong> <span class="math inline">\(s_e^2\)</span>, which is an unbiased estimator of <span class="math inline">\(\sigma^2\)</span> and is computed as:</p>
<p><span class="math display">\[
s_e^2 = \frac{\text{SSE}}{n - 2}
\]</span></p>
<p>We then obtain the estimated variance of <span class="math inline">\(b_1\)</span> as:</p>
<p><span class="math display">\[
s_{b_1}^2 = \frac{s_e^2}{(n - 1)s_x^2}
\]</span></p>
<p>This estimated variance will be used to construct <strong>confidence intervals</strong> and perform <strong>hypothesis tests</strong> about <span class="math inline">\(\beta_1\)</span> in the following sections.</p>
</section><section id="confidence-interval-for-beta_1" class="level3" data-number="29.1.3"><h3 data-number="29.1.3" class="anchored" data-anchor-id="confidence-interval-for-beta_1">
<span class="header-section-number">29.1.3</span> Confidence Interval for <span class="math inline">\(\beta_1\)</span>
</h3>
<p>Once we have estimated the regression coefficients using the least squares method, we may want to make <strong>inferences</strong> about the true (but unknown) population parameter <span class="math inline">\(\beta_1\)</span>. Two important tools for this purpose are <strong>confidence intervals</strong> and <strong>hypothesis testing</strong>.</p>
<p>We already know that the point estimate <span class="math inline">\(b_1\)</span> is an unbiased estimator of the true slope <span class="math inline">\(\beta_1\)</span>. Furthermore, under the classical linear regression assumptions (including normal, independent, and homoscedastic errors), <span class="math inline">\(b_1\)</span> is approximately normally distributed for large samples, or <strong>t-distributed</strong> for small samples.</p>
<p>To quantify the uncertainty in our estimate, we construct a <strong>confidence interval</strong> for <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math display">\[
b_1 \pm t_{\nu, \alpha/2} \cdot s_{b_1}
\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(s_{b_1}\)</span> is the estimated standard error of <span class="math inline">\(b_1\)</span>
</li>
<li>
<span class="math inline">\(t_{\nu, \alpha/2}\)</span> is the critical value from the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(\nu = n - 2\)</span> degrees of freedom</li>
<li>
<span class="math inline">\(\alpha\)</span> is the significance level (e.g., <span class="math inline">\(\alpha = 0.05\)</span> gives a 95% confidence interval)</li>
</ul>
<p>If the sample size is large (<span class="math inline">\(n \geq 30\)</span>), the <span class="math inline">\(t\)</span>-distribution can be approximated by the standard normal distribution <span class="math inline">\(\mathcal{N}(0, 1)\)</span>, and the confidence interval becomes:</p>
<p><span class="math display">\[
b_1 \pm z_{\alpha/2} \cdot s_{b_1}
\]</span></p>
<p>This interval provides a range of plausible values for the true slope <span class="math inline">\(\beta_1\)</span> at the chosen confidence level.</p>
</section><section id="hypothesis-testing-for-beta_1" class="level3" data-number="29.1.4"><h3 data-number="29.1.4" class="anchored" data-anchor-id="hypothesis-testing-for-beta_1">
<span class="header-section-number">29.1.4</span> Hypothesis Testing for <span class="math inline">\(\beta_1\)</span>
</h3>
<p>We may also wish to formally test hypotheses about the slope coefficient. For example, suppose we want to test whether <span class="math inline">\(\beta_1\)</span> equals a specific value <span class="math inline">\(\beta_1^*\)</span> (often this is 0), corresponding to the absence of a linear relationship.</p>
<p>We set up the null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = \beta_1^*\)</span> (null hypothesis)</li>
<li>
<span class="math inline">\(H_1\)</span>: <span class="math inline">\(\beta_1 \ne \beta_1^*\)</span> (two-sided alternative), or</li>
<li>
<span class="math inline">\(H_1\)</span>: <span class="math inline">\(\beta_1 &gt; \beta_1^*\)</span> or <span class="math inline">\(\beta_1 &lt; \beta_1^*\)</span> (one-sided alternatives)</li>
</ul>
<p>A common special case is:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span>
</li>
<li>
<span class="math inline">\(H_1\)</span>: <span class="math inline">\(\beta_1 \ne 0\)</span>
</li>
</ul>
<p>This tests whether there is <em>any linear relationship at all</em> between the predictor and response.</p>
<p>To perform the test, we use the following <strong><span class="math inline">\(t\)</span>-statistic</strong>:</p>
<p><span class="math display">\[
t = \frac{b_1 - \beta_1^*}{s_{b_1}}
\]</span></p>
<p>If <span class="math inline">\(H_0\)</span> is true, this statistic follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(\nu = n - 2\)</span> degrees of freedom. In the special case when testing <span class="math inline">\(H_0: \beta_1 = 0\)</span>, the test statistic simplifies to:</p>
<p><span class="math display">\[
t = \frac{b_1}{s_{b_1}}
\]</span></p>
<p>We then compare the calculated <span class="math inline">\(t\)</span> value to critical values from the <span class="math inline">\(t\)</span>-distribution to decide whether to reject <span class="math inline">\(H_0\)</span>. Just like before (<a href="../inferential/hyp-test.html" class="quarto-xref"><span>Chapter 22</span></a>) the rejection region depends on:</p>
<ul>
<li>The significance level (e.g., <span class="math inline">\(\alpha = 0.05\)</span>)</li>
<li>The type of alternative hypothesis (one- or two-sided)</li>
</ul>
<p>If the <span class="math inline">\(t\)</span>-statistic falls into the rejection region, we conclude that there is statistically significant evidence that <span class="math inline">\(\beta_1\)</span> differs from <span class="math inline">\(\beta_1^*\)</span> (e.g., that a linear relationship exists).</p>
</section><section id="hypothesis-testing-for-beta_1-t-test-and-f-test-equivalence" class="level3" data-number="29.1.5"><h3 data-number="29.1.5" class="anchored" data-anchor-id="hypothesis-testing-for-beta_1-t-test-and-f-test-equivalence">
<span class="header-section-number">29.1.5</span> Hypothesis Testing for <span class="math inline">\(\beta_1\)</span>: t-Test and F-Test Equivalence</h3>
<p>In simple linear regression, a common question is whether the explanatory variable <span class="math inline">\(x\)</span> has any linear influence on the response variable <span class="math inline">\(y\)</span>. This is typically tested by assessing whether the slope coefficient <span class="math inline">\(\beta_1\)</span> equals zero.</p>
<p>We state the hypotheses as:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span> (no linear relationship)</li>
<li>
<span class="math inline">\(H_1\)</span>: <span class="math inline">\(\beta_1 \ne 0\)</span> (there is a linear relationship)</li>
</ul>
<p>To test this, we use the <strong>F-statistic</strong> from the ANOVA table, which compares the explained and unexplained variance in <span class="math inline">\(y\)</span>. We define:</p>
<ul>
<li>
<span class="math inline">\(F_\text{obs}\)</span>: the observed F-statistic</li>
<li>
<span class="math inline">\(F_c\)</span>: the critical value from the <span class="math inline">\(F\)</span> distribution at the chosen significance level</li>
</ul>
<p>We reject <span class="math inline">\(H_0\)</span> only if the observed statistic exceeds the critical value:</p>
<p><span class="math display">\[
F_{\text{obs}} &gt; F_c
\]</span></p>
<p>In the special case of testing <span class="math inline">\(\beta_1 = 0\)</span> in a simple linear regression**, the F-test and t-test are mathematically equivalent. That is:</p>
<p><span class="math display">\[
F = t^2
\]</span></p>
<p>Both tests always lead to exactly the same conclusion in this setting. While the t-test focuses on the slope coefficient <span class="math inline">\(b_1\)</span> directly, the F-test evaluates the overall significance of the model. In simple linear regression, both refer to the same one predictor, so they test the same null hypothesis. We will return to the F test again below for multiple linear regression.</p>
<section id="example-28.1-savings-and-income" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-28.1-savings-and-income">Example 28.1: Savings and Income</h4>
<p>Let’s apply these ideas to an example. Suppose we want to understand how <strong>savings</strong> (in hundreds of EUR) depend on <strong>income</strong> (also in hundreds of EUR). We collect data from 10 individuals:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Income (<span class="math inline">\(x\)</span>)</th>
<th>Savings (<span class="math inline">\(y\)</span>)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>18</td>
<td>8</td>
</tr>
<tr class="even">
<td>44</td>
<td>52</td>
</tr>
<tr class="odd">
<td>31</td>
<td>30</td>
</tr>
<tr class="even">
<td>38</td>
<td>31</td>
</tr>
<tr class="odd">
<td>36</td>
<td>30</td>
</tr>
<tr class="even">
<td>26</td>
<td>25</td>
</tr>
<tr class="odd">
<td>24</td>
<td>8</td>
</tr>
<tr class="even">
<td>51</td>
<td>45</td>
</tr>
<tr class="odd">
<td>22</td>
<td>3</td>
</tr>
<tr class="even">
<td>30</td>
<td>16</td>
</tr>
</tbody>
</table>
<p>Our goal is to determine whether income significantly predicts savings using a simple linear regression model:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x + \varepsilon
\]</span></p>
<p>We’ll estimate <span class="math inline">\(b_1\)</span>, construct a confidence interval for <span class="math inline">\(\beta_1\)</span>, and test the hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span> using both a <strong>t-test</strong> and <strong>F-test</strong> to verify they produce the same result. This is done with R and the R output for the the above regression is as follows (the middle part is the 95% confidence interval fir <span class="math inline">\(\beta_1\)</span>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = df)

Residuals:
   Min     1Q Median     3Q    Max 
-7.531 -5.806 -1.435  5.764 10.077 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -20.8618     7.7114  -2.705 0.026852 *  
x             1.4269     0.2304   6.192 0.000262 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.133 on 8 degrees of freedom
Multiple R-squared:  0.8274,    Adjusted R-squared:  0.8058 
F-statistic: 38.34 on 1 and 8 DF,  p-value: 0.0002617</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -38.644256 -3.079335
x             0.895531  1.958331</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: y
          Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
x          1 1950.61 1950.61  38.343 0.0002617 ***
Residuals  8  406.99   50.87                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The interpretation is as follows:</p>
<ul>
<li>The slope coefficient <span class="math inline">\(b_1\)</span> represents the average change in savings per 1 unit (hundred EUR) increase in income.</li>
<li>The confidence interval for <span class="math inline">\(\beta_1\)</span> tells us the range of plausible values.</li>
<li>If the interval does not include 0, and the p-value is below the significance threshold (e.g., 0.05), we reject <span class="math inline">\(H_0\)</span> and conclude that income has a statistically significant effect on savings.</li>
<li>The F-statistic and the square of the t-statistic for <span class="math inline">\(b_1\)</span> are equal, confirming the equivalence of both tests in this case.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Introducing the F-distribution in Regression">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Introducing the F-distribution in Regression
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>F-distribution</strong> arises when comparing two variances, one typically explained by a model, and the other left unexplained (the residual variance). It is commonly used in regression analysis to evaluate whether the <strong>regression model explains a significant proportion of the total variation</strong> in the response variable.</p>
<p>In the case of simple linear regression, the F-statistic is defined as:</p>
<p><span class="math display">\[
F = \frac{MSR}{MSE}
\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(MSR\)</span> is the <strong>mean square due to regression</strong>, i.e., the variation explained by the model,</li>
<li>
<span class="math inline">\(MSE\)</span> is the <strong>mean square error</strong>, i.e., the average of the squared residuals.</li>
</ul>
<p>Under the null hypothesis that the slope <span class="math inline">\(\beta_1 = 0\)</span> (no linear relationship), the F-statistic follows an <strong>F-distribution</strong> with two degrees of freedom: <span class="math inline">\((1, n - 2)\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the sample size.</p>
<p>We use this distribution to determine whether the observed <span class="math inline">\(F\)</span> value is unusually large. A large <span class="math inline">\(F\)</span> value indicates that the model explains a significantly greater amount of variability than would be expected by chance.</p>
<p>In simple linear regression, the F-test and the squared t-test for <span class="math inline">\(\beta_1\)</span> are mathematically equivalent: <span class="math display">\[
F = t^2
\]</span> However, the F-distribution plays a much larger role in <strong>multiple regression</strong>, where it tests the significance of all predictors jointly.</p>
<p>Like the chi-square test, the F-test is <strong>one-sided</strong>: we only reject the null hypothesis when the observed F-statistic is <strong>sufficiently large</strong>, as shown in <a href="#fig-fdist" class="quarto-xref">Figure&nbsp;<span>29.1</span></a>.</p>
<div id="fig-fdist" class="center quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-fdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="reg-inf_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;29.1: This figure illustrates the F-distribution with the critical region shaded in red, corresponding to the upper tail of the distribution where we would reject the null hypothesis. As with the chi-square distribution, the F-test is right-tailed because we are only interested in whether the observed F-statistic is significantly larger than expected under <span class="math inline">\(H_0\)</span>.
</figcaption></figure>
</div>
</div>
</div>
</section></section></section><section id="the-multiple-linear-regression-model" class="level2" data-number="29.2"><h2 data-number="29.2" class="anchored" data-anchor-id="the-multiple-linear-regression-model">
<span class="header-section-number">29.2</span> The Multiple Linear Regression Model</h2>
<p>In multiple regression, we model the response <span class="math inline">\(y\)</span> as a linear combination of several predictors:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots + \beta_K x_{Ki} + \varepsilon_i
\]</span></p>
<p>Here:</p>
<ul>
<li>
<span class="math inline">\(Y_i\)</span> is the response for observation <span class="math inline">\(i\)</span>
</li>
<li>
<span class="math inline">\(x_{1i}, x_{2i}, \dots, x_{Ki}\)</span> are the values of <span class="math inline">\(K\)</span> predictors for observation <span class="math inline">\(i\)</span>
</li>
<li>
<span class="math inline">\(\beta_0\)</span> is the intercept</li>
<li>
<span class="math inline">\(\beta_1, \dots, \beta_K\)</span> are the unknown slope parameters</li>
<li>
<span class="math inline">\(\varepsilon_i\)</span> is the error term, capturing randomness and unobserved effects</li>
</ul>
<p>This model allows us to assess how <strong>each predictor influences <span class="math inline">\(y\)</span> while holding all other variables constant</strong>. In contrast to simple regression, where effects are unadjusted, multiple regression gives <strong>adjusted estimates</strong> that help untangle overlapping influences.</p>
</section><section id="assumptions-and-the-gaussmarkov-theorem" class="level2" data-number="29.3"><h2 data-number="29.3" class="anchored" data-anchor-id="assumptions-and-the-gaussmarkov-theorem">
<span class="header-section-number">29.3</span> Assumptions and the Gauss–Markov Theorem</h2>
<p>Like simple linear regression, the multiple linear regression model is built on a set of fundamental assumptions that ensure the reliability of the estimates and the validity of inference procedures.</p>
<p>At the core of the model is the assumption that the relationship between the response variable <span class="math inline">\(y\)</span> and the explanatory variables <span class="math inline">\(x_1, x_2, \dots, x_K\)</span> is <strong>linear in parameters</strong>. This means the model takes the form:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots + \beta_K x_{Ki} + \varepsilon_i,
\]</span></p>
<p>where <span class="math inline">\(\varepsilon_i\)</span> is a random error term.</p>
<p>For the least squares estimates to perform well, the following assumptions must hold:</p>
<ol type="1">
<li><p><strong>Linearity</strong>: The model must be linear in the coefficients. This does not mean that the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> must look linear visually, but rather that the parameters appear in a linear form (i.e., no squares, logs, or interactions unless explicitly modeled).</p></li>
<li><p><strong>Fixed explanatory variables</strong>: The values of the explanatory variables <span class="math inline">\(x_{1i}, \dots, x_{Ki}\)</span> are assumed to be non-random across repeated samples. This means we condition on <span class="math inline">\(X\)</span> when making inference about <span class="math inline">\(\beta\)</span>.</p></li>
<li><p><strong>Zero mean of errors</strong>: The error terms are assumed to have an expected value of zero: <span class="math inline">\(E[\varepsilon_i] = 0\)</span> for all <span class="math inline">\(i\)</span>.</p></li>
<li><p><strong>Independence of errors</strong>: The errors are independent of one another across observations. This rules out autocorrelation or clustering unless specifically accounted for in the model.</p></li>
<li><p><strong>Constant variance (Homoskedasticity)</strong>: All errors have the same variance: <span class="math inline">\(\operatorname{Var}(\varepsilon_i) = \sigma^2\)</span>. If the variance of errors changes with the level of a predictor, we have <strong>heteroskedasticity</strong>, which violates this assumption.</p></li>
<li><p><strong>No perfect multicollinearity</strong>: The explanatory variables must not be perfectly linearly related. That is, no predictor can be expressed as an exact linear combination of the others. This ensures that the matrix <span class="math inline">\(X'X\)</span> is invertible.</p></li>
</ol>
<p>Under these assumptions (excluding the assumption of normality) we can invoke the <strong>Gauss–Markov Theorem</strong>, which is a cornerstone of classical regression theory. It states:</p>
<blockquote class="blockquote">
<p>Among all linear and unbiased estimators, the <strong>least squares estimator</strong> has the <strong>smallest variance</strong>. That is, it is the <strong>Best Linear Unbiased Estimator (BLUE)</strong> of the regression coefficients.</p>
</blockquote>
<p>This result justifies using least squares even in the absence of normally distributed errors, as long as the other assumptions hold.</p>
<p>If, in addition to the above assumptions, we assume that the errors <span class="math inline">\(\varepsilon_i\)</span> are <strong>normally distributed</strong> (i.e., <span class="math inline">\(\varepsilon_i \sim \mathcal{N}(0, \sigma^2)\)</span>), then the least squares estimators not only remain unbiased and efficient but also follow a known sampling distribution. Specifically, the estimated coefficients follow a multivariate normal distribution, which enables us to perform t-tests, F-tests, and construct confidence intervals using standard inferential tools.</p>
<p>To estimate the coefficients <span class="math inline">\(\beta_0, \dots, \beta_K\)</span>, we apply the <strong>method of least squares</strong>, which minimizes the <strong>sum of squared residuals</strong>:</p>
<p><span class="math display">\[
\text{SSE} = \sum_{i=1}^n (y_i - \hat{y}_i)^2 = \sum_{i=1}^n (y_i - b_0 - b_1 x_{1i} - \dots - b_K x_{Ki})^2.
\]</span></p>
<p>The solution yields the least squares estimates <span class="math inline">\(b_0, b_1, \dots, b_K\)</span>, which are point estimates of the unknown population coefficients. Under the model assumptions, each <span class="math inline">\(b_k\)</span> is an <strong>unbiased</strong> estimator of the corresponding <span class="math inline">\(\beta_k\)</span>:</p>
<p><span class="math display">\[
E[b_k] = \beta_k.
\]</span></p>
<p>This guarantees that the estimates are, on average, correct in repeated sampling.</p>
<p>In summary, the classical linear regression model provides a solid statistical framework for estimation and inference, but only when its assumptions are satisfied. The Gauss–Markov Theorem confirms the optimality of least squares under fairly minimal conditions, making it the default approach in many applied settings.</p>
</section><section id="confidence-intervals-for-coefficients" class="level2" data-number="29.4"><h2 data-number="29.4" class="anchored" data-anchor-id="confidence-intervals-for-coefficients">
<span class="header-section-number">29.4</span> Confidence Intervals for Coefficients</h2>
<p>Once we’ve estimated the model parameters using least squares, we often want to understand the <strong>uncertainty</strong> in those estimates. Two central tools for doing this are <strong>confidence intervals</strong> and <strong>hypothesis tests</strong>, particularly concerning individual regression coefficients. We start with the former.</p>
<p>Each estimated coefficient in the regression model, denoted <span class="math inline">\(b_j\)</span>, is only an estimate of the true but unknown population coefficient <span class="math inline">\(\beta_j\)</span>. Due to sampling variability, this estimate is subject to uncertainty. To capture this uncertainty, we construct a confidence interval.</p>
<p>A 95% confidence interval for <span class="math inline">\(\beta_j\)</span> takes the form:</p>
<p><span class="math display">\[
b_j \pm t_{\nu, 0.025} \cdot s_{b_j}
\]</span></p>
<p>Here, <span class="math inline">\(s_{b_j}\)</span> is the standard error of <span class="math inline">\(b_j\)</span>, and <span class="math inline">\(t_{\nu, 0.025}\)</span> is the critical value from the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(\nu = n - K - 1\)</span> degrees of freedom. The interval gives us a range of values within which the true coefficient <span class="math inline">\(\beta_j\)</span> is likely to fall, assuming the model assumptions hold.</p>
<p>In practical work, these intervals are usually reported alongside the model output in software such as R, and they serve as a direct way to assess both the magnitude and uncertainty of an effect.</p>
</section><section id="hypothesis-testing-for-individual-predictors" class="level2" data-number="29.5"><h2 data-number="29.5" class="anchored" data-anchor-id="hypothesis-testing-for-individual-predictors">
<span class="header-section-number">29.5</span> Hypothesis Testing for Individual Predictors</h2>
<p>Beyond estimating coefficients, we often want to test whether a given variable contributes meaningfully to explaining <span class="math inline">\(y\)</span> in the presence of other variables. To do this, we test whether the corresponding coefficient is equal to zero. This leads to the hypothesis:</p>
<p><span class="math display">\[
H_0: \beta_j = 0 \quad \text{versus} \quad H_1: \beta_j \neq 0
\]</span></p>
<p>We calculate a <span class="math inline">\(t\)</span>-statistic using the formula:</p>
<p><span class="math display">\[
t = \frac{b_j}{s_{b_j}}
\]</span></p>
<p>This statistic measures how many standard errors the estimate is away from zero. If the result is far enough from zero, relative to the <span class="math inline">\(t\)</span>-distribution, we reject the null hypothesis. The <span class="math inline">\(t\)</span>-distribution used here has <span class="math inline">\(n - K - 1\)</span> degrees of freedom, which accounts for both the sample size and the number of estimated parameters.</p>
</section><section id="joint-hypothesis-testing-in-multiple-linear-regression" class="level2" data-number="29.6"><h2 data-number="29.6" class="anchored" data-anchor-id="joint-hypothesis-testing-in-multiple-linear-regression">
<span class="header-section-number">29.6</span> Joint Hypothesis Testing in Multiple Linear Regression</h2>
<p>So far, we’ve looked at inference for individual regression coefficients asking whether a single explanatory variable has a statistically significant effect on the response variable. But in multiple regression, a more fundamental question often comes first:</p>
<blockquote class="blockquote">
<p>Do all the predictors together explain any of the variation in the response variable?</p>
</blockquote>
<p>This leads to a <strong>joint hypothesis test</strong>, where we test whether <em>all</em> regression coefficients, except the intercept, are simultaneously equal to zero. This is also knows as an <strong>omnibus test</strong>.</p>
<p>We formulate the hypotheses as:</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \dots = \beta_K = 0
\]</span></p>
<p><span class="math display">\[
H_1: \text{At least one } \beta_j \neq 0, \quad j = 1, 2, \dots, K
\]</span></p>
<p>Under the null hypothesis, none of the explanatory variables contribute linearly to explaining <span class="math inline">\(y\)</span>. In other words, we might as well discard them all and use only the intercept to predict <span class="math inline">\(y\)</span>.</p>
<p>To test this joint hypothesis, we use the <strong>F-statistic</strong> from the regression’s ANOVA table:</p>
<p><span class="math display">\[
F = \frac{MSR}{MSE}
\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(MSR\)</span> is the mean square for regression: <span class="math inline">\(MSR = \frac{SSR}{K}\)</span>
</li>
<li>
<span class="math inline">\(MSE\)</span> is the mean square for error: <span class="math inline">\(MSE = \frac{SSE}{n - K - 1}\)</span>
</li>
</ul>
<p>This F-statistic follows an <strong>F-distribution</strong> with <span class="math inline">\(K\)</span> degrees of freedom in the numerator and <span class="math inline">\(n - K - 1\)</span> in the denominator, assuming the null hypothesis is true.</p>
<p>If the observed value of <span class="math inline">\(F\)</span> is <strong>large</strong>, this suggests that the model explains a substantial portion of the variability in <span class="math inline">\(y\)</span>, and we reject the null hypothesis.</p>
<p>In practical terms:</p>
<ul>
<li>A <strong>small F-value</strong> suggests that the predictors, taken together, do not improve prediction beyond what we’d expect by chance.</li>
<li>A <strong>large F-value</strong> provides evidence that at least one of the explanatory variables contributes meaningfully to the model.</li>
</ul>
<p>Software, such as R, will compute the F-statistic and the corresponding <span class="math inline">\(p\)</span>-value automatically. The result is typically reported in the regression output, adn the corresponding <span class="math inline">\(p\)</span>-value can be used to perform the test,</p>
<section id="example-28.1-sales-in-different-districts-contd" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-28.1-sales-in-different-districts-contd">Example 28.1: Sales in Different Districts (Cont’d)</h4>
<p>We continue with Example 28.1 from <a href="mlr.html" class="quarto-xref"><span>Chapter 28</span></a> where the response variable is:</p>
<ul>
<li>
<span class="math inline">\(y\)</span>: total sales (in millions of EUR)</li>
</ul>
<p>and the two explanatory variables are:</p>
<ul>
<li>
<span class="math inline">\(x_1\)</span>: population size (in 100,000s of people)</li>
<li>
<span class="math inline">\(x_2\)</span>: advertising volume (in 10,000s of EUR)</li>
</ul>
<p>We test (at the 1% significance level) whether <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> together can explain the variation in <span class="math inline">\(y\)</span>. In other words, we will perform an F-test.</p>
<p>We set up the null and alternative hypotheses as follows:</p>
<ul>
<li><p>Null hypothesis: <span class="math inline">\(H_0 : \beta_1 = \beta_2 = 0\)</span><br>
(Neither predictor has a linear effect on <span class="math inline">\(y\)</span>.)</p></li>
<li><p>Alternative hypothesis: <span class="math inline">\(H_1 :\)</span> At least one of <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span> is nonzero<br>
(At least one predictor contributes to explaining <span class="math inline">\(y\)</span>.)</p></li>
</ul>
<p>We read from the output below that the observed value of the F statistic is equal to <span class="math display">\[
F = 88.1
\]</span> on <span class="math inline">\(K=2\)</span> and <span class="math inline">\(n-K-1 = 8-2-1 = 5\)</span> degrees of freedom.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2, data = sales_df)

Residuals:
       1        2        3        4        5        6        7        8 
-0.27273 -0.43141  0.18678  0.60826 -0.40773  0.55532 -0.30926  0.07076 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)   0.4301     0.3897   1.104   0.3200  
x1            0.5464     0.1625   3.362   0.0201 *
x2            0.5021     0.1825   2.752   0.0402 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4981 on 5 degrees of freedom
Multiple R-squared:  0.9724,    Adjusted R-squared:  0.9614 
F-statistic:  88.1 on 2 and 5 DF,  p-value: 0.0001265</code></pre>
</div>
</div>
<p>We reject the null hypothesis at the 1% significance level since the <span class="math inline">\(p\)</span>-value is much smaller than 0.1. This means there is strong evidence that at least one of the explanatory variables has a significant linear relationship with <span class="math inline">\(y\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Using the $p$-value for the F-test">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Using the <span class="math inline">\(p\)</span>-value for the F-test
</div>
</div>
<div class="callout-body-container callout-body">
<p>In modern statistical practice, we almost always rely on the <span class="math inline">\(p\)</span>-value reported in the regression output to evaluate the F-test. There is <em>no need to consult critical value tables manually</em>, since the <span class="math inline">\(p\)</span>-value directly tells us how likely it is to observe an F-statistic as large as the one obtained, assuming the null hypothesis is true.</p>
<p>If the <span class="math inline">\(p\)</span>-value is smaller than the chosen significance level (e.g., 0.05 or 0.01), we reject the null hypothesis. Otherwise, we fail to reject it. This approach is both convenient and precise, especially with software like R that handles the calculations automatically.</p>
</div>
</div>
</section></section><section id="exercises" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li>We model <strong>miles per gallon (<code>mpg</code>)</strong> as a function of two predictors: <strong>horsepower (<code>hp</code>)</strong> and <strong>weight (<code>wt</code>)</strong>.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
<p><strong>Tasks</strong></p>
<ol type="a">
<li>Write out the estimated regression equation using the model output.<br>
</li>
<li>Which coefficients are statistically significant at the 5% level?<br>
</li>
<li>Interpret the coefficient on <code>wt</code> in the context of the model.<br>
</li>
<li>What does the p-value for <code>hp</code> tell you about its relationship with <code>mpg</code>, after controlling for <code>wt</code>?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Based on the model output, we get the estimated equation:</li>
</ol>
<p><span class="math display">\[
\widehat{\text{mpg}} = 37.23 - 0.032 \cdot \text{hp} - 3.88 \cdot \text{wt}
\]</span></p>
<ol start="2" type="a">
<li>The coefficients on both <code>hp</code> and <code>wt</code> are statistically significant at the 5% level. Their p-values are:</li>
</ol>
<ul>
<li>
<code>hp</code>: p ≈ 0.002</li>
<li>
<code>wt</code>: p &lt; 0.001</li>
</ul>
<ol start="3" type="a">
<li><p>The coefficient for <code>wt</code> is approximately <strong>−3.88</strong>. This means that, <em>holding horsepower constant</em>, a 1-unit increase in car weight (1,000 lbs) is associated with a <strong>3.88 mpg decrease</strong> in fuel efficiency on average.</p></li>
<li><p>The p-value for <code>hp</code> (≈ 0.002) indicates that horsepower has a statistically significant <strong>negative</strong> relationship with <code>mpg</code>, even when we account for car weight. More horsepower reduces fuel efficiency after adjusting for weight.</p></li>
</ol>
</div>
</div>
</div>
<ol start="2" type="1">
<li>We want to understand how <strong>home prices</strong> are affected by three factors: <strong>lot size</strong>, <strong>square footage</strong>, and <strong>number of bedrooms</strong>. To do this, we fit the following multiple linear regression model using data from the <code>hprice1</code> dataset in the <code>wooldridge</code> package:</li>
</ol>
<p><span class="math display">\[
\text{price} = \beta_0 + \beta_1\,\text{lotsize} + \beta_2\,\text{sqrft} + \beta_3\,\text{bdrms} + \varepsilon
\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(\text{price}\)</span> is the house price in thousands of dollars,</li>
<li>
<span class="math inline">\(\text{lotsize}\)</span> is the size of the lot in square feet,</li>
<li>
<span class="math inline">\(\text{sqrft}\)</span> is the size of the house in square feet,</li>
<li>
<span class="math inline">\(\text{bdrms}\)</span> is the number of bedrooms.</li>
</ul>
<p>We obtained the following <strong>95% confidence intervals</strong> for the estimated coefficients:</p>
<table class="caption-top table">
<thead><tr class="header">
<th>Term</th>
<th>2.5 %</th>
<th>97.5 %</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td><span class="math inline">\(-80.38\)</span></td>
<td><span class="math inline">\(36.84\)</span></td>
</tr>
<tr class="even">
<td>lotsize</td>
<td><span class="math inline">\(0.00079\)</span></td>
<td><span class="math inline">\(0.00333\)</span></td>
</tr>
<tr class="odd">
<td>sqrft</td>
<td><span class="math inline">\(0.0965\)</span></td>
<td><span class="math inline">\(0.1491\)</span></td>
</tr>
<tr class="even">
<td>bdrms</td>
<td><span class="math inline">\(-4.07\)</span></td>
<td><span class="math inline">\(31.77\)</span></td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>For each coefficient, determine whether zero is included in the interval. What does this imply about the hypothesis <span class="math inline">\(H_0: \beta_k = 0\)</span>?</p></li>
<li><p>Interpret the confidence interval for <span class="math inline">\(\beta_1\)</span> (the effect of lot size).</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(a) Hypothesis Tests via Confidence Intervals:</strong></p>
<ul>
<li><p><strong>lotsize:</strong><br>
The interval is <span class="math inline">\((0.00079,\; 0.00333)\)</span>, which <strong>does not contain 0</strong>.<br>
⟶ We reject <span class="math inline">\(H_0: \beta_1 = 0\)</span>. Lot size has a statistically significant positive effect on house price.</p></li>
<li><p><strong>sqrft:</strong><br>
The interval is <span class="math inline">\((0.0965,\; 0.1491)\)</span>, again <strong>excluding 0</strong>.<br>
⟶ <span class="math inline">\(H_0: \beta_2 = 0\)</span> is rejected. Square footage significantly affects price.</p></li>
<li><p><strong>bdrms:</strong><br>
The interval is <span class="math inline">\((-4.07,\; 31.77)\)</span>, which <strong>includes 0</strong>.<br>
⟶ We <strong>fail to reject</strong> <span class="math inline">\(H_0: \beta_3 = 0\)</span>. The number of bedrooms does <strong>not</strong> have a statistically significant effect when controlling for the other variables.</p></li>
</ul>
<p><strong>(b) Interpretation of <span class="math inline">\(\beta_1\)</span> (lotsize):</strong></p>
<p>We are 95% confident that the effect of a one square foot increase in lot size is associated with an increase in house price between <strong>$0.00079 and $0.00333 thousand dollars</strong>, or <strong>$0.79 to $3.33 dollars</strong>, holding square footage and number of bedrooms constant.</p>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/termehs\.github\.io\/found-stats\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../regression/mlr.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../regression/reg-cats.html" class="pagination-link" aria-label="Categorical Variables in Regression">
        <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Categorical Variables in Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Foundational Statistics by Termeh Shafie.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/termehs/found-stats/edit/main/regression/reg-inf.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/termehs/found-stats/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>